var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/lib/excelExport.ts
var excelExport_exports = {};
__export(excelExport_exports, {
  buildCmaWorkbook: () => buildCmaWorkbook,
  downloadCmaExcel: () => downloadCmaExcel
});
module.exports = __toCommonJS(excelExport_exports);
var import_exceljs = __toESM(require("exceljs"), 1);

// src/lib/format.ts
var UNIT_DIVISOR = { rs: 1, thousands: 1e3, lakhs: 1e5 };
var UNIT_LABEL = { rs: "\u20B9", thousands: "\u20B9 '000", lakhs: "\u20B9 Lakhs" };

// src/lib/excelExport.ts
var BASE_EXPENSES = [
  { label: "Power & Fuel", key: "powerFuel" },
  { label: "Direct Labour & Wages", key: "directLabour" },
  { label: "Salary & Employee Benefits", key: "salary" },
  { label: "Freight & Cartage", key: "freight" },
  { label: "Sales Promotion & Distribution", key: "salesPromo" },
  { label: "Travelling & Conveyance", key: "travelAdmin" },
  { label: "Repairs & Maintenance", key: "repairs" },
  { label: "Professional Fees", key: "professionalFees" },
  { label: "Operating Expenses (General)", key: "operatingExp" },
  { label: "Other Expenses", key: "otherExp" },
  { label: "Custom Expense 1", key: "customExp1" },
  { label: "Custom Expense 2", key: "customExp2" }
];
var col = (i) => {
  let c = i + 2, s = "";
  while (c > 0) {
    const m = (c - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    c = Math.floor((c - 1) / 26);
  }
  return s;
};
async function buildCmaWorkbook(result) {
  const { config, sim, years, emiSchedule, depSchedule } = result;
  const div = UNIT_DIVISOR[config.unit];
  const nA = config.actualYears;
  const V = (v) => +(v / div).toFixed(2);
  const customHeads = config.customHeads || [];
  const expRows = [
    ...BASE_EXPENSES,
    ...customHeads.filter((h) => h.kind === "expense").map((h) => ({ label: h.name, headId: h.id }))
  ];
  const liabCustom = customHeads.filter((h) => h.kind === "liability");
  const assetCustom = customHeads.filter((h) => h.kind === "asset");
  const wb = new import_exceljs.default.Workbook();
  wb.creator = "CMA Pro Builder";
  wb.created = /* @__PURE__ */ new Date();
  wb.calcProperties = { fullCalcOnLoad: true };
  const headerStyle = (ws, row, nCols) => {
    const r = ws.getRow(row);
    r.font = { bold: true };
    r.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFDCE6F1" } };
    for (let c = 1; c <= nCols; c++) r.getCell(c).border = { bottom: { style: "thin" } };
  };
  const sectionRow = (ws, row, text) => {
    ws.getCell(`A${row}`).value = text;
    ws.getRow(row).font = { bold: true, color: { argb: "FF1F4E79" } };
    ws.getRow(row).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEBF1FA" } };
  };
  const numFmt = "#,##0.00";
  const applyNum = (ws) => {
    ws.eachRow((row) => row.eachCell((cell) => {
      if (typeof cell.value === "number" || cell.value?.formula) cell.numFmt = numFmt;
    }));
  };
  const A = wb.addWorksheet("Assumptions");
  A.getColumn(1).width = 38;
  A.getColumn(2).width = 14;
  A.getCell("A1").value = `CMA DATA \u2014 ${config.clientName}`;
  A.getCell("A1").font = { bold: true, size: 14 };
  A.getCell("A2").value = `All amounts in ${UNIT_LABEL[config.unit]} \xB7 generated by CMA Pro Builder`;
  const asm = [
    ["Sales Growth % p.a.", sim.salesGrowth],
    ["Cost Efficiency Boost %", sim.marginAdj],
    ["RM Consumed as % of Sales", 0],
    ["Inventory Days", sim.inventoryDays],
    ["Debtor Days", sim.debtorDays],
    ["Creditor Days", sim.creditorDays],
    ["Tax Rate %", sim.taxRate],
    ["Dividend % of PAT", sim.dividendPct],
    ["Minimum Cash Balance", V(sim.minCashBalance)],
    ["CC Limit", V(config.loan.ccLimit)],
    ["CC Interest Rate %", config.loan.ccRate],
    ["Grant Month Index (0=Apr)", config.loan.grantMonthIndex],
    ["Term Loan Amount", V(config.loan.tlAmount)]
  ];
  asm.forEach(([label, val], i) => {
    A.getCell(`A${4 + i}`).value = label;
    A.getCell(`B${4 + i}`).value = val;
  });
  const base = years[nA - 1];
  const rmRate = base.sales > 0 ? base.rmConsumed / base.sales : 0;
  A.getCell("B6").value = +rmRate.toFixed(6);
  A.getCell("A19").value = "Expense ratios (% of sales, from latest actual year)";
  A.getCell("A19").font = { bold: true };
  expRows.forEach((er, i) => {
    const r = 20 + i;
    A.getCell(`A${r}`).value = er.label;
    const baseVal = er.key ? base[er.key] : base.customHeadValues?.[er.headId] || 0;
    A.getCell(`B${r}`).value = +(base.sales > 0 ? baseVal / base.sales : 0).toFixed(6);
  });
  const AM = (i) => `Assumptions!$B$${i}`;
  const GROWTH = AM(4), EFF = AM(5), RMRATE = AM(6), INVD = AM(7), DEBD = AM(8), CRED = AM(9), TAXR = AM(10), DIVP = AM(11), CCLIM = AM(13), CCRATE = AM(14), GMTH = AM(15), TLAMT = AM(16);
  const expRate = (i) => `Assumptions!$B$${20 + i}`;
  const L = wb.addWorksheet("Loan Schedule");
  L.getRow(1).values = ["Month", "Date", "FY Index", "Opening", "EMI", "Interest", "Principal", "Closing"];
  headerStyle(L, 1, 8);
  emiSchedule.forEach((r) => {
    L.addRow([r.month, r.date, r.fyIndex, V(r.opening), V(r.emi), V(r.interest), V(r.principal), V(r.closing)]);
  });
  L.columns.forEach((c) => {
    c.width = 12;
  });
  applyNum(L);
  const D = wb.addWorksheet("Depreciation");
  D.getColumn(1).width = 34;
  D.getCell("A1").value = "Depreciation Schedule (WDV)";
  D.getCell("A1").font = { bold: true, size: 12 };
  D.getRow(2).values = ["Block", ...years.map((y) => y.year)];
  headerStyle(D, 2, years.length + 1);
  let dRow = 3;
  const depTotalRow = 3 + config.assetBlocks.length * 4;
  const netBlockRow = depTotalRow + 1;
  config.assetBlocks.forEach((b, bi) => {
    const openR = dRow, addR = dRow + 1, depR = dRow + 2, closeR = dRow + 3;
    D.getCell(`A${openR}`).value = `${b.name} \u2014 Opening (${b.rate}%)`;
    D.getCell(`A${addR}`).value = `${b.name} \u2014 Addition`;
    D.getCell(`A${depR}`).value = `${b.name} \u2014 Depreciation`;
    D.getCell(`A${closeR}`).value = `${b.name} \u2014 Closing WDV`;
    years.forEach((_, i) => {
      const c = col(i), p = col(i - 1);
      const dv = depSchedule[i].blocks[bi];
      if (i === 0) D.getCell(`${c}${openR}`).value = V(dv.opening);
      else D.getCell(`${c}${openR}`).value = { formula: `${p}${closeR}` };
      D.getCell(`${c}${addR}`).value = V(dv.addition);
      D.getCell(`${c}${depR}`).value = { formula: `(${c}${openR}+${c}${addR})*${b.rate / 100}` };
      D.getCell(`${c}${closeR}`).value = { formula: `${c}${openR}+${c}${addR}-${c}${depR}` };
    });
    dRow += 4;
  });
  D.getCell(`A${depTotalRow}`).value = "TOTAL DEPRECIATION";
  D.getCell(`A${netBlockRow}`).value = "TOTAL NET BLOCK";
  [depTotalRow, netBlockRow].forEach((r) => {
    D.getRow(r).font = { bold: true };
  });
  years.forEach((_, i) => {
    const c = col(i);
    const depCells = config.assetBlocks.map((_2, bi) => `${c}${3 + bi * 4 + 2}`).join("+");
    const closeCells = config.assetBlocks.map((_2, bi) => `${c}${3 + bi * 4 + 3}`).join("+");
    D.getCell(`${c}${depTotalRow}`).value = { formula: depCells };
    D.getCell(`${c}${netBlockRow}`).value = { formula: closeCells };
  });
  years.forEach((_, i) => {
    D.getColumn(2 + i).width = 13;
  });
  applyNum(D);
  const depTotalRef = (i) => `Depreciation!${col(i)}${depTotalRow}`;
  const netBlockRef = (i) => `Depreciation!${col(i)}${netBlockRow}`;
  const O = wb.addWorksheet("Operating Statement");
  O.getColumn(1).width = 36;
  O.getCell("A1").value = "FORM-II : OPERATING STATEMENT";
  O.getCell("A1").font = { bold: true, size: 12 };
  O.getCell("A2").value = `For the year ended/ending 31st March \xB7 ${UNIT_LABEL[config.unit]}`;
  O.getRow(3).values = ["Particulars", ...years.map((y) => `${y.year} (${y.type})`)];
  headerStyle(O, 3, years.length + 1);
  const expStart = 12, expEnd = expStart + expRows.length - 1;
  const R = {
    sales: 5,
    otherInc: 6,
    rmOpen: 8,
    rmPur: 9,
    rmClose: 10,
    rmCons: 11,
    expStart,
    expEnd,
    totExp: expEnd + 1,
    ebitda: expEnd + 2,
    dep: expEnd + 3,
    intCC: expEnd + 4,
    intTL: expEnd + 5,
    bankCh: expEnd + 6,
    pbt: expEnd + 7,
    tax: expEnd + 8,
    pat: expEnd + 9,
    div: expEnd + 10,
    retained: expEnd + 11,
    nca: expEnd + 12
  };
  sectionRow(O, 4, "INCOME");
  O.getCell(`A${R.sales}`).value = "Gross Sales";
  O.getCell(`A${R.otherInc}`).value = "Other Income";
  sectionRow(O, 7, "COST OF SALES");
  O.getCell(`A${R.rmOpen}`).value = "Opening Stock";
  O.getCell(`A${R.rmPur}`).value = "Add: Purchases";
  O.getCell(`A${R.rmClose}`).value = "Less: Closing Stock";
  O.getCell(`A${R.rmCons}`).value = "Raw Material Consumed";
  O.getRow(R.rmCons).font = { bold: true };
  expRows.forEach((er, i) => {
    O.getCell(`A${R.expStart + i}`).value = er.label;
  });
  O.getCell(`A${R.totExp}`).value = "Total Expenses (incl. Power & Labour)";
  O.getRow(R.totExp).font = { bold: true };
  O.getCell(`A${R.ebitda}`).value = "PBDIT / EBITDA";
  O.getRow(R.ebitda).font = { bold: true };
  O.getCell(`A${R.dep}`).value = "Depreciation";
  O.getCell(`A${R.intCC}`).value = "Interest \u2014 Cash Credit";
  O.getCell(`A${R.intTL}`).value = "Interest \u2014 Term Loan";
  O.getCell(`A${R.bankCh}`).value = "Bank Charges";
  O.getCell(`A${R.pbt}`).value = "Profit Before Tax";
  O.getRow(R.pbt).font = { bold: true };
  O.getCell(`A${R.tax}`).value = "Provision for Tax";
  O.getCell(`A${R.pat}`).value = "Net Profit After Tax";
  O.getRow(R.pat).font = { bold: true };
  O.getCell(`A${R.div}`).value = "Dividend";
  O.getCell(`A${R.retained}`).value = "Retained Profit";
  O.getCell(`A${R.nca}`).value = "Net Cash Accrual (PAT + Dep)";
  O.getRow(R.nca).font = { bold: true };
  years.forEach((y, i) => {
    const c = col(i), p = col(i - 1);
    const isActual = i < nA;
    if (isActual) {
      O.getCell(`${c}${R.sales}`).value = V(y.sales);
      O.getCell(`${c}${R.otherInc}`).value = V(y.otherIncome);
      O.getCell(`${c}${R.rmOpen}`).value = V(y.rmOpening);
      O.getCell(`${c}${R.rmPur}`).value = V(y.rmPurchases);
      O.getCell(`${c}${R.rmClose}`).value = V(y.rmClosing);
      expRows.forEach((er, ei) => {
        O.getCell(`${c}${R.expStart + ei}`).value = V(er.key ? y[er.key] : y.customHeadValues?.[er.headId] || 0);
      });
      O.getCell(`${c}${R.dep}`).value = V(y.depreciation);
      O.getCell(`${c}${R.intCC}`).value = V(y.interestCC);
      O.getCell(`${c}${R.intTL}`).value = V(y.interestTL);
      O.getCell(`${c}${R.bankCh}`).value = V(y.bankCharges);
      O.getCell(`${c}${R.tax}`).value = V(y.tax);
      O.getCell(`${c}${R.div}`).value = V(y.dividend);
    } else {
      O.getCell(`${c}${R.sales}`).value = { formula: `${p}${R.sales}*(1+${GROWTH}/100)` };
      O.getCell(`${c}${R.otherInc}`).value = 0;
      O.getCell(`${c}${R.rmCons}`).value = { formula: `${c}${R.sales}*${RMRATE}*(1-${EFF}/100)` };
      O.getCell(`${c}${R.rmOpen}`).value = { formula: `${p}${R.rmClose}` };
      O.getCell(`${c}${R.rmClose}`).value = { formula: `${c}${R.sales}/365*${INVD}` };
      O.getCell(`${c}${R.rmPur}`).value = { formula: `${c}${R.rmCons}+${c}${R.rmClose}-${c}${R.rmOpen}` };
      expRows.forEach((_, ei) => {
        O.getCell(`${c}${R.expStart + ei}`).value = { formula: `${c}${R.sales}*${expRate(ei)}*(1-${EFF}/100)` };
      });
      O.getCell(`${c}${R.dep}`).value = { formula: depTotalRef(i) };
      const ccF = i === nA ? `${CCLIM}*${CCRATE}/100*(12-${GMTH})/12` : `${CCLIM}*${CCRATE}/100`;
      O.getCell(`${c}${R.intCC}`).value = { formula: config.loan.loanType !== "tl" ? ccF : "0" };
      O.getCell(`${c}${R.intTL}`).value = { formula: `SUMIF('Loan Schedule'!C:C,${i},'Loan Schedule'!F:F)` };
      O.getCell(`${c}${R.bankCh}`).value = V(y.bankCharges);
      O.getCell(`${c}${R.tax}`).value = { formula: `MAX(0,${c}${R.pbt}*${TAXR}/100)` };
      O.getCell(`${c}${R.div}`).value = { formula: `MAX(0,${c}${R.pat}*${DIVP}/100)` };
    }
    if (isActual) {
      O.getCell(`${c}${R.rmCons}`).value = { formula: `${c}${R.rmOpen}+${c}${R.rmPur}-${c}${R.rmClose}` };
    }
    O.getCell(`${c}${R.totExp}`).value = { formula: `SUM(${c}${R.expStart}:${c}${R.expEnd})` };
    O.getCell(`${c}${R.ebitda}`).value = { formula: `${c}${R.sales}+${c}${R.otherInc}-${c}${R.rmCons}-${c}${R.totExp}` };
    O.getCell(`${c}${R.pbt}`).value = { formula: `${c}${R.ebitda}-${c}${R.dep}-${c}${R.intCC}-${c}${R.intTL}-${c}${R.bankCh}` };
    O.getCell(`${c}${R.pat}`).value = { formula: `${c}${R.pbt}-${c}${R.tax}` };
    O.getCell(`${c}${R.retained}`).value = { formula: `${c}${R.pat}-${c}${R.div}` };
    O.getCell(`${c}${R.nca}`).value = { formula: `${c}${R.pat}+${c}${R.dep}` };
  });
  years.forEach((_, i) => {
    O.getColumn(2 + i).width = 14;
  });
  applyNum(O);
  const Oref = (row, i) => `'Operating Statement'!${col(i)}${row}`;
  const B = wb.addWorksheet("Balance Sheet");
  B.getColumn(1).width = 36;
  B.getCell("A1").value = "FORM-III : ANALYSIS OF BALANCE SHEET";
  B.getCell("A1").font = { bold: true, size: 12 };
  B.getRow(3).values = ["Particulars", ...years.map((y) => `${y.year} (${y.type})`)];
  headerStyle(B, 3, years.length + 1);
  const BR = {
    cap: 5,
    res: 6,
    nw: 7,
    tl: 8,
    cpltd: 9,
    cc: 10,
    uns: 11,
    cred: 12,
    ocl: 13,
    customLStart: 14,
    totL: 14 + liabCustom.length,
    assetsSection: 15 + liabCustom.length,
    fa: 16 + liabCustom.length,
    depo: 17 + liabCustom.length,
    inv: 18 + liabCustom.length,
    stock: 19 + liabCustom.length,
    debt: 20 + liabCustom.length,
    cash: 21 + liabCustom.length,
    oca: 22 + liabCustom.length,
    customAStart: 23 + liabCustom.length,
    totA: 23 + liabCustom.length + assetCustom.length,
    diff: 24 + liabCustom.length + assetCustom.length
  };
  sectionRow(B, 4, "LIABILITIES");
  const bsLabels = [
    [BR.cap, "Share Capital"],
    [BR.res, "Reserves & Surplus"],
    [BR.nw, "Net Worth"],
    [BR.tl, "Term Loan (total o/s)"],
    [BR.cpltd, "  of which CPLTD (next 12m)"],
    [BR.cc, "Cash Credit"],
    [BR.uns, "Unsecured Loans"],
    [BR.cred, "Creditors / Payables"],
    [BR.ocl, "Other Current Liabilities"],
    [BR.totL, "TOTAL LIABILITIES"]
  ];
  bsLabels.forEach(([r, t]) => {
    B.getCell(`A${r}`).value = t;
  });
  liabCustom.forEach((h, k) => {
    B.getCell(`A${BR.customLStart + k}`).value = `${h.name} (${h.current ? "current" : "non-current"})`;
  });
  [BR.nw, BR.totL].forEach((r) => {
    B.getRow(r).font = { bold: true };
  });
  sectionRow(B, BR.assetsSection, "ASSETS");
  const bsLabels2 = [
    [BR.fa, "Fixed Assets (Net Block)"],
    [BR.depo, "Deposits & Advances"],
    [BR.inv, "Investments"],
    [BR.stock, "Stock / Inventory"],
    [BR.debt, "Debtors / Receivables"],
    [BR.cash, "Cash & Bank"],
    [BR.oca, "Other Current Assets"],
    [BR.totA, "TOTAL ASSETS"],
    [BR.diff, "Difference (should be 0)"]
  ];
  bsLabels2.forEach(([r, t]) => {
    B.getCell(`A${r}`).value = t;
  });
  assetCustom.forEach((h, k) => {
    B.getCell(`A${BR.customAStart + k}`).value = `${h.name} (${h.current ? "current" : "non-current"})`;
  });
  B.getRow(BR.totA).font = { bold: true };
  years.forEach((y, i) => {
    const c = col(i), p = col(i - 1);
    const isActual = i < nA;
    B.getCell(`${c}${BR.cap}`).value = V(y.shareCapital);
    if (isActual) {
      B.getCell(`${c}${BR.res}`).value = V(y.reserves);
      B.getCell(`${c}${BR.tl}`).value = V(y.termLoan);
      B.getCell(`${c}${BR.cpltd}`).value = V(y.cpltd);
      B.getCell(`${c}${BR.cc}`).value = V(y.cc);
      B.getCell(`${c}${BR.cred}`).value = V(y.creditors);
      B.getCell(`${c}${BR.ocl}`).value = V(y.otherCurrentLiab);
      B.getCell(`${c}${BR.fa}`).value = V(y.fixedAssets);
      B.getCell(`${c}${BR.stock}`).value = V(y.stock);
      B.getCell(`${c}${BR.debt}`).value = V(y.debtors);
      B.getCell(`${c}${BR.cash}`).value = V(y.cash);
    } else {
      B.getCell(`${c}${BR.res}`).value = { formula: `${p}${BR.res}+${Oref(R.retained, i)}` };
      B.getCell(`${c}${BR.tl}`).value = { formula: `${TLAMT}-SUMIF('Loan Schedule'!C:C,"<="&${i},'Loan Schedule'!G:G)` };
      B.getCell(`${c}${BR.cpltd}`).value = { formula: `SUMIF('Loan Schedule'!C:C,${i + 1},'Loan Schedule'!G:G)` };
      B.getCell(`${c}${BR.cc}`).value = config.loan.loanType !== "tl" ? { formula: CCLIM } : 0;
      B.getCell(`${c}${BR.cred}`).value = { formula: `${Oref(R.rmPur, i)}/365*${CRED}` };
      B.getCell(`${c}${BR.ocl}`).value = { formula: `${p}${BR.ocl}*1.05` };
      B.getCell(`${c}${BR.fa}`).value = { formula: netBlockRef(i) };
      B.getCell(`${c}${BR.stock}`).value = { formula: Oref(R.rmClose, i) };
      B.getCell(`${c}${BR.debt}`).value = { formula: `${Oref(R.sales, i)}/365*${DEBD}` };
      B.getCell(`${c}${BR.cash}`).value = { formula: `${c}${BR.totL}-(${c}${BR.fa}+${c}${BR.depo}+${c}${BR.inv}+${c}${BR.stock}+${c}${BR.debt}+${c}${BR.oca}${assetCustom.map((_, k) => `+${c}${BR.customAStart + k}`).join("")})` };
    }
    liabCustom.forEach((h, k) => {
      const cell = B.getCell(`${c}${BR.customLStart + k}`);
      if (isActual) cell.value = V(y.customHeadValues?.[h.id] || 0);
      else cell.value = h.current ? { formula: `${p}${BR.customLStart + k}*1.05` } : V(y.customHeadValues?.[h.id] || 0);
    });
    assetCustom.forEach((h, k) => {
      B.getCell(`${c}${BR.customAStart + k}`).value = V(y.customHeadValues?.[h.id] || 0);
    });
    B.getCell(`${c}${BR.uns}`).value = V(y.unsecured);
    B.getCell(`${c}${BR.depo}`).value = V(y.deposits);
    B.getCell(`${c}${BR.inv}`).value = V(y.investments);
    B.getCell(`${c}${BR.oca}`).value = V(y.otherCurrentAssets);
    B.getCell(`${c}${BR.nw}`).value = { formula: `${c}${BR.cap}+${c}${BR.res}` };
    const customLTerms = liabCustom.map((_, k) => `+${c}${BR.customLStart + k}`).join("");
    B.getCell(`${c}${BR.totL}`).value = { formula: `${c}${BR.cap}+${c}${BR.res}+${c}${BR.tl}+${c}${BR.cc}+${c}${BR.uns}+${c}${BR.cred}+${c}${BR.ocl}${customLTerms}` };
    B.getCell(`${c}${BR.totA}`).value = { formula: `SUM(${c}${BR.fa}:${c}${BR.totA - 1})` };
    B.getCell(`${c}${BR.diff}`).value = { formula: `${c}${BR.totL}-${c}${BR.totA}` };
  });
  years.forEach((_, i) => {
    B.getColumn(2 + i).width = 14;
  });
  applyNum(B);
  const RA = wb.addWorksheet("Ratio Analysis");
  RA.getColumn(1).width = 34;
  RA.getCell("A1").value = "KEY RATIOS";
  RA.getCell("A1").font = { bold: true, size: 12 };
  RA.getRow(3).values = ["Ratio", ...years.map((y) => y.year)];
  headerStyle(RA, 3, years.length + 1);
  const customCurA = assetCustom.map((h, k) => ({ h, row: BR.customAStart + k })).filter((x) => x.h.current);
  const customCurL = liabCustom.map((h, k) => ({ h, row: BR.customLStart + k })).filter((x) => x.h.current);
  const intTot = (i) => `(${Oref(R.intCC, i)}+${Oref(R.intTL, i)}+${Oref(R.bankCh, i)})`;
  const tlPrin = (i) => `SUMIF('Loan Schedule'!C:C,${i},'Loan Schedule'!G:G)`;
  const caRef = (i) => `('Balance Sheet'!${col(i)}${BR.stock}+'Balance Sheet'!${col(i)}${BR.debt}+'Balance Sheet'!${col(i)}${BR.cash}+'Balance Sheet'!${col(i)}${BR.oca}${customCurA.map((x) => `+'Balance Sheet'!${col(i)}${x.row}`).join("")})`;
  const clRef = (i) => `('Balance Sheet'!${col(i)}${BR.cc}+'Balance Sheet'!${col(i)}${BR.cred}+'Balance Sheet'!${col(i)}${BR.ocl}+'Balance Sheet'!${col(i)}${BR.cpltd}${customCurL.map((x) => `+'Balance Sheet'!${col(i)}${x.row}`).join("")})`;
  const nwRef = (i) => `'Balance Sheet'!${col(i)}${BR.nw}`;
  const ratioDefs = [
    { label: "Current Ratio (norm \u2265 1.23)", f: (i) => `IF(${clRef(i)}=0,0,${caRef(i)}/${clRef(i)})` },
    { label: "DSCR (norm \u2265 1.75)", f: (i) => `IF((${Oref(R.intTL, i)}+${tlPrin(i)})=0,0,(${Oref(R.pat, i)}+${Oref(R.dep, i)}+${Oref(R.intTL, i)})/(${Oref(R.intTL, i)}+${tlPrin(i)}))` },
    { label: "Debt / Equity (norm \u2264 3.00)", f: (i) => `IF(${nwRef(i)}=0,0,('Balance Sheet'!${col(i)}${BR.tl}-'Balance Sheet'!${col(i)}${BR.cpltd}+'Balance Sheet'!${col(i)}${BR.uns})/${nwRef(i)})` },
    { label: "TOL / TNW (norm \u2264 4.50)", f: (i) => `IF(${nwRef(i)}=0,0,('Balance Sheet'!${col(i)}${BR.totL}-${nwRef(i)})/${nwRef(i)})` },
    { label: "Interest Coverage (norm \u2265 2.60)", f: (i) => `IF(${intTot(i)}=0,0,(${Oref(R.pbt, i)}+${intTot(i)})/${intTot(i)})` },
    { label: "Net Profit Ratio %", f: (i) => `IF(${Oref(R.sales, i)}=0,0,${Oref(R.pat, i)}/${Oref(R.sales, i)}*100)` },
    { label: "Return on Investment %", f: (i) => `IF((${nwRef(i)}+'Balance Sheet'!${col(i)}${BR.tl})=0,0,${Oref(R.pat, i)}/(${nwRef(i)}+'Balance Sheet'!${col(i)}${BR.tl})*100)` }
  ];
  ratioDefs.forEach((rd, ri) => {
    const row = 4 + ri;
    RA.getCell(`A${row}`).value = rd.label;
    years.forEach((_, i) => {
      RA.getCell(`${col(i)}${row}`).value = { formula: rd.f(i) };
    });
  });
  years.forEach((_, i) => {
    RA.getColumn(2 + i).width = 13;
  });
  applyNum(RA);
  const M = wb.addWorksheet("MPBF & DP");
  M.getColumn(1).width = 44;
  M.getCell("A1").value = "MAXIMUM PERMISSIBLE BANK FINANCE & DRAWING POWER";
  M.getCell("A1").font = { bold: true, size: 12 };
  M.getRow(3).values = ["Particulars", ...years.map((y) => y.year)];
  headerStyle(M, 3, years.length + 1);
  const oclX = (i) => `('Balance Sheet'!${col(i)}${BR.cred}+'Balance Sheet'!${col(i)}${BR.ocl})`;
  const mRows = [
    { label: "TANDON METHOD (Balance Sheet Method)", section: true },
    { label: "Total Current Assets", f: (i) => caRef(i) },
    { label: "Other Current Liabilities (excl. bank)", f: (i) => oclX(i) },
    { label: "Working Capital Gap", f: (i) => `${caRef(i)}-${oclX(i)}`, bold: true },
    { label: "Less: 25% minimum margin of CA", f: (i) => `0.25*${caRef(i)}` },
    { label: "MPBF \u2014 Tandon", f: (i) => `MAX(0,0.75*${caRef(i)}-${oclX(i)})`, bold: true },
    { label: "TURNOVER METHOD (Nayak Committee)", section: true },
    { label: "Sales Turnover", f: (i) => Oref(R.sales, i) },
    { label: "25% of Turnover", f: (i) => `0.25*${Oref(R.sales, i)}` },
    { label: "Less: 5% margin by promoter", f: (i) => `0.05*${Oref(R.sales, i)}` },
    { label: "MPBF \u2014 Turnover (20% of sales)", f: (i) => `0.2*${Oref(R.sales, i)}`, bold: true },
    { label: "DRAWING POWER", section: true },
    { label: `Stock after ${config.loan.ccStockMarginPct}% margin`, f: (i) => `'Balance Sheet'!${col(i)}${BR.stock}*(1-${config.loan.ccStockMarginPct}/100)` },
    { label: `Debtors (\u2264${config.loan.ccDebtorCoverDays}d) after ${config.loan.ccDebtorMarginPct}% margin`, f: (i) => `MIN('Balance Sheet'!${col(i)}${BR.debt},${Oref(R.sales, i)}/365*${config.loan.ccDebtorCoverDays})*(1-${config.loan.ccDebtorMarginPct}/100)` },
    { label: "Total Drawing Power", f: (i) => `'Balance Sheet'!${col(i)}${BR.stock}*(1-${config.loan.ccStockMarginPct}/100)+MIN('Balance Sheet'!${col(i)}${BR.debt},${Oref(R.sales, i)}/365*${config.loan.ccDebtorCoverDays})*(1-${config.loan.ccDebtorMarginPct}/100)`, bold: true },
    { label: "CC Limit / Drawing", f: (i) => `'Balance Sheet'!${col(i)}${BR.cc}` }
  ];
  mRows.forEach((rd, ri) => {
    const row = 4 + ri;
    M.getCell(`A${row}`).value = rd.label;
    if (rd.bold) M.getRow(row).font = { bold: true };
    if (rd.section) {
      sectionRow(M, row, rd.label);
      return;
    }
    if (rd.f) years.forEach((_, i) => {
      M.getCell(`${col(i)}${row}`).value = { formula: rd.f(i) };
    });
  });
  years.forEach((_, i) => {
    M.getColumn(2 + i).width = 14;
  });
  applyNum(M);
  return wb;
}
async function downloadCmaExcel(result) {
  const wb = await buildCmaWorkbook(result);
  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `CMA_${result.config.clientName.replace(/[^a-z0-9]+/gi, "_")}_${result.config.startYear}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  buildCmaWorkbook,
  downloadCmaExcel
});
