"""
AI Auditor V8 - Professional Word Audit Report Generator
Produces a structured, formatted Word (.docx) document suitable for management, CAs, and lenders.
"""

import os
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from core.models import FinancialModel
from config.constants import APP_NAME, APP_VERSION, DISCLAIMER_TEXT
from analysis.trend_engine import TrendEngine

class WordReportGenerator:

    def __init__(self, model: FinancialModel):
        self.model = model
        self.doc = docx.Document()
        self._setup_page_layout()

    def _setup_page_layout(self):
        """Sets standard 0.75-inch margins for clean readability."""
        for section in self.doc.sections:
            section.top_margin = Inches(0.75)
            section.bottom_margin = Inches(0.75)
            section.left_margin = Inches(0.75)
            section.right_margin = Inches(0.75)

    def _set_cell_background(self, cell, hex_color: str):
        """Fills table cell with background color."""
        shading_xml = f'<w:shd {nsdecls("w")} w:fill="{hex_color}"/>'
        cell._tc.get_or_add_tcPr().append(parse_xml(shading_xml))

    def _set_cell_margins(self, cell, top=80, bottom=80, left=120, right=120):
        """Sets internal cell margins in twips."""
        tcPr = cell._tc.get_or_add_tcPr()
        tcMar = OxmlElement('w:tcMar')
        for margin_name, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
            node = OxmlElement(f'w:{margin_name}')
            node.set(qn('w:w'), str(val))
            node.set(qn('w:type'), 'dxa')
            tcMar.append(node)
        tcPr.append(tcMar)

    def generate(self, output_path: str, chart_paths: dict = None) -> str:
        """Constructs the Word document and saves to disk."""
        self._build_title_page()
        self.doc.add_page_break()

        self._build_executive_summary()
        self._build_financial_statements_section()
        self._build_ratio_analysis_section()
        self._build_trend_analysis_section()
        self._build_variance_analysis_section()
        self._build_possible_reasons_section()
        self._build_audit_verification_section()
        self._build_risk_areas_section()
        self._build_limitations_and_disclaimer()

        self.doc.save(output_path)
        return output_path

    def _build_title_page(self):
        p_top = self.doc.add_paragraph()
        p_top.paragraph_format.space_before = Pt(40)

        # Title
        p_title = self.doc.add_paragraph()
        p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_title = p_title.add_run("FINANCIAL STATEMENT ANALYSIS &\nAUDIT-SUPPORT REPORT")
        run_title.font.name = 'Segoe UI'
        run_title.font.size = Pt(22)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(26, 54, 93)  # Navy

        p_sub = self.doc.add_paragraph()
        p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_sub = p_sub.add_run(f"Comprehensive Analytical Procedures & Verification Review\nGenerated by {APP_NAME} (v{APP_VERSION})")
        run_sub.font.name = 'Segoe UI'
        run_sub.font.size = Pt(11)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(74, 85, 104)

        self.doc.add_paragraph().paragraph_format.space_after = Pt(40)

        # Meta Table
        table = self.doc.add_table(rows=6, cols=2)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.autofit = False

        meta_rows = [
            ("Target Entity / Company Name:", self.model.company_info.name),
            ("Financial Year Covered (Current Period):", self.model.company_info.financial_year_current),
            ("Comparative Period:", self.model.company_info.financial_year_previous),
            ("Reporting Currency & Unit Scale:", self.model.company_info.unit_label),
            ("Engagement / Review Type:", self.model.company_info.engagement_type),
            ("Date of Analytical Review:", self.model.company_info.analysis_date)
        ]

        for idx, (label, val) in enumerate(meta_rows):
            c0 = table.cell(idx, 0)
            c1 = table.cell(idx, 1)
            c0.width = Inches(2.8)
            c1.width = Inches(4.0)

            p0 = c0.paragraphs[0]
            r0 = p0.add_run(label)
            r0.font.name = 'Segoe UI'
            r0.font.bold = True
            r0.font.size = Pt(10)
            r0.font.color.rgb = RGBColor(45, 55, 72)

            p1 = c1.paragraphs[0]
            r1 = p1.add_run(val)
            r1.font.name = 'Segoe UI'
            r1.font.size = Pt(10)

            self._set_cell_background(c0, "F7FAFC")
            self._set_cell_background(c1, "FFFFFF")
            self._set_cell_margins(c0, top=60, bottom=60)
            self._set_cell_margins(c1, top=60, bottom=60)

        self.doc.add_paragraph().paragraph_format.space_after = Pt(30)

        # Note at bottom
        p_bot = self.doc.add_paragraph()
        p_bot.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r_bot = p_bot.add_run("CONFIDENTIAL - PREPARED FOR STATUTORY / INTERNAL AUDITORS & LENDERS")
        r_bot.font.name = 'Segoe UI'
        r_bot.font.size = Pt(9)
        r_bot.font.bold = True
        r_bot.font.color.rgb = RGBColor(113, 128, 150)

    def _build_executive_summary(self):
        h = self.doc.add_heading("1. Executive Summary & Key Highlights", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.paragraph_format.line_spacing = 1.15
        p.add_run(
            f"This analytical report presents a comprehensive financial diagnostic of "
            f"{self.model.company_info.name} covering {self.model.company_info.financial_year_current} "
            f"in comparison with {self.model.company_info.financial_year_previous}. "
            f"All values are denominated in {self.model.company_info.unit_label}."
        )

        # Highlight Table
        p_curr = self.model.periods[0] if self.model.periods else "Current"
        p_prev = self.model.periods[1] if len(self.model.periods) > 1 else "Previous"

        def get_rev(p): return self.model.profit_loss.get_value_by_key("revenue_operations", p, 0.0)
        def get_pat(p): return self.model.profit_loss.get_value_by_key("profit_after_tax", p, 0.0)
        def get_ebitda(p):
            pbt = self.model.profit_loss.get_value_by_key("profit_before_tax", p, 0.0)
            fin = self.model.profit_loss.get_value_by_key("finance_costs", p, 0.0)
            dep = self.model.profit_loss.get_value_by_key("depreciation_amortisation", p, 0.0)
            return pbt + fin + dep

        kpis = [
            ("Revenue from Operations", get_rev(p_curr), get_rev(p_prev)),
            ("EBITDA", get_ebitda(p_curr), get_ebitda(p_prev)),
            ("Profit After Tax (PAT)", get_pat(p_curr), get_pat(p_prev))
        ]

        table = self.doc.add_table(rows=1 + len(kpis), cols=5)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Key Financial Indicator", p_curr, p_prev, "Abs Change", "YoY % Change"]

        # Format header row
        for c_idx, head in enumerate(headers):
            cell = table.cell(0, c_idx)
            self._set_cell_background(cell, "1A365D")
            self._set_cell_margins(cell, top=80, bottom=80)
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER if c_idx > 0 else WD_ALIGN_PARAGRAPH.LEFT
            r = p.add_run(head)
            r.font.name = 'Segoe UI'
            r.font.bold = True
            r.font.size = Pt(9.5)
            r.font.color.rgb = RGBColor(255, 255, 255)

        for r_idx, (name, cy, py) in enumerate(kpis, 1):
            diff = cy - py
            pct = (diff / abs(py) * 100) if py != 0 else 0.0
            
            c0 = table.cell(r_idx, 0)
            c1 = table.cell(r_idx, 1)
            c2 = table.cell(r_idx, 2)
            c3 = table.cell(r_idx, 3)
            c4 = table.cell(r_idx, 4)

            c0.paragraphs[0].add_run(name).font.bold = True
            c1.paragraphs[0].add_run(f"{cy:,.2f}")
            c2.paragraphs[0].add_run(f"{py:,.2f}")
            c3.paragraphs[0].add_run(f"{diff:+,.2f}")
            c4.paragraphs[0].add_run(f"{pct:+.1f}%")

            for idx, c in enumerate([c0, c1, c2, c3, c4]):
                self._set_cell_margins(c, top=60, bottom=60)
                self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")
                if idx > 0:
                    c.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

        self.doc.add_paragraph().paragraph_format.space_after = Pt(12)

    def _build_financial_statements_section(self):
        h = self.doc.add_heading("2. Financial Statements Summary", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        for stmt_name, stmt in [
            ("Balance Sheet Extract", self.model.balance_sheet),
            ("Profit & Loss Statement Extract", self.model.profit_loss)
        ]:
            h2 = self.doc.add_heading(stmt_name, level=2)
            h2.runs[0].font.name = 'Segoe UI'
            h2.runs[0].font.color.rgb = RGBColor(43, 108, 176)

            periods = stmt.periods if stmt.periods else self.model.periods
            num_cols = 1 + len(periods)

            table = self.doc.add_table(rows=1 + len(stmt.line_items[:15]), cols=num_cols)
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            headers = ["Line Item"] + periods
            for c_idx, head in enumerate(headers):
                cell = table.cell(0, c_idx)
                self._set_cell_background(cell, "2B6CB0")
                p = cell.paragraphs[0]
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else WD_ALIGN_PARAGRAPH.RIGHT
                r = p.add_run(head)
                r.font.name = 'Segoe UI'
                r.font.bold = True
                r.font.size = Pt(9)
                r.font.color.rgb = RGBColor(255, 255, 255)

            for r_idx, item in enumerate(stmt.line_items[:15], 1):
                c0 = table.cell(r_idx, 0)
                c0.paragraphs[0].add_run(item.original_name).font.size = Pt(8.5)
                self._set_cell_background(c0, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")

                for p_idx, p_name in enumerate(periods, 1):
                    c = table.cell(r_idx, p_idx)
                    val = item.get_value(p_name, 0.0)
                    p = c.paragraphs[0]
                    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
                    p.add_run(f"{val:,.2f}").font.size = Pt(8.5)
                    self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")

            self.doc.add_paragraph().paragraph_format.space_after = Pt(10)

    def _build_ratio_analysis_section(self):
        h = self.doc.add_heading("3. Financial Ratio Analysis", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.add_run("The table below details 30 standard financial ratios categorized across Liquidity, Profitability, Solvency, and Efficiency.")

        for cat, r_list in self.model.ratios.items():
            h2 = self.doc.add_heading(cat, level=2)
            h2.runs[0].font.name = 'Segoe UI'
            h2.runs[0].font.color.rgb = RGBColor(43, 108, 176)

            table = self.doc.add_table(rows=1 + len(r_list), cols=6)
            table.alignment = WD_TABLE_ALIGNMENT.CENTER
            headers = ["Ratio Name", "Formula", "Current", "Previous", "Benchmark", "Status"]

            for c_idx, head in enumerate(headers):
                cell = table.cell(0, c_idx)
                self._set_cell_background(cell, "1A365D")
                p = cell.paragraphs[0]
                p.alignment = WD_ALIGN_PARAGRAPH.LEFT if c_idx < 2 else WD_ALIGN_PARAGRAPH.CENTER
                r = p.add_run(head)
                r.font.name = 'Segoe UI'
                r.font.bold = True
                r.font.size = Pt(8.5)
                r.font.color.rgb = RGBColor(255, 255, 255)

            for r_idx, r_item in enumerate(r_list, 1):
                c0 = table.cell(r_idx, 0)
                c1 = table.cell(r_idx, 1)
                c2 = table.cell(r_idx, 2)
                c3 = table.cell(r_idx, 3)
                c4 = table.cell(r_idx, 4)
                c5 = table.cell(r_idx, 5)

                c0.paragraphs[0].add_run(r_item["name"]).font.size = Pt(8)
                c0.paragraphs[0].runs[0].font.bold = True
                c1.paragraphs[0].add_run(r_item["formula"]).font.size = Pt(7.5)

                val_cy = f"{r_item['current_value']:,.2f} {r_item['unit']}" if r_item['current_value'] is not None else "N/A"
                val_py = f"{r_item['previous_value']:,.2f} {r_item['unit']}" if r_item['previous_value'] is not None else "N/A"

                c2.paragraphs[0].add_run(val_cy).font.size = Pt(8)
                c2.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
                c3.paragraphs[0].add_run(val_py).font.size = Pt(8)
                c3.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
                c4.paragraphs[0].add_run(r_item["benchmark"]).font.size = Pt(7.5)
                
                run_st = c5.paragraphs[0].add_run(r_item["status"])
                run_st.font.size = Pt(8)
                run_st.font.bold = True
                c5.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

                if r_item["status"] == "Healthy":
                    self._set_cell_background(c5, "C6F6D5")
                elif r_item["status"] in ["Attention", "Critical"]:
                    self._set_cell_background(c5, "FED7D7")

                for c in [c0, c1, c2, c3, c4]:
                    self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")

            self.doc.add_paragraph().paragraph_format.space_after = Pt(8)

    def _build_trend_analysis_section(self):
        h = self.doc.add_heading("4. Horizontal & Vertical Trend Analysis", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        trends = TrendEngine.analyze_trends(self.model)
        rows = trends.get("profit_loss_trends", [])[:10] + trends.get("balance_sheet_trends", [])[:10]
        if not rows:
            return

        table = self.doc.add_table(rows=1 + len(rows), cols=5)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Particulars", "Current Amount", "Prior Amount", "YoY % Change", "Direction"]

        for c_idx, head in enumerate(headers):
            cell = table.cell(0, c_idx)
            self._set_cell_background(cell, "2B6CB0")
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT if c_idx == 0 else WD_ALIGN_PARAGRAPH.RIGHT
            r = p.add_run(head)
            r.font.name = 'Segoe UI'
            r.font.bold = True
            r.font.size = Pt(8.5)
            r.font.color.rgb = RGBColor(255, 255, 255)

        for r_idx, r_item in enumerate(rows, 1):
            c0 = table.cell(r_idx, 0)
            c1 = table.cell(r_idx, 1)
            c2 = table.cell(r_idx, 2)
            c3 = table.cell(r_idx, 3)
            c4 = table.cell(r_idx, 4)

            c0.paragraphs[0].add_run(r_item["particulars"]).font.size = Pt(8)
            c1.paragraphs[0].add_run(f"{r_item['cy_value']:,.2f}").font.size = Pt(8)
            c1.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            c2.paragraphs[0].add_run(f"{r_item['py_value']:,.2f}").font.size = Pt(8)
            c2.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

            pct_str = f"{r_item['pct_change']:+.1f}%" if r_item['pct_change'] is not None else "N/A"
            c3.paragraphs[0].add_run(pct_str).font.size = Pt(8)
            c3.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

            c4.paragraphs[0].add_run(r_item["trend_direction"]).font.size = Pt(8)
            c4.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

            for c in [c0, c1, c2, c3, c4]:
                self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")

        self.doc.add_paragraph().paragraph_format.space_after = Pt(12)

    def _build_variance_analysis_section(self):
        h = self.doc.add_heading("5. Significant Variations Analysis (>= 5% Threshold)", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.add_run(
            f"The application has identified {len(self.model.variations)} line items exhibiting material "
            f"movements greater than or equal to 5% compared to the previous period."
        )

        if not self.model.variations:
            return

        table = self.doc.add_table(rows=1 + len(self.model.variations), cols=6)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Statement", "Particulars", "Prior Amount", "Current Amount", "Change (%)", "Risk Level"]

        for c_idx, head in enumerate(headers):
            cell = table.cell(0, c_idx)
            self._set_cell_background(cell, "1A365D")
            p = cell.paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT if c_idx < 2 else WD_ALIGN_PARAGRAPH.RIGHT
            r = p.add_run(head)
            r.font.name = 'Segoe UI'
            r.font.bold = True
            r.font.size = Pt(8.5)
            r.font.color.rgb = RGBColor(255, 255, 255)

        for r_idx, v in enumerate(self.model.variations, 1):
            c0 = table.cell(r_idx, 0)
            c1 = table.cell(r_idx, 1)
            c2 = table.cell(r_idx, 2)
            c3 = table.cell(r_idx, 3)
            c4 = table.cell(r_idx, 4)
            c5 = table.cell(r_idx, 5)

            c0.paragraphs[0].add_run(v["statement"]).font.size = Pt(8)
            c1.paragraphs[0].add_run(v["particulars"]).font.size = Pt(8)
            c1.paragraphs[0].runs[0].font.bold = True
            c2.paragraphs[0].add_run(f"{v['previous_period_amount']:,.2f}").font.size = Pt(8)
            c2.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            c3.paragraphs[0].add_run(f"{v['current_period_amount']:,.2f}").font.size = Pt(8)
            c3.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
            c4.paragraphs[0].add_run(f"{v['percentage_change']:+.1f}%").font.size = Pt(8)
            c4.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

            c5.paragraphs[0].add_run(v["risk_level"]).font.size = Pt(8)
            c5.paragraphs[0].runs[0].font.bold = True
            c5.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
            if v["risk_level"] == "High":
                self._set_cell_background(c5, "FED7D7")

            for c in [c0, c1, c2, c3, c4]:
                self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")

        self.doc.add_paragraph().paragraph_format.space_after = Pt(12)

    def _build_possible_reasons_section(self):
        h = self.doc.add_heading("6. Possible Reasons for Significant Variations", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.add_run(
            "IMPORTANT NOTICE: The explanations outlined below represent professional hypotheses "
            "derived from financial statement patterns and standard accounting relationships. They do NOT "
            "represent confirmed facts. Primary corroborative evidence must be obtained to confirm actual causes."
        ).font.italic = True

        for v in self.model.variations[:12]:
            p_item = self.doc.add_paragraph()
            p_item.paragraph_format.space_before = Pt(8)
            r_head = p_item.add_run(f"• {v['particulars']} ({v['statement']}) — {v['direction']} of {v['percentage_change']:+.1f}%")
            r_head.font.name = 'Segoe UI'
            r_head.font.bold = True
            r_head.font.size = Pt(10)
            r_head.font.color.rgb = RGBColor(43, 108, 176)

            p_intro = self.doc.add_paragraph()
            p_intro.paragraph_format.left_indent = Inches(0.25)
            p_intro.add_run("POSSIBLE REASONS (May include):").font.bold = True

            for r in v["possible_reasons"]:
                p_r = self.doc.add_paragraph(style='List Bullet')
                p_r.paragraph_format.left_indent = Inches(0.4)
                p_r.add_run(r).font.size = Pt(9)

    def _build_audit_verification_section(self):
        h = self.doc.add_heading("7. Audit Verification Requirements & Corroborative Evidence", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.add_run(
            "In accordance with Standards on Auditing (SA 500 / SA 520), the following specific documents "
            "and schedules are required to obtain sufficient and appropriate audit evidence for material movements."
        )

        # Collect flat list of audit requirements
        flat_reqs = []
        for v in self.model.variations:
            for item in v["audit_verification"]:
                flat_reqs.append((v["particulars"], item["doc"], item["why"]))

        if not flat_reqs:
            return

        table = self.doc.add_table(rows=1 + len(flat_reqs[:25]), cols=3)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Financial Statement Area", "Required Audit Document / Evidence", "WHY Document is Required (Audit Purpose)"]

        for c_idx, head in enumerate(headers):
            cell = table.cell(0, c_idx)
            self._set_cell_background(cell, "1A365D")
            p = cell.paragraphs[0]
            r = p.add_run(head)
            r.font.name = 'Segoe UI'
            r.font.bold = True
            r.font.size = Pt(8.5)
            r.font.color.rgb = RGBColor(255, 255, 255)

        for r_idx, (part, doc_name, why_txt) in enumerate(flat_reqs[:25], 1):
            c0 = table.cell(r_idx, 0)
            c1 = table.cell(r_idx, 1)
            c2 = table.cell(r_idx, 2)

            c0.paragraphs[0].add_run(part).font.size = Pt(8)
            c0.paragraphs[0].runs[0].font.bold = True
            c1.paragraphs[0].add_run(doc_name).font.size = Pt(8)
            c2.paragraphs[0].add_run(why_txt).font.size = Pt(8)

            for c in [c0, c1, c2]:
                self._set_cell_background(c, "F7FAFC" if r_idx % 2 == 0 else "FFFFFF")
                self._set_cell_margins(c, top=40, bottom=40)

        self.doc.add_paragraph().paragraph_format.space_after = Pt(12)

    def _build_risk_areas_section(self):
        h = self.doc.add_heading("8. Potential Risk & Attention Areas Matrix", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p = self.doc.add_paragraph()
        p.add_run("The following potential risk signals were flagged during quantitative and ratio screening:")

        for r in self.model.risks:
            p_box = self.doc.add_paragraph()
            p_box.paragraph_format.space_before = Pt(6)
            
            run_tag = p_box.add_run(f"[{r['severity'].upper()} RISK] {r['title']}\n")
            run_tag.font.bold = True
            run_tag.font.size = Pt(9.5)
            run_tag.font.color.rgb = RGBColor(197, 48, 48) if r['severity'] == "High" else RGBColor(183, 121, 31)

            run_desc = p_box.add_run(f"Finding: {r['description']}\n")
            run_desc.font.size = Pt(9)

            run_imp = p_box.add_run(f"Audit Implication: {r['audit_implication']}")
            run_imp.font.size = Pt(9)
            run_imp.font.italic = True

    def _build_limitations_and_disclaimer(self):
        h = self.doc.add_heading("9. Data Limitations & Professional Disclaimer", level=1)
        h.runs[0].font.name = 'Segoe UI'
        h.runs[0].font.color.rgb = RGBColor(26, 54, 93)

        p_lim = self.doc.add_paragraph()
        p_lim.add_run("Identified Technical & Extraction Limitations:\n").font.bold = True
        if not self.model.data_limitations:
            p_lim.add_run("• No data extraction anomalies or missing comparative figures detected.")
        else:
            for lim in self.model.data_limitations:
                p_lim.add_run(f"• {lim}\n")

        p_disc = self.doc.add_paragraph()
        p_disc.paragraph_format.space_before = Pt(12)
        r_d = p_disc.add_run(DISCLAIMER_TEXT)
        r_d.font.size = Pt(8.5)
        r_d.font.italic = True
        r_d.font.color.rgb = RGBColor(113, 128, 150)
