<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Practice.BuildingBlocks/Practice.BuildingBlocks.csproj" />
    <ProjectReference Include="../Practice.Database/Practice.Database.csproj" />
    <ProjectReference Include="../Practice.Scheduling/Practice.Scheduling.csproj" />
  </ItemGroup>
</Project>
