// TAB 10 — Board Pack. A pack is a frozen snapshot, retrievable exactly as issued.
import React, { useState } from 'react'
import { useApp, useEndpoint } from '../lib/store'
import { api } from '../lib/api'
import { cls, d, inr, num, ts } from '../lib/format'
import {
  Card, Dot, Drawer, Empty, ErrorNote, Field, Icon, Loading, Modal,
  StatusPill, Table, TD, TH,
} from '../components/ui'
import { Stat, StatRow } from '../components/Figure'

export default function BoardPack() {
  const { canWrite, notify } = useApp()
  const { data, loading, error, reload } = useEndpoint('/api/board-packs')
  const [gen, setGen] = useState(false)
  const [viewing, setViewing] = useState(null)

  if (loading && !data) return <Loading label="Loading the pack library…" rows={3} />
  if (error) return <ErrorNote error={error} onRetry={reload} />
  if (!data) return null

  async function open(id) {
    setViewing({ loading: true })
    try { setViewing(await api.get(`/api/board-packs/${id}`)) }
    catch (e) { setViewing({ error: e.message }) }
  }

  return (
    <div className="space-y-5">
      <Card title="Generate a pack"
            sub="Pick the as-on date, the sections and the scenarios. What comes out is frozen."
            right={canWrite && (
              <button className="btn-primary btn-sm" onClick={() => setGen(true)}>
                <Icon name="plus" size={13} /> New pack
              </button>)}>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2.5">
          {data.sections.map((s) => (
            <div key={s} className="rounded-lg border border-line bg-canvas px-3 py-2.5">
              <p className="text-[13px] text-ink-soft">{s}</p>
            </div>
          ))}
        </div>
        <p className="basis mt-4">
          Each section is pulled from a fixed snapshot at generation time, so re-opening a
          pack months later shows exactly what was issued — not what the numbers look like now.
        </p>
      </Card>

      <Card title="Snapshot library"
            sub="Every pack ever generated, retrievable exactly as issued"
            pad={false}>
        {data.packs.length === 0 ? (
          <Empty>No packs generated yet.</Empty>
        ) : (
          <Table className="px-4 pb-1">
            <thead><tr>
              <TH left>Title</TH><TH>As on</TH><TH left>Generated by</TH><TH>Generated</TH>
              <TH>Runway stated</TH><TH>Cash-out stated</TH><TH left>Confidence</TH><TH left />
            </tr></thead>
            <tbody>
              {data.packs.map((p) => (
                <tr key={p.id} className="tr-hover cursor-pointer group" onClick={() => open(p.id)}>
                  <TD left className="!text-ink font-medium">{p.title}</TD>
                  <TD>{d(p.as_on)}</TD>
                  <TD left>{p.generated_by}</TD>
                  <TD>{ts(p.generated_on)}</TD>
                  <TD className="font-semibold !text-ink">
                    {p.runway_stated ? `${num(p.runway_stated)} mo` : '—'}
                  </TD>
                  <TD>{d(p.cashout_stated)}</TD>
                  <TD left>
                    <StatusPill status={p.confidence === 'High' ? 'Green'
                                      : p.confidence === 'Medium' ? 'Amber' : 'Grey'}
                                label={p.confidence} />
                  </TD>
                  <TD left>
                    <Icon name="chevronRight" size={14}
                          className="text-ink-faint opacity-0 group-hover:opacity-100" />
                  </TD>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Card>

      <GenerateModal open={gen} sections={data.sections} scenarios={data.scenarios}
                     onClose={() => setGen(false)}
                     onDone={() => { setGen(false); reload(); notify('Board pack generated.') }} />

      <PackViewer pack={viewing} onClose={() => setViewing(null)} />
    </div>
  )
}

function GenerateModal({ open, sections, scenarios, onClose, onDone }) {
  const [title, setTitle] = useState('')
  const [picked, setPicked] = useState(sections)
  const [scen, setScen] = useState([])
  const [commentary, setCommentary] = useState({})
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState(null)
  if (!open) return null

  const toggle = (s) => setPicked((p) => p.includes(s) ? p.filter((x) => x !== s) : [...p, s])

  async function save() {
    setBusy(true); setErr(null)
    try {
      await api.post('/api/board-packs', {
        title: title || undefined, sections: picked, scenario_ids: scen, commentary,
      })
      onDone()
    } catch (e) { setErr(e.message); setBusy(false) }
  }

  return (
    <Modal open onClose={onClose} width="max-w-2xl"
           title="Generate a board pack"
           sub="Everything is computed once, now, and stored. It will not change later."
           footer={<>
             <button className="btn-ghost" onClick={onClose}>Cancel</button>
             <button className="btn-primary" disabled={busy || !picked.length} onClick={save}>
               {busy ? 'Generating…' : 'Generate'}
             </button>
           </>}>
      <div className="space-y-5">
        <Field label="Title" hint="Left blank, it is named for the entity and the as-on date.">
          <input className="input" value={title} onChange={(e) => setTitle(e.target.value)}
                 placeholder="September board pack" />
        </Field>

        <div>
          <span className="label block mb-2">Sections</span>
          <div className="grid sm:grid-cols-2 gap-2">
            {sections.map((s) => (
              <button key={s} type="button" onClick={() => toggle(s)}
                      className={cls('rounded-lg border px-3 py-2 text-left text-[13px] transition-colors flex items-center gap-2',
                        picked.includes(s) ? 'border-navy-500 bg-navy-50 text-navy-700 font-medium'
                                           : 'border-line text-ink-soft hover:border-navy-300')}>
                <span className={cls('w-4 h-4 rounded border grid place-items-center shrink-0',
                  picked.includes(s) ? 'bg-navy-700 border-navy-700' : 'border-line-strong')}>
                  {picked.includes(s) && <Icon name="check" size={11} className="text-white" strokeWidth={3} />}
                </span>
                {s}
              </button>
            ))}
          </div>
        </div>

        <div>
          <span className="label block mb-2">Scenarios to include</span>
          <div className="grid sm:grid-cols-2 gap-2">
            {scenarios.map((s) => (
              <button key={s.id} type="button"
                      onClick={() => setScen((p) => p.includes(s.id) ? p.filter((x) => x !== s.id)
                                                                    : p.length < 4 ? [...p, s.id] : p)}
                      className={cls('rounded-lg border px-3 py-2 text-left text-[13px] transition-colors',
                        scen.includes(s.id) ? 'border-navy-500 bg-navy-50 text-navy-700 font-medium'
                                            : 'border-line text-ink-soft hover:border-navy-300')}>
                {s.name}
              </button>
            ))}
          </div>
          <p className="basis mt-1.5">Up to four.</p>
        </div>

        <Field label="Your commentary on the cash position"
               hint="Saved with the pack, in your words, alongside the figures.">
          <textarea rows={4} className="input"
                    value={commentary['Cash & Runway Summary'] || ''}
                    onChange={(e) => setCommentary({ 'Cash & Runway Summary': e.target.value })} />
        </Field>
      </div>
      {err && <p className="text-[13px] text-red mt-3">{err}</p>}
    </Modal>
  )
}

function PackViewer({ pack, onClose }) {
  if (!pack) return null
  if (pack.loading) {
    return <Drawer open onClose={onClose} title="Opening the pack…"><Loading /></Drawer>
  }
  if (pack.error) {
    return <Drawer open onClose={onClose} title="Could not open the pack">
      <ErrorNote error={pack.error} /></Drawer>
  }

  const snap = pack.snapshot || {}
  const cr = snap.cash_runway
  const col = snap.collections
  const risks = snap.risks

  return (
    <Drawer open onClose={onClose} width="max-w-3xl"
            title={pack.title}
            sub={`As on ${d(pack.as_on)} · generated by ${pack.generated_by} on ${ts(pack.generated_on)}`}>
      <div className="rounded-lg border border-grey-line bg-grey-bg px-4 py-3 mb-5">
        <p className="text-[13px] text-grey">{pack.note}</p>
      </div>

      {pack.commentary?.['Cash & Runway Summary'] && (
        <div className="card card-pad mb-5">
          <span className="label block mb-2">Commentary</span>
          <p className="text-[14px] leading-relaxed text-ink-soft whitespace-pre-line">
            {pack.commentary['Cash & Runway Summary']}
          </p>
        </div>
      )}

      <div className="card card-pad mb-5">
        <span className="label block mb-3">What this pack stated</span>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <Stat label="Runway" value={pack.runway_stated ? `${num(pack.runway_stated)} mo` : '—'} />
          <Stat label="Cash-out date" value={d(pack.cashout_stated)} />
          <Stat label="Cash available" value={inr(cr?.position?.available)} />
          <Stat label="Confidence" value={pack.confidence} />
        </div>
      </div>

      <div className="space-y-4">
        {cr && (
          <PackSection title="Cash & Runway Summary">
            <div className="grid sm:grid-cols-2 gap-3">
              {cr.runway.rows.map((r) => (
                <div key={r.key} className="rounded-lg border border-line px-3 py-2.5">
                  <p className="text-[13px] font-medium text-ink">{r.scenario}</p>
                  <p className="text-2xs text-ink-muted mt-0.5">
                    {num(r.months)} months · cash-out {d(r.cashout_date)} · burn {inr(r.monthly_burn)}
                  </p>
                </div>
              ))}
            </div>
            {cr.movement?.narrative && (
              <p className="text-[13px] text-ink-soft mt-3">{cr.movement.narrative}</p>
            )}
          </PackSection>
        )}

        {snap.burn && (
          <PackSection title="Burn Analysis">
            <Table>
              <thead><tr><TH left>Category</TH><TH>This month</TH><TH>3-mth avg</TH><TH>% of total</TH></tr></thead>
              <tbody>
                {snap.burn.by_category.rows.slice(0, 6).map((r) => (
                  <tr key={r.category}>
                    <TD left>{r.category}</TD><TD>{inr(r.this_month)}</TD>
                    <TD>{inr(r.avg_3m)}</TD><TD>{r.pct_of_total}%</TD>
                  </tr>
                ))}
              </tbody>
            </Table>
          </PackSection>
        )}

        {col && (
          <PackSection title="Collections & Concentration">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-3">
              <Stat label="Receivable" value={inr(col.summary.total_receivable)} size="sm" />
              <Stat label="Overdue" value={inr(col.summary.overdue)} size="sm" />
              <Stat label="DSO" value={col.summary.dso ? `${Math.round(col.summary.dso)}d` : '—'} size="sm" />
              <Stat label="Weighted 30d" value={inr(col.summary.weighted_next_30d)} size="sm" />
            </div>
            {col.concentration?.impact && (
              <p className="text-[13px] text-ink-soft">{col.concentration.impact.sentence}</p>
            )}
          </PackSection>
        )}

        {snap.forecast?.lowest_point && (
          <PackSection title="13-Week Forecast">
            <p className="text-[13px] text-ink-soft">{snap.forecast.lowest_point.sentence}</p>
            <p className="text-2xs text-ink-muted mt-1.5">{snap.forecast.accuracy?.sentence}</p>
          </PackSection>
        )}

        {snap.scenarios?.rows?.length > 0 && (
          <PackSection title="Scenario Summary">
            <Table>
              <thead><tr>
                <TH left>Scenario</TH><TH>Cash-out</TH><TH>Runway</TH><TH>Lowest cash</TH><TH left>Verdict</TH>
              </tr></thead>
              <tbody>
                {snap.scenarios.rows.map((r) => (
                  <tr key={r.scenario_id}>
                    <TD left>{r.name}</TD><TD>{d(r.cashout_date)}</TD>
                    <TD>{num(r.runway_months)} mo</TD><TD>{inr(r.lowest_cash)}</TD>
                    <TD left>{r.verdict}</TD>
                  </tr>
                ))}
              </tbody>
            </Table>
            {snap.sensitivity?.sentence && (
              <p className="text-2xs text-ink-muted mt-3">{snap.sensitivity.sentence}</p>
            )}
          </PackSection>
        )}

        {snap.funding && (
          <PackSection title="Funding Position">
            <div className="grid grid-cols-3 gap-4 mb-3">
              <Stat label="Sanctioned" value={inr(snap.funding.facilities.totals.sanctioned)} size="sm" />
              <Stat label="Drawn" value={inr(snap.funding.facilities.totals.drawn)} size="sm" />
              <Stat label="Available to draw" value={inr(snap.funding.facilities.totals.available_to_draw)} size="sm" />
            </div>
            {snap.funding.next_raise?.exists && (
              <p className="text-[13px] text-ink-soft">{snap.funding.next_raise.sentence}</p>
            )}
          </PackSection>
        )}

        {risks && (
          <PackSection title="Key Risks">
            <p className="text-[13px] leading-relaxed text-ink-soft">
              {risks.reading?.text || risks.reading?.reason}
            </p>
            <ul className="mt-3 space-y-1.5">
              {(risks.what_needs_me?.rows || []).slice(0, 5).map((r) => (
                <li key={r.priority} className="flex items-start gap-2 text-[13px] text-ink-soft">
                  <Dot status={r.severity} className="mt-1.5" />{r.item}
                </li>
              ))}
            </ul>
          </PackSection>
        )}
      </div>
    </Drawer>
  )
}

function PackSection({ title, children }) {
  return (
    <section className="card card-pad">
      <h4 className="text-[14px] font-semibold text-ink mb-3">{title}</h4>
      {children}
    </section>
  )
}
