"""Phase 9 — DOCX output and the audit pack. §11.1, §11.2, §18.9.

Golden-file tests in the sense that matters here: the file is opened again
and its structure inspected, rather than its bytes compared — a .docx is a
zip whose byte order is not stable.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

import pytest
from docx import Document as DocxDocument
from docx.shared import Inches, Pt
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.clauses.model import ClauseSet
from app.models.engagement import Engagement
from app.models.issuance import DocumentInstance
from app.render import docx as docx_renderer
from app.render.base import Document, Heading, Para, Signature, Table
from app.services.export import (
    ExportError,
    build_audit_pack,
    generate_document,
    reprint,
    to_pdf,
)


@pytest.fixture
def engagement(db: Session, client_id: int) -> Engagement:
    found = db.scalar(
        select(Engagement).where(Engagement.client_id == client_id, Engagement.fy_code == "2025-26")
    )
    assert found is not None
    return found


@pytest.fixture
def sample(tmp_path: Path) -> Path:
    document = Document(id="d", title="Independent Auditor's Report", template_version="v1")
    document.add(Heading(text="Independent Auditor's Report", level=1))
    document.add(Para(text="Body paragraph.", number="(a)"))
    document.add(Table(headers=("A", "B"), rows=(("1", "2"),)))
    document.add(Signature(lines=("For Example & Co.", "FRN 000000W")))
    target = tmp_path / "out.docx"
    return docx_renderer.render(
        document, target, client_name="ABC Private Limited", fy_code="FY 2025-26"
    )


class TestDocxFormatting:
    def test_it_opens_in_word(self, sample: Path) -> None:
        assert sample.exists()
        assert DocxDocument(str(sample)) is not None

    def test_body_font_is_times_new_roman_10pt(self, sample: Path) -> None:
        # §18.9 — the DOCX must match the preview.
        style = DocxDocument(str(sample)).styles["Normal"]
        assert style.font.name == "Times New Roman"
        assert style.font.size == Pt(10)

    def test_margins_are_one_inch_with_a_gutter(self, sample: Path) -> None:
        # The prototype used 0.75 inch and no gutter.
        section = DocxDocument(str(sample)).sections[0]
        assert section.top_margin == Inches(1)
        assert section.right_margin == Inches(1)
        assert section.bottom_margin == Inches(1)
        assert section.left_margin == Inches(1.25)

    def test_a_footer_exists_on_every_section(self, sample: Path) -> None:
        for section in DocxDocument(str(sample)).sections:
            text = section.footer.paragraphs[0].text
            assert "ABC Private Limited" in text
            assert "FY 2025-26" in text

    def test_page_numbers_are_fields_not_typed_numbers(self, sample: Path) -> None:
        """A typed "Page 1 of 3" is wrong the moment Word repaginates."""
        with zipfile.ZipFile(sample) as archive:
            footers = [n for n in archive.namelist() if "footer" in n]
            assert footers
            xml = archive.read(footers[0]).decode("utf-8")
        assert "PAGE" in xml
        assert "NUMPAGES" in xml
        assert "fldChar" in xml

    def test_a_header_carries_the_document_title(self, sample: Path) -> None:
        section = DocxDocument(str(sample)).sections[0]
        assert "Independent Auditor" in section.header.paragraphs[0].text

    def test_the_document_does_not_name_the_software(self, sample: Path) -> None:
        """Partner, 19 August 2026: no tool stamp on the output.

        This test asserted the OPPOSITE until today - that every export carried
        "Generated by AuditCraft . Template <version> . <timestamp>" at its foot.
        A statutory report goes out over the firm's name and the signing
        partner's membership number; the software that typeset it is not a party
        to it.

        The version and timestamp are not lost: they are on the
        `document_instance` row, which is what a reprint is rebuilt from.
        """
        text = chr(10).join(p.text for p in DocxDocument(str(sample)).paragraphs)
        assert "AuditCraft" not in text
        assert "Generated by" not in text

    def test_signature_blocks_keep_with_next(self, sample: Path) -> None:
        # §11.1 — a signature must not split across a page break.
        paragraphs = [p for p in DocxDocument(str(sample)).paragraphs if "FRN" in p.text]
        assert paragraphs
        assert paragraphs[0].paragraph_format.keep_with_next is True

    def test_a_clause_number_gets_a_hanging_indent(self, sample: Path) -> None:
        paragraphs = [p for p in DocxDocument(str(sample)).paragraphs if p.text.startswith("(a)")]
        assert paragraphs
        assert paragraphs[0].paragraph_format.first_line_indent < 0

    def test_the_table_is_a_real_table(self, sample: Path) -> None:
        tables = DocxDocument(str(sample)).tables
        assert len(tables) == 1
        assert tables[0].rows[0].cells[0].text == "A"


class TestRendererHoldsNoProse:
    def test_no_document_text_in_the_docx_adapter(self) -> None:
        """§19 — the two renderers must not hold independent copies.

        Enforced generally by test_no_hardcoded_text.py; asserted here too
        because this is the file most likely to acquire boilerplate.
        """
        source = Path("app/render/docx.py").read_text(encoding="utf-8")
        assert "According to the information" not in source
        assert "in our opinion" not in source.lower()


class TestGeneration:
    def test_a_document_instance_is_recorded(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        result = generate_document(
            db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False
        )
        assert result.path.exists()
        assert len(result.content_sha256) == 64

        instance = db.scalar(
            select(DocumentInstance).where(
                DocumentInstance.engagement_id == engagement.engagement_id
            )
        )
        assert instance is not None
        assert instance.version_no == 1
        assert instance.payload_json

    def test_versions_increment(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        first = generate_document(
            db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False
        )
        second = generate_document(
            db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False
        )
        assert (first.version_no, second.version_no) == (1, 2)

    def test_filenames_derive_from_ids_not_free_text(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        # §11.4 — never from user-entered text.
        result = generate_document(
            db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False
        )
        assert result.path.name == f"{engagement.engagement_id}_caro_2020_v1.docx"

    def test_a_blocked_document_will_not_export(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        from app.services.engagement import set_response

        set_response(db, engagement.engagement_id, "caro.viii", "", updated_by="t")
        with pytest.raises(ExportError, match="block export"):
            generate_document(
                db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False
            )


class TestAuditPack:
    def test_it_zips_the_available_documents(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        pack = build_audit_pack(db, engagement, clause_set, generated_by="partner")
        assert pack.exists()
        with zipfile.ZipFile(pack) as archive:
            names = archive.namelist()
        assert "manifest.json" in names
        assert any(name.endswith("_Auditors_Report.docx") for name in names)
        assert any(name.endswith("_CARO_2020_Annexure_A.docx") for name in names)

    def test_documents_are_numbered_in_order(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        pack = build_audit_pack(db, engagement, clause_set, generated_by="p")
        with zipfile.ZipFile(pack) as archive:
            docs = sorted(n for n in archive.namelist() if n.endswith(".docx"))
        assert docs[0].startswith("03_")  # auditor's report
        assert docs[1].startswith("04_")  # CARO annexure

    def test_the_manifest_records_hashes_and_versions(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        pack = build_audit_pack(db, engagement, clause_set, generated_by="p")
        with zipfile.ZipFile(pack) as archive:
            manifest = json.loads(archive.read("manifest.json"))
        assert manifest["financial_year"] == "2025-26"
        assert manifest["template_version"] == "0.1.0-phase1"
        for entry in manifest["documents"]:
            assert len(entry["sha256"]) == 64
            assert entry["version"] >= 1

    def test_missing_documents_are_named_not_silently_dropped(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet
    ) -> None:
        """Four of the six documents are not authored yet.

        A pack that quietly lacks the MRL and the Directors' Report would be
        worse than one that says so.
        """
        pack = build_audit_pack(db, engagement, clause_set, generated_by="p")
        with zipfile.ZipFile(pack) as archive:
            manifest = json.loads(archive.read("manifest.json"))
        missing = manifest["documents_not_in_repository"]
        assert set(missing) == {
            "engagement_letter",
            "mrl",
            "ifc_report",
            "directors_report",
        }


class TestPdfDegradesGracefully:
    def test_absent_soffice_returns_none_rather_than_raising(self, sample: Path) -> None:
        # §1, §11.2 — "if soffice is absent, log and offer DOCX only. Never
        # crash." LibreOffice is not installed in this environment, so this
        # is the real path, not a simulated one.
        assert to_pdf(sample) is None


class TestReprintFromSnapshot:
    def test_a_reprint_matches_its_recorded_hash(
        self, db: Session, engagement: Engagement, clause_set: ClauseSet, tmp_path: Path
    ) -> None:
        generate_document(db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False)
        instance = db.scalar(
            select(DocumentInstance).where(
                DocumentInstance.engagement_id == engagement.engagement_id
            )
        )
        assert instance is not None

        _, matches = reprint(db, instance.doc_id, clause_set, tmp_path / "again.docx")
        assert matches is True

    def test_a_reprint_ignores_later_master_data_changes(
        self,
        db: Session,
        engagement: Engagement,
        clause_set: ClauseSet,
        client_id: int,
        tmp_path: Path,
    ) -> None:
        from datetime import date

        from app.services.client import ChangeScope, change_profile

        generate_document(db, engagement, "caro_2020", clause_set, generated_by="p", with_pdf=False)
        instance = db.scalar(
            select(DocumentInstance).where(
                DocumentInstance.engagement_id == engagement.engagement_id
            )
        )
        assert instance is not None

        change_profile(
            db,
            client_id,
            {"company_name": "Renamed Limited"},
            change_date=date(2026, 9, 1),
            changed_by="m",
            reason="Renamed",
            scope=ChangeScope.MASTER_ONLY,
        )
        db.flush()

        # §18.6 — the reprint still reproduces what was signed.
        _, matches = reprint(db, instance.doc_id, clause_set, tmp_path / "again.docx")
        assert matches is True
