# Generated by Django 5.2.17 on 2026-08-21 06:01

import assets.models
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "useful_life_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Schedule II useful life in years. Leave blank for 'per Ind AS 38' intangibles.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "default_method",
                    models.CharField(
                        choices=[
                            ("SLM", "Straight Line Method"),
                            ("WDV", "Written Down Value"),
                        ],
                        default="SLM",
                        max_length=8,
                    ),
                ),
                ("is_intangible", models.BooleanField(default=False)),
                (
                    "residual_value_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Residual value as % of original cost. Schedule II caps this at 5% unless justified.",
                        max_digits=5,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Asset classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "is_related_party",
                    models.BooleanField(
                        default=False,
                        help_text="Section 188 related-party flag — auto-flags asset transactions with this vendor for disclosure.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSET_CREATE", "Create asset"),
                            ("ASSET_EDIT", "Edit asset"),
                            ("CAPITALISATION", "Capitalise CWIP"),
                            ("DISPOSAL", "Disposal / write-off / sale"),
                            ("TRANSFER", "Transfer"),
                            ("REVALUATION", "Revaluation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payload_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of what's being approved.",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_comment", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="CapexRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("justification", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "delegated_authority_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Approval threshold in force at request time, for audit reference.",
                        max_digits=16,
                    ),
                ),
                ("requires_board_approval", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending board/committee approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "board_resolution_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_requisitions",
                        to="locations.entity",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capex_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CWIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="CWIP reference number.", max_length=64, unique=True
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="PO number"
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="GRN number"
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "duty_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "installation_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "borrowing_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — accumulating cost"),
                            ("READY", "Ready for capitalisation"),
                            ("CAPITALISED", "Capitalised"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cwip_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cwip_items",
                        to="locations.entity",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cwip_items",
                        to="assets.capexrequisition",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cwip_items",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "CWIP item",
                "verbose_name_plural": "CWIP items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        default=assets.models.generate_asset_id,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "make_model",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Make / model / spec"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Serial / chassis number",
                    ),
                ),
                ("acquisition_date", models.DateField(help_text="Date of purchase.")),
                (
                    "put_to_use_date",
                    models.DateField(help_text="Depreciation starts here."),
                ),
                ("po_reference", models.CharField(blank=True, max_length=64)),
                ("grn_reference", models.CharField(blank=True, max_length=64)),
                ("invoice_reference", models.CharField(blank=True, max_length=64)),
                (
                    "capitalised_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purchase price plus freight, duty, installation, borrowing cost.",
                        max_digits=16,
                    ),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("SLM", "Straight Line Method"),
                            ("WDV", "Written Down Value"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "useful_life_years",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "residual_value_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "tax_block_code",
                    models.CharField(
                        blank=True,
                        help_text="Income Tax Act block-of-assets code.",
                        max_length=16,
                    ),
                ),
                (
                    "tax_wdv_rate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=128)),
                (
                    "ownership_status",
                    models.CharField(
                        choices=[
                            ("OWNED", "Owned"),
                            ("LEASED", "Leased"),
                            ("ROU", "Right-of-use (Ind AS 116)"),
                        ],
                        default="OWNED",
                        max_length=8,
                    ),
                ),
                (
                    "title_deed_in_company_name",
                    models.BooleanField(
                        blank=True,
                        help_text="CARO 3(i)(c) — for immovable property, is the title deed held in the company's own name?",
                        null=True,
                    ),
                ),
                ("title_deed_reference", models.CharField(blank=True, max_length=128)),
                (
                    "encumbrance_details",
                    models.TextField(
                        blank=True,
                        help_text="Charges, liens, or hypothecation against the asset.",
                    ),
                ),
                ("is_immovable_property", models.BooleanField(default=False)),
                (
                    "last_scan_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "last_scan_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("is_revalued", models.BooleanField(default=False)),
                ("last_revaluation_date", models.DateField(blank=True, null=True)),
                (
                    "accumulated_revaluation_surplus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "impairment_loss_to_date",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("insurer_name", models.CharField(blank=True, max_length=128)),
                (
                    "insurance_sum_insured",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("insurance_renewal_date", models.DateField(blank=True, null=True)),
                ("amc_provider", models.CharField(blank=True, max_length=128)),
                ("amc_renewal_date", models.DateField(blank=True, null=True)),
                ("last_verified_date", models.DateField(blank=True, null=True)),
                (
                    "last_verification_condition",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("IN_USE", "In use"),
                            ("IDLE", "Idle"),
                            ("UNDER_MAINTENANCE", "Under maintenance"),
                            ("HELD_FOR_DISPOSAL", "Held for disposal"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="IN_USE",
                        max_length=24,
                    ),
                ),
                (
                    "tag_status",
                    models.CharField(
                        choices=[
                            ("UNTAGGED", "Untagged"),
                            ("TAGGED", "Tagged"),
                            ("REISSUED", "Reissued"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="UNTAGGED",
                        max_length=16,
                    ),
                ),
                (
                    "qr_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tagged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_in_custody",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="locations.entity",
                    ),
                ),
                (
                    "last_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_last_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="locations.location",
                    ),
                ),
                (
                    "parent_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for a component/sub-assembly with a distinct useful life.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="assets.asset",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_tagged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetclass",
                    ),
                ),
                (
                    "cwip_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capitalised_assets",
                        to="assets.cwip",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_supplied",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        choices=[
                            ("SCHEDULE_II", "Schedule II (books)"),
                            ("INCOME_TAX", "Income Tax Act (tax block/WDV)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("is_posted", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_runs",
                        to="locations.entity",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
                "unique_together": {("entity", "book", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PO", "Purchase order"),
                            ("GRN", "Goods receipt note"),
                            ("INVOICE", "Invoice"),
                            ("TITLE_DEED", "Title deed"),
                            ("VALUATION_REPORT", "Valuation report"),
                            ("INSURANCE_POLICY", "Insurance policy"),
                            ("BOARD_RESOLUTION", "Board/committee resolution"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAssetClass",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "useful_life_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Schedule II useful life in years. Leave blank for 'per Ind AS 38' intangibles.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "default_method",
                    models.CharField(
                        choices=[
                            ("SLM", "Straight Line Method"),
                            ("WDV", "Written Down Value"),
                        ],
                        default="SLM",
                        max_length=8,
                    ),
                ),
                ("is_intangible", models.BooleanField(default=False)),
                (
                    "residual_value_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Residual value as % of original cost. Schedule II caps this at 5% unless justified.",
                        max_digits=5,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset class",
                "verbose_name_plural": "historical Asset classes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCapexRequisition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("justification", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "delegated_authority_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Approval threshold in force at request time, for audit reference.",
                        max_digits=16,
                    ),
                ),
                ("requires_board_approval", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending board/committee approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "board_resolution_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical capex requisition",
                "verbose_name_plural": "historical capex requisitions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalImpairmentCheck",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("check_date", models.DateField()),
                ("indicators_present", models.BooleanField(default=False)),
                ("indicator_notes", models.TextField(blank=True)),
                (
                    "recoverable_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "carrying_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "impairment_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical impairment check",
                "verbose_name_plural": "historical impairment checks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRevaluationRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "valuer_name",
                    models.CharField(
                        help_text="Registered Valuer per Section 247.", max_length=255
                    ),
                ),
                ("valuer_registration_number", models.CharField(max_length=64)),
                ("valuation_date", models.DateField()),
                ("methodology", models.CharField(max_length=255)),
                ("fair_value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "carrying_value_before",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "surplus_or_deficit",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("movement_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                ("exceeds_10pct_threshold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical revaluation record",
                "verbose_name_plural": "historical revaluation records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVendor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "is_related_party",
                    models.BooleanField(
                        default=False,
                        help_text="Section 188 related-party flag — auto-flags asset transactions with this vendor for disclosure.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vendor",
                "verbose_name_plural": "historical vendors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ImpairmentCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_date", models.DateField()),
                ("indicators_present", models.BooleanField(default=False)),
                ("indicator_notes", models.TextField(blank=True)),
                (
                    "recoverable_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "carrying_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "impairment_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impairment_checks",
                        to="assets.asset",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impairment_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="RevaluationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valuer_name",
                    models.CharField(
                        help_text="Registered Valuer per Section 247.", max_length=255
                    ),
                ),
                ("valuer_registration_number", models.CharField(max_length=64)),
                ("valuation_date", models.DateField()),
                ("methodology", models.CharField(max_length=255)),
                ("fair_value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "carrying_value_before",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "surplus_or_deficit",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("movement_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                ("exceeds_10pct_threshold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revaluations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revaluations",
                        to="assets.asset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revaluations_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-valuation_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCWIP",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, help_text="CWIP reference number.", max_length=64
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="PO number"
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="GRN number"
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "freight_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "duty_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "installation_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "borrowing_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — accumulating cost"),
                            ("READY", "Ready for capitalisation"),
                            ("CAPITALISED", "Capitalised"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.capexrequisition",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical CWIP item",
                "verbose_name_plural": "historical CWIP items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        db_index=True,
                        default=assets.models.generate_asset_id,
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "make_model",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Make / model / spec"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Serial / chassis number",
                    ),
                ),
                ("acquisition_date", models.DateField(help_text="Date of purchase.")),
                (
                    "put_to_use_date",
                    models.DateField(help_text="Depreciation starts here."),
                ),
                ("po_reference", models.CharField(blank=True, max_length=64)),
                ("grn_reference", models.CharField(blank=True, max_length=64)),
                ("invoice_reference", models.CharField(blank=True, max_length=64)),
                (
                    "capitalised_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Purchase price plus freight, duty, installation, borrowing cost.",
                        max_digits=16,
                    ),
                ),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("SLM", "Straight Line Method"),
                            ("WDV", "Written Down Value"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "useful_life_years",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "residual_value_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "tax_block_code",
                    models.CharField(
                        blank=True,
                        help_text="Income Tax Act block-of-assets code.",
                        max_length=16,
                    ),
                ),
                (
                    "tax_wdv_rate_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=128)),
                (
                    "ownership_status",
                    models.CharField(
                        choices=[
                            ("OWNED", "Owned"),
                            ("LEASED", "Leased"),
                            ("ROU", "Right-of-use (Ind AS 116)"),
                        ],
                        default="OWNED",
                        max_length=8,
                    ),
                ),
                (
                    "title_deed_in_company_name",
                    models.BooleanField(
                        blank=True,
                        help_text="CARO 3(i)(c) — for immovable property, is the title deed held in the company's own name?",
                        null=True,
                    ),
                ),
                ("title_deed_reference", models.CharField(blank=True, max_length=128)),
                (
                    "encumbrance_details",
                    models.TextField(
                        blank=True,
                        help_text="Charges, liens, or hypothecation against the asset.",
                    ),
                ),
                ("is_immovable_property", models.BooleanField(default=False)),
                (
                    "last_scan_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "last_scan_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("is_revalued", models.BooleanField(default=False)),
                ("last_revaluation_date", models.DateField(blank=True, null=True)),
                (
                    "accumulated_revaluation_surplus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "impairment_loss_to_date",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("insurer_name", models.CharField(blank=True, max_length=128)),
                (
                    "insurance_sum_insured",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("insurance_renewal_date", models.DateField(blank=True, null=True)),
                ("amc_provider", models.CharField(blank=True, max_length=128)),
                ("amc_renewal_date", models.DateField(blank=True, null=True)),
                ("last_verified_date", models.DateField(blank=True, null=True)),
                (
                    "last_verification_condition",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("IN_USE", "In use"),
                            ("IDLE", "Idle"),
                            ("UNDER_MAINTENANCE", "Under maintenance"),
                            ("HELD_FOR_DISPOSAL", "Held for disposal"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="IN_USE",
                        max_length=24,
                    ),
                ),
                (
                    "tag_status",
                    models.CharField(
                        choices=[
                            ("UNTAGGED", "Untagged"),
                            ("TAGGED", "Tagged"),
                            ("REISSUED", "Reissued"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="UNTAGGED",
                        max_length=16,
                    ),
                ),
                (
                    "qr_uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("tagged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_class",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.assetclass",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cwip_source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.cwip",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "parent_asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Set for a component/sub-assembly with a distinct useful life.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset",
                "verbose_name_plural": "historical assets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BookDepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_wdv", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "depreciable_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("closing_wdv", models.DecimalField(decimal_places=2, max_digits=16)),
                ("days_in_period", models.PositiveIntegerField()),
                (
                    "days_used",
                    models.PositiveIntegerField(
                        help_text="Proration for mid-year additions/deletions."
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("SLM", "Straight Line Method"),
                            ("WDV", "Written Down Value"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_depreciation_entries",
                        to="assets.asset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book_entries",
                        to="assets.depreciationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__asset_id"],
                "unique_together": {("run", "asset")},
            },
        ),
        migrations.CreateModel(
            name="TaxDepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_block_code", models.CharField(blank=True, max_length=16)),
                ("opening_wdv", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "additions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("rate_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "is_half_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Asset held < 180 days in the year — half the normal WDV rate applies.",
                    ),
                ),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("closing_wdv", models.DecimalField(decimal_places=2, max_digits=16)),
                ("period_end", models.DateField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_depreciation_entries",
                        to="assets.asset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_entries",
                        to="assets.depreciationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__asset_id"],
                "unique_together": {("run", "asset")},
            },
        ),
    ]
