# Generated by Django 5.2.17 on 2026-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrevaluationrecord",
            name="movement_pct",
            field=models.DecimalField(
                decimal_places=2,
                help_text="(fair value − carrying value) / carrying value × 100. Widened beyond a typical percentage range because a near-zero carrying value (e.g. an asset depreciated almost to nil) can produce a legitimately huge swing.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="revaluationrecord",
            name="movement_pct",
            field=models.DecimalField(
                decimal_places=2,
                help_text="(fair value − carrying value) / carrying value × 100. Widened beyond a typical percentage range because a near-zero carrying value (e.g. an asset depreciated almost to nil) can produce a legitimately huge swing.",
                max_digits=10,
            ),
        ),
    ]
