[theme]
primaryColor = "#742E46"
backgroundColor = "#F4F5F8"
secondaryBackgroundColor = "#E9EDF4"
textColor = "#1C2D45"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true
address = "127.0.0.1"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
