"""Investment thesis generation — synthesizes an InvestmentThesis from
already-computed metrics/trends/interpretations.

The banned-phrase lint here is the concrete implementation of the
spec's explicit prohibition on phrases like "guaranteed return",
"certain multibagger", "risk-free", "AI predicts the stock will rise".
Every piece of free-text the LLM produces is scanned and sanitized
before an InvestmentThesis is ever constructed — this happens
unconditionally, it is not optional or skippable by a caller.
"""

from __future__ import annotations

import logging

from app.core.enums import Recommendation
from app.core.exceptions import LLMProviderError
from app.core.models import InvestmentThesis, MetricResult, ThesisInvalidationTrigger, TrendResult
from app.ai.json_utils import parse_json_response
from app.ai.llm_client import LLMClient
from app.ai.prompts import build_thesis_prompt

logger = logging.getLogger(__name__)

_NEUTRALIZED_MARKER = "[LANGUAGE ADJUSTED: overconfident claim removed]"

# Case-insensitive substring match. Deliberately broad phrasing per
# entry so close paraphrases are still caught (e.g. "guaranteed" alone
# catches "guaranteed return", "guaranteed profit", "guaranteed upside").
BANNED_PHRASES: list[str] = [
    "guaranteed return", "guaranteed profit", "guaranteed upside", "guaranteed to",
    "certain multibagger", "sure shot", "sure-shot",
    "risk-free", "risk free", "zero risk", "no risk",
    "ai predicts", "ai forecasts the stock", "we predict the stock will",
    "cannot lose", "can't lose", "will definitely",
    "100% safe", "assured returns",
]


def lint_text(text: str) -> list[str]:
    """Return every banned phrase found in `text` (case-insensitive)."""
    lowered = text.lower()
    return [phrase for phrase in BANNED_PHRASES if phrase in lowered]


def sanitize_text(text: str) -> tuple[str, bool]:
    """Replace any banned-phrase occurrence with a neutral marker.
    Returns (sanitized_text, was_modified)."""
    sanitized = text
    modified = False
    lowered = text.lower()
    for phrase in BANNED_PHRASES:
        idx = lowered.find(phrase)
        while idx != -1:
            sanitized = sanitized[:idx] + _NEUTRALIZED_MARKER + sanitized[idx + len(phrase):]
            lowered = sanitized.lower()
            modified = True
            idx = lowered.find(phrase)
    return sanitized, modified


def generate_investment_thesis(
    *,
    company_name: str,
    metrics: list[MetricResult],
    trends: list[TrendResult],
    interpretation_claims: list[tuple[str, str]],
    llm_client: LLMClient,
) -> InvestmentThesis:
    """Synthesize an InvestmentThesis. Every free-text field is linted
    and sanitized for banned phrases before construction — this cannot
    be bypassed by a caller.

    Raises:
        LLMProviderError: if the LLM call fails, returns unparseable
            JSON, or an unrecognized recommendation value.
    """
    system, user = build_thesis_prompt(
        company_name=company_name, metrics=metrics, trends=trends,
        interpretation_claims=interpretation_claims, banned_phrases=BANNED_PHRASES,
    )
    response = llm_client.complete(system=system, user=user, max_tokens=2000)
    data = parse_json_response(response.text)

    try:
        recommendation = Recommendation(str(data["recommendation"]).lower())
    except (KeyError, ValueError) as exc:
        raise LLMProviderError(
            f"LLM response missing or invalid 'recommendation' field: {exc}"
        ) from exc

    core_thesis, core_modified = sanitize_text(str(data.get("core_thesis", "")))
    counterarguments = []
    for text in data.get("counterarguments", []):
        clean, modified = sanitize_text(str(text))
        counterarguments.append(clean)
        core_modified = core_modified or modified

    catalysts = []
    for text in data.get("catalysts", []):
        clean, modified = sanitize_text(str(text))
        catalysts.append(clean)
        core_modified = core_modified or modified

    invalidation_triggers = [
        ThesisInvalidationTrigger(
            condition=str(t.get("condition", "")),
            threshold_basis=str(t.get("threshold_basis", "explicit_assumption")),
            metric_reference=t.get("metric_reference"),
        )
        for t in data.get("invalidation_triggers", [])
    ]
    data_limitations = [str(x) for x in data.get("data_limitations", [])]

    if len(invalidation_triggers) < 2:
        data_limitations.append(
            "Fewer than 2 thesis invalidation triggers were generated by the model; "
            "treat this thesis with extra caution and consider requesting a re-run."
        )
        logger.warning(
            "Thesis for %s has only %d invalidation trigger(s); spec requires "
            "measurable invalidation conditions — flagged in data_limitations.",
            company_name, len(invalidation_triggers),
        )

    if core_modified:
        logger.warning(
            "Banned/overconfident phrase(s) detected and neutralized in generated "
            "thesis for %s.", company_name,
        )
        data_limitations.append(
            "One or more overconfident phrases were detected and removed from the "
            "model's output; review this thesis carefully before relying on it."
        )

    return InvestmentThesis(
        recommendation=recommendation, core_thesis=core_thesis,
        supporting_evidence_ids=[cid for cid, _ in interpretation_claims],
        counterarguments=counterarguments, catalysts=catalysts,
        invalidation_triggers=invalidation_triggers, data_limitations=data_limitations,
        requires_human_review=True,  # never settable to False by this function
    )
