"""Phase 4 schema

Revision ID: 75659b2a4b05
Revises: 0001_baseline
Create Date: 2026-08-15 16:11:07.302974

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "75659b2a4b05"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("entity", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("field", sa.String(length=120), nullable=False),
        sa.Column("before_json", sa.Text(), nullable=False),
        sa.Column("after_json", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column(
            "at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "field_catalog",
        sa.Column("field_key", sa.String(length=120), nullable=False),
        sa.Column("document", sa.String(length=60), nullable=False),
        sa.Column("clause_id", sa.String(length=120), nullable=False),
        sa.Column("clause_ref", sa.String(length=200), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("datatype", sa.String(length=30), nullable=False),
        sa.Column("options_json", sa.Text(), nullable=False),
        sa.Column(
            "carry_forward",
            sa.Enum("ALWAYS", "PROMPT", "NEVER", name="carryforward", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("field_key"),
    )
    op.create_table(
        "firm",
        sa.Column("firm_id", sa.Integer(), nullable=False),
        sa.Column("firm_name", sa.String(length=200), nullable=False),
        sa.Column("frn", sa.String(length=10), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("logo_path", sa.String(length=400), nullable=False),
        sa.Column("default_place", sa.String(length=100), nullable=False),
        sa.Column("doc_font", sa.String(length=60), nullable=False),
        sa.Column("doc_font_size", sa.Integer(), nullable=False),
        sa.Column("doc_margin_mm", sa.String(length=40), nullable=False),
        sa.Column("doc_header", sa.Text(), nullable=False),
        sa.Column("doc_footer", sa.Text(), nullable=False),
        sa.Column("doc_page_numbering", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("firm_id"),
        sa.UniqueConstraint("frn"),
    )
    op.create_table(
        "client",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("firm_id", sa.Integer(), nullable=False),
        sa.Column("client_code", sa.String(length=30), nullable=False),
        sa.Column("cin", sa.String(length=21), nullable=False),
        sa.Column("pan", sa.String(length=10), nullable=False),
        sa.Column("gstin", sa.String(length=15), nullable=False),
        sa.Column("date_of_incorp", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firm.firm_id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint("cin"),
        sa.UniqueConstraint("client_code"),
    )
    op.create_table(
        "partner",
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("firm_id", sa.Integer(), nullable=False),
        sa.Column("partner_name", sa.String(length=200), nullable=False),
        sa.Column("membership_no", sa.String(length=10), nullable=False),
        sa.Column("is_signing", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firm.firm_id"],
        ),
        sa.PrimaryKeyConstraint("partner_id"),
        sa.UniqueConstraint("membership_no"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("firm_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("STAFF", "MANAGER", "PARTNER", "ADMIN", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firm.firm_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "banker",
        sa.Column("banker_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.String(length=200), nullable=False),
        sa.Column("branch", sa.String(length=200), nullable=False),
        sa.Column("facility_type", sa.String(length=120), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.PrimaryKeyConstraint("banker_id"),
    )
    op.create_table(
        "client_profile",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("company_name", sa.String(length=250), nullable=False),
        sa.Column("registered_addr", sa.Text(), nullable=False),
        sa.Column("corporate_addr", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("nature_of_business", sa.Text(), nullable=False),
        sa.Column(
            "company_type",
            sa.Enum(
                "PVT",
                "PUB_UNLISTED",
                "PUB_LISTED",
                "OPC",
                "SMALL",
                "SEC8",
                "NIDHI",
                name="companytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "framework",
            sa.Enum("IND_AS", "IGAAP", name="framework", native_enum=False),
            nullable=False,
        ),
        sa.Column("amounts_in", sa.String(length=20), nullable=False),
        sa.Column("paid_up_capital", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("borrowings", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("net_worth", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("caro", sa.Boolean(), nullable=False),
        sa.Column("caro_override", sa.Boolean(), nullable=False),
        sa.Column("ifc", sa.Boolean(), nullable=False),
        sa.Column("ifc_override", sa.Boolean(), nullable=False),
        sa.Column("s197", sa.Boolean(), nullable=False),
        sa.Column("s197_override", sa.Boolean(), nullable=False),
        sa.Column("csr", sa.Boolean(), nullable=False),
        sa.Column("csr_override", sa.Boolean(), nullable=False),
        sa.Column("cost_records", sa.Boolean(), nullable=False),
        sa.Column("cost_records_override", sa.Boolean(), nullable=False),
        sa.Column("internal_audit", sa.Boolean(), nullable=False),
        sa.Column("internal_audit_override", sa.Boolean(), nullable=False),
        sa.Column("kam", sa.Boolean(), nullable=False),
        sa.Column("kam_override", sa.Boolean(), nullable=False),
        sa.Column("changed_by", sa.String(length=200), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    with op.batch_alter_table("client_profile", schema=None) as batch_op:
        batch_op.create_index(
            "ux_client_profile_current",
            ["client_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current = true"),
        )

    op.create_table(
        "director",
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("din", sa.String(length=8), nullable=False),
        sa.Column(
            "designation",
            sa.Enum(
                "MANAGING",
                "WHOLE_TIME",
                "EXECUTIVE",
                "NON_EXECUTIVE",
                "INDEPENDENT",
                "NOMINEE",
                "ADDITIONAL",
                name="designation",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("appointment_date", sa.Date(), nullable=False),
        sa.Column("cessation_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.PrimaryKeyConstraint("director_id"),
    )
    op.create_table(
        "kmp",
        sa.Column("kmp_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CFO", "CEO", "CS", "MANAGER", name="kmprole", native_enum=False),
            nullable=False,
        ),
        sa.Column("pan", sa.String(length=10), nullable=False),
        sa.Column("appointment_date", sa.Date(), nullable=False),
        sa.Column("cessation_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.PrimaryKeyConstraint("kmp_id"),
    )
    op.create_table(
        "engagement",
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("fy_code", sa.String(length=9), nullable=False),
        sa.Column("fy_start", sa.Date(), nullable=False),
        sa.Column("fy_end", sa.Date(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.Column(
            "opinion_type",
            sa.Enum(
                "CLEAN", "QUALIFIED", "ADVERSE", "DISCLAIMER", name="opiniontype", native_enum=False
            ),
            nullable=True,
        ),
        sa.Column(
            "going_concern",
            sa.Enum("NONE", "EOM", "MATERIAL_UNCERTAINTY", name="goingconcern", native_enum=False),
            nullable=False,
        ),
        sa.Column("appointment_date", sa.Date(), nullable=True),
        sa.Column("commencement_date", sa.Date(), nullable=True),
        sa.Column("expected_completion", sa.Date(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("place", sa.String(length=120), nullable=False),
        sa.Column("audit_fee", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("oope", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "DATA_COLLECTION",
                "PREPARED",
                "MANAGER_REVIEW",
                "PARTNER_REVIEW",
                "APPROVED",
                "FINALISED",
                "ARCHIVED",
                name="engagementstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("locked_by", sa.String(length=200), nullable=False),
        sa.Column("rolled_from", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partner.partner_id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["client_profile.profile_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rolled_from"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("engagement_id"),
        sa.UniqueConstraint("client_id", "fy_code", name="ux_engagement_client_fy"),
    )
    op.create_table(
        "board_meeting",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("directors_present", sa.Integer(), nullable=False),
        sa.Column("total_directors", sa.Integer(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "director_change",
        sa.Column("change_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["director.director_id"],
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("change_id"),
    )
    op.create_table(
        "document_instance",
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(length=60), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("template_version", sa.String(length=40), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("udin", sa.String(length=18), nullable=True),
        sa.Column("generated_by", sa.String(length=200), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("docx_path", sa.String(length=500), nullable=False),
        sa.Column("pdf_path", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "IN_REVIEW",
                "APPROVED",
                "FINAL",
                "SUPERSEDED",
                "WITHDRAWN",
                name="documentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("revision_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("doc_id"),
        sa.UniqueConstraint(
            "engagement_id", "doc_type", "version_no", name="ux_document_instance_version"
        ),
    )
    op.create_table(
        "engagement_response",
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("field_key", sa.String(length=120), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("value_num", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=200), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("wp_reference", sa.String(length=120), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["field_key"],
            ["field_catalog.field_key"],
        ),
        sa.PrimaryKeyConstraint("engagement_id", "field_key"),
    )
    op.create_table(
        "ifc_deficiency",
        sa.Column("deficiency_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("process", sa.String(length=200), nullable=False),
        sa.Column("control", sa.Text(), nullable=False),
        sa.Column("nature", sa.Text(), nullable=False),
        sa.Column("risk", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("management_response", sa.Text(), nullable=False),
        sa.Column("auditor_assessment", sa.Text(), nullable=False),
        sa.Column("remediation_status", sa.String(length=40), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("deficiency_id"),
    )
    op.create_table(
        "litigation",
        sa.Column("litigation_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("forum", sa.String(length=250), nullable=False),
        sa.Column("case_number", sa.String(length=120), nullable=False),
        sa.Column("nature", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("period", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("mgmt_assessment", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("litigation_id"),
    )
    op.create_table(
        "review_comment",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("field_key", sa.String(length=120), nullable=True),
        sa.Column("document", sa.String(length=60), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("raised_by", sa.String(length=200), nullable=False),
        sa.Column(
            "raised_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESPONDED", "RESOLVED", name="commentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("resolved_by", sa.String(length=200), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["review_comment.comment_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "statutory_due",
        sa.Column("statutory_due_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("statute", sa.String(length=200), nullable=False),
        sa.Column("nature", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("period", sa.String(length=60), nullable=False),
        sa.Column("forum", sa.String(length=250), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("statutory_due_id"),
    )
    op.create_table(
        "udin_register",
        sa.Column("udin", sa.String(length=18), nullable=False),
        sa.Column("doc_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("generated_on", sa.Date(), nullable=False),
        sa.Column("revoked_on", sa.Date(), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_id"],
            ["document_instance.doc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partner.partner_id"],
        ),
        sa.PrimaryKeyConstraint("udin"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("udin_register")
    op.drop_table("statutory_due")
    op.drop_table("review_comment")
    op.drop_table("litigation")
    op.drop_table("ifc_deficiency")
    op.drop_table("engagement_response")
    op.drop_table("document_instance")
    op.drop_table("director_change")
    op.drop_table("board_meeting")
    op.drop_table("engagement")
    op.drop_table("kmp")
    op.drop_table("director")
    with op.batch_alter_table("client_profile", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_client_profile_current",
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current = true"),
        )

    op.drop_table("client_profile")
    op.drop_table("banker")
    op.drop_table("user")
    op.drop_table("partner")
    op.drop_table("client")
    op.drop_table("firm")
    op.drop_table("field_catalog")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
