"""Child tables for the Phase 2 repeating blocks

Ten clauses authored in Phase 2 declare a `repeating_block` and nothing
stored the rows: `CHILD_MODELS` had four entries and the YAML named
fourteen. The workspace raised `KeyError: 'key_audit_matter'` for any
document containing one, and the tests missed it because the fixture
repository has no repeating blocks and the render harness passed child rows
in directly.

Purely additive — ten new tables, nothing altered, so this is safe on a
populated database. `tests/test_repeating_blocks.py` now fails if a declared
entity has no model or a model is missing a column the YAML names.

Revision ID: 5508cf94f5ff
Revises: b3f27c04a1de
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5508cf94f5ff"
down_revision: str | None = "b3f27c04a1de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bdr_director_change",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("din", sa.String(length=30), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=False),
        sa.Column("change", sa.String(length=40), nullable=False),
        sa.Column("change_date", sa.Date(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "deposit_particulars",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("particulars", sa.String(length=250), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "employee_remuneration",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=False),
        sa.Column("remuneration", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("qualification", sa.Text(), nullable=False),
        sa.Column("date_of_employment", sa.Date(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "financial_summary",
        sa.Column("summary_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("particulars", sa.String(length=250), nullable=False),
        sa.Column("current_year", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("previous_year", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("summary_id"),
    )
    op.create_table(
        "forex_particulars",
        sa.Column("forex_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("particulars", sa.String(length=250), nullable=False),
        sa.Column("current_year", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("previous_year", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("forex_id"),
    )
    op.create_table(
        "key_audit_matter",
        sa.Column("matter_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("matter", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("matter_id"),
    )
    op.create_table(
        "loan_186",
        sa.Column("loan_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("party", sa.String(length=250), nullable=False),
        sa.Column("nature", sa.String(length=60), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("loan_id"),
    )
    op.create_table(
        "related_party_contract",
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("party", sa.String(length=250), nullable=False),
        sa.Column("relationship", sa.String(length=120), nullable=False),
        sa.Column("contract_nature", sa.Text(), nullable=False),
        sa.Column("duration", sa.String(length=120), nullable=False),
        sa.Column("salient_terms", sa.Text(), nullable=False),
        sa.Column("approval_date", sa.Date(), nullable=True),
        sa.Column("advance_paid", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    op.create_table(
        "subsidiary_change",
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("relationship", sa.String(length=60), nullable=False),
        sa.Column("change", sa.String(length=40), nullable=False),
        sa.Column("change_date", sa.Date(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "uncorrected_misstatement",
        sa.Column("misstatement_id", sa.Integer(), nullable=False),
        sa.Column("engagement_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("financial_statement_line", sa.String(length=250), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("effect", sa.String(length=250), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USER",
                "CARRIED_FORWARD",
                "DEFAULT",
                "IMPORTED",
                name="responsesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.engagement_id"],
        ),
        sa.PrimaryKeyConstraint("misstatement_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uncorrected_misstatement")
    op.drop_table("subsidiary_change")
    op.drop_table("related_party_contract")
    op.drop_table("loan_186")
    op.drop_table("key_audit_matter")
    op.drop_table("forex_particulars")
    op.drop_table("financial_summary")
    op.drop_table("employee_remuneration")
    op.drop_table("deposit_particulars")
    op.drop_table("bdr_director_change")
    # ### end Alembic commands ###
