"""mgt9 annexure tables

Revision ID: 3c6e92a21133
Revises: 276ca8147352
Create Date: 2026-08-20 17:56:42.362140

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3c6e92a21133'
down_revision: str | None = '276ca8147352'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mgt9_business_activity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.Text(), nullable=False),
    sa.Column('nic_code', sa.String(length=20), nullable=False),
    sa.Column('turnover_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CARRIED_FORWARD', 'DEFAULT', 'IMPORTED', name='responsesource', native_enum=False), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.engagement_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('mgt9_director_holding',
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.Text(), nullable=False),
    sa.Column('shares_begin', sa.String(length=60), nullable=False),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('shares_end', sa.String(length=60), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CARRIED_FORWARD', 'DEFAULT', 'IMPORTED', name='responsesource', native_enum=False), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.engagement_id'], ),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_table('mgt9_indebtedness',
    sa.Column('indebtedness_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('particulars', sa.Text(), nullable=False),
    sa.Column('secured', sa.String(length=60), nullable=False),
    sa.Column('unsecured', sa.String(length=60), nullable=False),
    sa.Column('deposits', sa.String(length=60), nullable=False),
    sa.Column('total', sa.String(length=60), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CARRIED_FORWARD', 'DEFAULT', 'IMPORTED', name='responsesource', native_enum=False), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.engagement_id'], ),
    sa.PrimaryKeyConstraint('indebtedness_id')
    )
    op.create_table('mgt9_promoter_holding',
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('shareholder_name', sa.Text(), nullable=False),
    sa.Column('shares_begin', sa.Integer(), nullable=False),
    sa.Column('pct_begin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shares_end', sa.Integer(), nullable=False),
    sa.Column('pct_end', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CARRIED_FORWARD', 'DEFAULT', 'IMPORTED', name='responsesource', native_enum=False), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.engagement_id'], ),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_table('mgt9_shareholding',
    sa.Column('shareholding_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('shares_begin', sa.String(length=60), nullable=False),
    sa.Column('shares_end', sa.String(length=60), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CARRIED_FORWARD', 'DEFAULT', 'IMPORTED', name='responsesource', native_enum=False), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.engagement_id'], ),
    sa.PrimaryKeyConstraint('shareholding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mgt9_shareholding')
    op.drop_table('mgt9_promoter_holding')
    op.drop_table('mgt9_indebtedness')
    op.drop_table('mgt9_director_holding')
    op.drop_table('mgt9_business_activity')
    # ### end Alembic commands ###
