"""slim the client profile to fields something reads

Revision ID: 4511e994cbfe
Revises: 3c6e92a21133
Create Date: 2026-08-20 23:03:21.556462

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4511e994cbfe'
down_revision: str | None = '3c6e92a21133'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('gstin')

    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('nature_of_business')
        batch_op.drop_column('amounts_in')
        batch_op.drop_column('reserves')
        batch_op.drop_column('industry')
        batch_op.drop_column('turnover')
        batch_op.drop_column('email')
        batch_op.drop_column('is_holding_of_public')
        batch_op.drop_column('paid_up_capital')
        batch_op.drop_column('borrowings')
        batch_op.drop_column('deposits')
        batch_op.drop_column('net_profit')
        batch_op.drop_column('corporate_addr')
        batch_op.drop_column('is_subsidiary_of_public')
        batch_op.drop_column('net_worth')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_worth', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_subsidiary_of_public', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('corporate_addr', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('net_profit', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deposits', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('borrowings', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_up_capital', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_holding_of_public', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('turnover', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('reserves', sa.NUMERIC(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amounts_in', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('nature_of_business', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), nullable=False))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gstin', sa.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
