"""default signing partner on the client

Revision ID: b98485352bcf
Revises: 4511e994cbfe
Create Date: 2026-08-21 00:40:29.222662

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b98485352bcf'
down_revision: str | None = '4511e994cbfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_client_default_partner', 'partner', ['default_partner_id'], ['partner_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_default_partner', type_='foreignkey')
        batch_op.drop_column('default_partner_id')

    # ### end Alembic commands ###
