"use strict";

const token = document.querySelector('meta[name="session-token"]').content;
const state = { ledger: false, vendors: false, assumptions: false, results: false, route: "file", mapping: {}, mappingConfidence: {}, recordType: "purchase", vendorFilter: "all", vendorEditing: null, certificateReview: null, entity: "", fy: "" };
const titles = { home:["ANALYSIS WORKSPACE","Client analyses"], load:["STEP 2 OF 7","Load ledger"], vendors:["STEP 3 OF 7","Vendor coverage"], assumptions:["STEP 4 OF 7","Assumptions"], results:["STEP 5 OF 7","Results"], exclusions:["STEP 6 OF 7","Exclusion Register"], export:["STEP 7 OF 7","Export"] };
const requiredPurchase = ["invoice_number","invoice_date","vendor_name","amount"];
const requiredPayment = ["invoice_number","payment_date","amount"];
const fieldLabels = { invoice_number:"Invoice number",invoice_date:"Invoice date",payment_date:"Payment date",vendor_name:"Vendor name",vendor_pan_or_gstin:"Vendor PAN or GSTIN (combined)",vendor_pan:"Vendor PAN",vendor_gstin:"Vendor GSTIN",amount:"Invoice amount",udyam_no:"Udyam registration number",enterprise_class:"Enterprise type / MSME class",classification_year:"Udyam classification year",nic_code:"NIC code",major_activity:"Major activity",registration_status:"Registration status",udyam_verification_source:"Udyam verification source",grn_date:"GRN date",agreement_credit_days:"Agreement credit days",agreed_due_date:"Agreed payment due date",actual_payment_date:"Actual payment date",outstanding_amount:"Outstanding amount",ledger_category:"Ledger / expense category",vendor_contact:"Vendor contact",remarks:"Remarks" };
const optionalPurchase = new Set(Object.keys(fieldLabels).filter(field=>!["invoice_number","invoice_date","vendor_name","amount","payment_date"].includes(field)));

const el = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const indian = value => {
  const number = Number(value || 0); const sign = number < 0 ? "-" : "";
  const [whole, fraction] = Math.abs(number).toFixed(2).split(".");
  const tail = whole.slice(-3); let head = whole.slice(0,-3); const groups=[];
  while(head.length>2){groups.unshift(head.slice(-2));head=head.slice(0,-2)} if(head)groups.unshift(head);
  const joined = groups.length ? `${groups.join(",")},${tail}` : tail;
  return `${sign}Rs ${joined}${fraction === "00" ? "" : "."+fraction}`;
};

let pendingRequests=0;
function setBusy(active,title="Working…"){
  pendingRequests=Math.max(0,pendingRequests+(active?1:-1));
  const overlay=el("busy-overlay");
  if(active&&title)el("busy-title").textContent=title;
  overlay.hidden=pendingRequests===0;
}
async function api(path, options={}){
  const {busyTitle,...requestOptions}=options;
  const headers = new Headers(requestOptions.headers || {}); headers.set("X-Session-Token", token);
  if(requestOptions.body && !(requestOptions.body instanceof FormData)) headers.set("Content-Type","application/json");
  setBusy(true,busyTitle||"Working…");
  try{
    const response = await fetch(path,{...requestOptions,headers});
    if(!response.ok){let message=`Request failed (${response.status})`;try{const data=await response.json();message=typeof data.detail==="string"?data.detail:(data.detail?.message||message);if(data.detail?.rows)showRowErrors(data.detail.rows)}catch(_){message=await response.text()||message}throw new Error(message)}
    const type=response.headers.get("content-type")||""; return type.includes("application/json")?await response.json():response;
  }finally{setBusy(false)}
}
function notify(message,error=false){const box=el("notice");box.textContent=message;box.classList.toggle("error",error);box.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>box.hidden=true,3500)}
async function nativeInvoke(name,args=[],title="Working locally…"){
  if(!window.pywebview?.api?.[name])throw new Error("This action is available in the installed desktop window.");
  setBusy(true,title);
  try{return await window.pywebview.api[name](...args)}finally{setBusy(false)}
}
function unlock(){
  document.querySelector('[data-screen="vendors"]').classList.toggle("locked",!state.ledger);
  document.querySelector('[data-screen="assumptions"]').classList.toggle("locked",!state.vendors);
  ["results","exclusions","export"].forEach(name=>document.querySelector(`[data-screen="${name}"]`).classList.toggle("locked",!state.results));
}
async function go(screen){const nav=document.querySelector(`[data-screen="${screen}"]`);if(nav?.classList.contains("locked"))return;document.querySelectorAll(".screen").forEach(item=>item.classList.remove("active"));el(`screen-${screen}`).classList.add("active");document.querySelectorAll(".nav-item").forEach(item=>item.classList.toggle("active",item.dataset.screen===screen));el("screen-step").textContent=titles[screen][0];el("screen-title").textContent=titles[screen][1];window.scrollTo(0,0);if(screen==="home")await loadHome();if(screen==="vendors")await loadVendors();if(screen==="assumptions")await loadAssumptions();if(screen==="results")await loadResults();if(screen==="exclusions")await loadExclusions();if(screen==="export")await loadExports()}

document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>go(button.dataset.screen)));
document.querySelectorAll("[data-go]").forEach(button=>button.addEventListener("click",()=>go(button.dataset.go)));
el("new-analysis").addEventListener("click",()=>{el("analysis-modal").hidden=false;el("analysis-entity").focus()});
document.querySelectorAll("[data-close-analysis]").forEach(item=>item.addEventListener("click",()=>el("analysis-modal").hidden=true));
el("start-analysis").addEventListener("click",async()=>{const entity=el("analysis-entity").value.trim();const pan=el("analysis-pan").value.trim();const fy=el("analysis-fy").value;try{const data=await api("/api/analysis/start",{method:"POST",body:JSON.stringify({entity_name:entity,entity_pan:pan,fy})});Object.assign(state,{ledger:false,vendors:false,assumptions:false,results:false,entity:data.entity,fy:data.fy});setEntity();unlock();el("analysis-modal").hidden=true;go("load")}catch(error){notify(error.message,true)}});

async function loadHome(){const data=await api("/api/home");el("entity-list").innerHTML=data.entities.length?data.entities.map(item=>`<div class="entity-card"><strong>${esc(item.name)}</strong><span>FY ${esc(item.fy)} · ${esc(item.status)}</span></div>`).join(""):'<div class="empty-state">No client analysis has been loaded in this session.</div>';el("run-list").innerHTML=data.runs.length?data.runs.map(run=>`<tr><td><strong>${esc(run.entity)}</strong></td><td>${esc(run.fy)}</td><td class="money">${esc(run.disallowance_display)}</td><td class="number">${esc(run.run_date)}</td><td><code>${esc(run.run_hash)}</code></td></tr>`).join(""):'<tr><td colspan="5" class="empty-cell">No completed runs in this session.</td></tr>'}

document.querySelectorAll(".route-card").forEach(card=>card.addEventListener("click",()=>{document.querySelectorAll(".route-card").forEach(item=>item.classList.remove("selected"));card.classList.add("selected");state.route=card.dataset.route;el("manual-panel").hidden=state.route!=="manual";el("file-panel").hidden=state.route==="manual";el("mapping-panel").hidden=true}));
el("ledger-file").addEventListener("change",event=>{el("file-name").textContent=event.target.files[0]?.name||"Choose Excel, CSV or XML"});
el("inspect-file").addEventListener("click",async()=>{const file=el("ledger-file").files[0];if(!file){notify("Choose a ledger file first.",true);return}const form=new FormData();form.append("file",file);try{const data=await api(`/api/import/file?record_type=${encodeURIComponent(el("record-type").value)}`,{method:"POST",body:form});if(data.complete){showControl(data.control_totals,data.confirmations||[]);notify("Tally vouchers reconciled.")}else{state.recordType=data.record_type;renderMapping(data.columns,data.suggested_mapping,data.mapping_confidence||{})}}catch(error){showFailedControl(error.message);notify(error.message,true)}});
function renderMapping(columns,suggestions,confidence){const fields=state.recordType==="payment"?["invoice_number","payment_date","amount"]:["invoice_number","invoice_date","vendor_name","vendor_pan","vendor_gstin","vendor_pan_or_gstin","amount","udyam_no","enterprise_class","classification_year","nic_code","major_activity","registration_status","udyam_verification_source","grn_date","agreement_credit_days","agreed_due_date","actual_payment_date","outstanding_amount","ledger_category","vendor_contact","remarks"];state.mapping={...suggestions};state.mappingConfidence={...confidence};el("mapping-grid").innerHTML=fields.map(field=>{const optional=state.recordType==="purchase"&&optionalPurchase.has(field);const confidenceLabel=confidence[field]?`<small class="confidence">${esc(confidence[field])}</small>`:"";return `<div class="mapping-field ${!optional&&!suggestions[field]?"unresolved":""}"><label>${fieldLabels[field]}${optional?'<small>OPTIONAL</small>':''}${confidenceLabel}</label><select data-map-field="${field}"><option value="">${optional?"Not available":"Choose column"}</option>${columns.map(column=>`<option value="${esc(column)}" ${suggestions[field]===column?"selected":""}>${esc(column)}</option>`).join("")}</select></div>`}).join("");el("mapping-panel").hidden=false;el("unmapped-columns").hidden=true;el("mapping-panel").scrollIntoView({behavior:"smooth",block:"start"});document.querySelectorAll("[data-map-field]").forEach(select=>select.addEventListener("change",()=>{state.mapping[select.dataset.mapField]=select.value;select.closest(".mapping-field").classList.toggle("unresolved",!optionalPurchase.has(select.dataset.mapField)&&!select.value)}))}
el("apply-mapping").addEventListener("click",async()=>{document.querySelectorAll("[data-map-field]").forEach(select=>state.mapping[select.dataset.mapField]=select.value);const required=state.recordType==="payment"?requiredPayment:requiredPurchase;const missing=required.filter(field=>!state.mapping[field]);if(missing.length){notify(`Map ${missing.map(f=>fieldLabels[f]).join(", ")}.`,true);return}const selected=Object.values(state.mapping).filter(Boolean);const duplicate=selected.find((column,index)=>selected.indexOf(column)!==index);if(duplicate){notify(`The source column "${duplicate}" is mapped more than once. Choose only one destination field.`,true);return}try{const data=await api("/api/import/map",{method:"POST",body:JSON.stringify({mapping:state.mapping,record_type:state.recordType})});showControl(data.control_totals,data.confirmations||[]);const box=el("unmapped-columns");box.hidden=!data.unmapped_columns?.length;box.innerHTML=data.unmapped_columns?.length?`<strong>Columns retained but not used:</strong> ${data.unmapped_columns.map(esc).join(", ")}. Nothing was silently discarded; add a mapping if any field is required.`:"";notify("Ledger reconciled successfully.")}catch(error){showFailedControl(error.message);notify(error.message,true)}});
el("analyse-manual").addEventListener("click",async()=>{const text=el("manual-data").value.trim();if(!text){notify("Paste ledger rows first.",true);return}const recordType=el("record-type").value;try{const data=await api("/api/import/manual",{method:"POST",body:JSON.stringify({text,record_type:recordType})});showControl(data.control_totals,data.confirmations||[]);notify(`${recordType==="payment"?"Payment":"Purchase"} rows reconciled.`)}catch(error){showFailedControl(error.message);notify(error.message,true)}});
el("load-demo").addEventListener("click",async()=>{try{const data=await api("/api/demo/load",{method:"POST"});state.entity=data.entity;state.fy=data.fy;setEntity();showControl(data.control_totals);notify("Demonstration ledger loaded and reconciled.")}catch(error){notify(error.message,true)}});
el("download-template").addEventListener("click",async()=>{if(window.pywebview?.api?.save_input_template){const result=await nativeInvoke("save_input_template",[],"Preparing the finished input template…");if(result.cancelled){notify("Template save cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Input template saved: ${result.file}`);return}downloadApi("/api/import/template")});
function setEntity(){if(state.entity){el("entity-chip").hidden=false;el("entity-name").textContent=state.entity;el("entity-fy").textContent=`FY ${state.fy}`}}
function showControl(totals,confirmations=[]){const safe=totals.can_continue??totals.ties;state.ledger=!!safe;unlock();const panel=el("control-panel");panel.hidden=false;panel.classList.toggle("failed",!safe);el("control-icon").textContent=safe?"✓":"×";el("control-status").textContent=!totals.ties?"Totals do not tie — import blocked":totals.scope_ok===false?`No invoices fall within FY ${totals.selected_fy||state.fy} — blocked`:"Totals and financial-year scope agree";const hash=totals.source_file_sha256?` · SHA-256 ${totals.source_file_sha256.slice(0,12)}…`:"";el("control-source").textContent=(totals.source||"Imported ledger")+hash;el("lines-read").textContent=Number(totals.lines_read||0).toLocaleString("en-IN");el("value-read").textContent=indian(totals.total_value_read);el("value-accounted").textContent=indian(totals.total_value_accounted_for);el("in-period-lines").textContent=totals.in_period_lines==null?"—":Number(totals.in_period_lines).toLocaleString("en-IN");el("in-period-value").textContent=totals.in_period_value==null?"—":indian(totals.in_period_value);el("out-period-value").textContent=totals.out_of_period_value==null?"—":`${Number(totals.out_of_period_lines||0).toLocaleString("en-IN")} line(s) · ${indian(totals.out_of_period_value)}`;el("continue-vendors").disabled=!safe;el("error-rows").hidden=true;const review=el("import-confirmations");review.hidden=!confirmations.length;review.innerHTML=confirmations.length?`<strong>${confirmations.length} imported value(s) require confirmation</strong><br>${confirmations.map(item=>`Row ${esc(item.row_number)}: ${esc(item.reason)}`).join("<br>")}`:"";panel.scrollIntoView({behavior:"smooth",block:"center"})}
function showFailedControl(message){state.ledger=false;unlock();showControl({ties:false,lines_read:0,total_value_read:0,total_value_accounted_for:0,source:message})}
function showRowErrors(rows){const box=el("error-rows");box.hidden=false;box.innerHTML=`<strong>Rows requiring correction</strong>${rows.map(row=>`<p>Row ${row.row_number}: ${row.reasons.map(esc).join("; ")}</p>`).join("")}`}
el("continue-vendors").addEventListener("click",()=>{if(state.ledger){state.vendors=true;unlock();go("vendors")}});

async function loadVendors(filter=state.vendorFilter){
  const data=await api(`/api/vendors?filter=${filter}`,{busyTitle:"Loading vendor master…"});
  state.vendorFilter=filter;
  el("assumed-alert").hidden=data.assumed_count===0;
  el("assumed-message").textContent=`${data.assumed_count} vendor(s) have no reliable evidence. Open Edit vendor, upload a certificate, or record a declaration before continuing.`;
  el("continue-assumptions").disabled=data.assumed_count>0;
  el("vendor-list").innerHTML=data.vendors.length?data.vendors.map(row=>`<tr class="${row.is_assumed?"assumed-row":""}"><td><input type="checkbox" class="vendor-check" value="${esc(row.vendor_id)}" aria-label="Select ${esc(row.name)}"></td><td><strong>${esc(row.name)}</strong><br><small>${esc(row.contact||"")}</small></td><td>${esc(row.pan_gstin)}</td><td><strong>${esc(row.udyam_no)}</strong><br><small>${esc(row.enterprise_class)}${row.relevant_classification_year?` · FY ${esc(row.relevant_classification_year)}`:""}</small></td><td><strong>${esc(row.nic_code)}</strong><br><small>${esc(row.activity)}</small></td><td class="number">${esc(row.credit_days)}</td><td><span class="status ${row.validation_status==="VERIFIED"?"green":row.validation_status==="REVIEW_REQUIRED"?"red":"amber"}">${esc(row.validation_status.replaceAll("_"," "))}</span></td><td><span class="status ${row.coverage==="Covered"?"green":"amber"}">${esc(row.coverage)}</span></td><td><span class="status ${row.is_assumed?"red":row.unconfirmed?"amber":"green"}">${esc(row.source_label)}</span><br><small>${row.evidence_count} file(s)</small></td><td><small>${esc(row.required_action)}</small></td><td><div class="table-actions"><button class="button primary small" data-edit-vendor="${esc(row.vendor_id)}">Edit vendor</button><label class="button secondary small">Upload certificate<input class="upload-input" type="file" data-cert="${esc(row.vendor_id)}" accept=".pdf,.png,.jpg,.jpeg"></label>${row.evidence_count?`<button class="button secondary small" data-view-evidence="${esc(row.vendor_id)}">View evidence</button>`:""}<button class="button secondary small" data-declaration="${esc(row.vendor_id)}">Declaration</button></div></td></tr>`).join(""):'<tr><td colspan="11" class="empty-cell">No vendors are available. Import a purchase ledger first.</td></tr>';
  document.querySelectorAll("[data-edit-vendor]").forEach(button=>button.addEventListener("click",()=>openVendorEditor(button.dataset.editVendor)));
  document.querySelectorAll("[data-cert]").forEach(input=>input.addEventListener("change",()=>uploadCertificate(input)));
  document.querySelectorAll("[data-view-evidence]").forEach(button=>button.addEventListener("click",()=>viewEvidence(button.dataset.viewEvidence)));
  document.querySelectorAll("[data-declaration]").forEach(button=>button.addEventListener("click",()=>saveDeclaration(button.dataset.declaration)));
}

async function openVendorEditor(vendorId){
  try{
    const row=await api(`/api/vendors/${encodeURIComponent(vendorId)}`,{busyTitle:"Opening vendor record…"});
    state.vendorEditing=vendorId;
    el("vendor-modal-title").textContent=`Update ${row.name}`;
    el("vendor-modal-subtitle").textContent=row.pan_gstin;
    el("vendor-udyam").value=row.udyam_no_raw||"";
    el("vendor-class").value=row.enterprise_class_raw||"";
    el("vendor-registration-date").value=row.registration_date||"";
    el("vendor-nic").value=row.nic_code_raw||"";
    el("vendor-activity").value=row.activity_raw||"";
    const certificateOption=el("vendor-source").querySelector('option[value="UDYAM_CERTIFICATE"]');
    certificateOption.disabled=!row.has_certificate_evidence;
    certificateOption.textContent=row.has_certificate_evidence?"Uploaded Udyam certificate — strong":"Upload certificate first — unavailable";
    el("vendor-source").value=row.source||"ASSUMED";
    el("vendor-confirmed-by").value=row.confirmed_by||"";
    el("vendor-current-reason").textContent=row.coverage_reason;
    el("vendor-modal").hidden=false;
    el("vendor-udyam").focus();
  }catch(error){notify(error.message,true)}
}

document.querySelectorAll("[data-close-vendor]").forEach(item=>item.addEventListener("click",()=>el("vendor-modal").hidden=true));
el("save-vendor").addEventListener("click",async()=>{
  if(!state.vendorEditing)return;
  const payload={udyam_no:el("vendor-udyam").value,enterprise_class:el("vendor-class").value,nic_code:el("vendor-nic").value,activity_label:el("vendor-activity").value,registration_date:el("vendor-registration-date").value,source:el("vendor-source").value,confirmed_by:el("vendor-confirmed-by").value};
  try{
    const updated=await api(`/api/vendors/${encodeURIComponent(state.vendorEditing)}`,{method:"PUT",body:JSON.stringify(payload),busyTitle:"Saving vendor classification…"});
    el("vendor-modal").hidden=true;
    notify(`Vendor saved. Current conclusion: ${updated.coverage}.`);
    await loadVendors();
  }catch(error){notify(error.message,true)}
});
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(item=>item.classList.remove("active"));button.classList.add("active");loadVendors(button.dataset.filter)}));
el("select-all").addEventListener("change",event=>document.querySelectorAll(".vendor-check").forEach(box=>box.checked=event.target.checked));
el("apply-bulk").addEventListener("click",async()=>{const ids=[...document.querySelectorAll(".vendor-check:checked")].map(box=>box.value);const source=el("bulk-source").value;if(!ids.length||!source){notify("Select vendors and a bulk evidence action.",true);return}await api("/api/vendors/bulk",{method:"POST",body:JSON.stringify({vendor_ids:ids,source})});notify(`${ids.length} vendor records updated.`);loadVendors()});
async function uploadCertificate(input){const file=input.files[0];if(!file)return;const form=new FormData();form.append("file",file);try{const data=await api(`/api/vendors/${encodeURIComponent(input.dataset.cert)}/certificate`,{method:"POST",body:form,busyTitle:"Reading Udyam certificate locally…"});openCertificateReview(input.dataset.cert,data)}catch(error){notify(error.message,true)}finally{input.value=""}}
function historyRow(item={}){return `<div class="history-row"><label><span>Classification year</span><input data-history-year value="${esc(item.classification_year||"")}" placeholder="2025-26"></label><label><span>Enterprise class</span><select data-history-class><option value="MICRO" ${item.enterprise_class==="MICRO"?"selected":""}>Micro</option><option value="SMALL" ${item.enterprise_class==="SMALL"?"selected":""}>Small</option><option value="MEDIUM" ${item.enterprise_class==="MEDIUM"?"selected":""}>Medium</option></select></label><label><span>Classification date</span><input type="date" data-history-date value="${esc(item.classification_date||"")}"></label><button class="button secondary small" data-remove-history>Remove</button></div>`}
function bindHistoryRows(){document.querySelectorAll("[data-remove-history]").forEach(button=>button.addEventListener("click",()=>button.closest(".history-row").remove()))}
function openCertificateReview(vendorId,data){state.certificateReview={vendorId,evidenceId:data.evidence_id};const x=data.extracted||{};el("certificate-review-status").textContent=data.message||"Review the locally extracted values.";el("cert-enterprise-name").value=x.enterprise_name||"";el("cert-pan").value=x.pan||"";el("cert-udyam").value=x.udyam_no||"";el("cert-class").value=x.project_year_class||x.enterprise_class||"";el("cert-nic").value=x.nic_code||"";el("cert-activity").value=x.major_activity||"";el("cert-organisation").value=x.organisation_type||"";el("cert-registration-date").value=x.registration_date||"";el("cert-incorporation-date").value=x.incorporation_date||"";el("cert-commencement-date").value=x.commencement_date||"";el("cert-address").value=x.registered_address||"";el("cert-confirmed-by").value="";const conflicts=Object.entries(data.conflicts||{});el("certificate-conflicts").hidden=!conflicts.length;el("certificate-conflicts").innerHTML=conflicts.length?`<strong>Differences require your decision</strong><ul class="conflict-list">${conflicts.map(([key,value])=>`<li>${esc(fieldLabels[key]||key)}: current "${esc(value.current)}"; certificate "${esc(value.extracted)}"</li>`).join("")}</ul>`:"";el("certificate-history").innerHTML=(x.classification_history||[]).map(historyRow).join("")||historyRow({classification_year:state.fy,enterprise_class:x.project_year_class||"MICRO"});bindHistoryRows();el("certificate-confirm-check").checked=false;el("save-certificate-review").disabled=true;el("certificate-modal").hidden=false}
el("add-history-row").addEventListener("click",()=>{el("certificate-history").insertAdjacentHTML("beforeend",historyRow());bindHistoryRows()});
document.querySelectorAll("[data-close-certificate]").forEach(item=>item.addEventListener("click",()=>el("certificate-modal").hidden=true));
el("certificate-confirm-check").addEventListener("change",event=>el("save-certificate-review").disabled=!event.target.checked);
el("save-certificate-review").addEventListener("click",async()=>{if(!state.certificateReview)return;const history=[...document.querySelectorAll(".history-row")].map(row=>({classification_year:row.querySelector("[data-history-year]").value,enterprise_class:row.querySelector("[data-history-class]").value,classification_date:row.querySelector("[data-history-date]").value}));const payload={evidence_id:state.certificateReview.evidenceId,udyam_no:el("cert-udyam").value,enterprise_name:el("cert-enterprise-name").value,enterprise_class:el("cert-class").value,major_activity:el("cert-activity").value,pan:el("cert-pan").value,organisation_type:el("cert-organisation").value,incorporation_date:el("cert-incorporation-date").value,commencement_date:el("cert-commencement-date").value,registration_date:el("cert-registration-date").value,registered_address:el("cert-address").value,nic_code:el("cert-nic").value,confirmed_by:el("cert-confirmed-by").value,classification_history:history};try{await api(`/api/vendors/${encodeURIComponent(state.certificateReview.vendorId)}/certificate/confirm`,{method:"POST",body:JSON.stringify(payload),busyTitle:"Saving confirmed certificate evidence…"});el("certificate-modal").hidden=true;notify("Certificate confirmed, linked and saved with its year-wise classification history.");await loadVendors()}catch(error){notify(error.message,true)}});
async function saveDeclaration(vendorId){if(window.pywebview?.api?.save_vendor_declaration){const result=await nativeInvoke("save_vendor_declaration",[vendorId],"Generating the vendor declaration…");if(result.cancelled){notify("Declaration save cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Declaration saved: ${result.file}`);return}downloadApi(`/api/vendors/${encodeURIComponent(vendorId)}/declaration`)}
async function viewEvidence(vendorId){try{const data=await api(`/api/vendors/${encodeURIComponent(vendorId)}/evidence`);if(!data.evidence.length){notify("No evidence file is stored for this vendor.",true);return}const evidence=data.evidence[data.evidence.length-1];if(window.pywebview?.api?.save_vendor_evidence){const result=await nativeInvoke("save_vendor_evidence",[evidence.evidence_id],"Preparing a verified copy of the evidence…");if(result.cancelled){notify("Evidence save cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Evidence copy saved: ${result.file}`)}else{notify(`Evidence is stored locally as ${evidence.filename}. Open the desktop application to save a copy.`)}}catch(error){notify(error.message,true)}}
el("continue-assumptions").addEventListener("click",()=>{state.vendors=true;unlock();go("assumptions")});

let selectedPolicy="INVOICE_DATE";
async function loadAssumptions(){const data=await api("/api/assumptions");el("policy-list").innerHTML=data.policies.map((policy,index)=>`<button class="policy-card ${index===0?"selected":""}" data-policy="${policy.id}" data-wording="${esc(policy.wording)}"><span class="radio-dot"></span><span><strong>${esc(policy.label)}</strong><small>${esc(policy.wording)}</small></span></button>`).join("");selectedPolicy=data.policies[0].id;el("policy-wording").textContent=data.policies[0].wording;document.querySelectorAll(".policy-card").forEach(card=>card.addEventListener("click",()=>{document.querySelectorAll(".policy-card").forEach(item=>item.classList.remove("selected"));card.classList.add("selected");selectedPolicy=card.dataset.policy;el("policy-wording").textContent=card.dataset.wording;el("plus-days-field").hidden=selectedPolicy!=="INVOICE_DATE_PLUS_N"}))}
function setRunAvailability(){el("run-analysis").disabled=!(el("policy-confirm").checked&&el("payments-confirm").checked)}
el("policy-confirm").addEventListener("change",setRunAvailability);
el("payments-confirm").addEventListener("change",setRunAvailability);
el("run-analysis").addEventListener("click",async()=>{try{const data=await api("/api/assumptions/confirm",{method:"POST",body:JSON.stringify({policy:selectedPolicy,plus_days:Number(el("plus-days").value||0),payments_confirmed:el("payments-confirm").checked})});state.assumptions=true;state.results=true;unlock();notify(`Analysis completed. Run hash ${data.run_hash}`);go("results")}catch(error){notify(error.message,true)}});

async function loadResults(){const data=await api("/api/results");el("result-law").textContent=`${data.act}, Section ${data.section}`;el("result-section").textContent=`Disallowance under Section ${data.section}`;el("result-disallowance").textContent=data.disallowance_display;el("result-interest").textContent=data.interest_display;el("result-excluded").textContent=data.excluded_display;const r=data.reconciliation;el("result-reconciliation").innerHTML=[["Original population",r.original_population_display],["Paid within year",r.paid_within_year_display],["31 March outstanding",r.outstanding_at_year_end_display],["Excluded population",r.excluded_population_display],["Population considered",r.population_considered_display]].map(item=>`<div class="reconcile-item"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join("");el("result-formulas").innerHTML=Object.entries(data.formula_notes).map(([key,value])=>`<div><strong>${esc(key.replaceAll("_"," ").toUpperCase())}</strong>${esc(value)}</div>`).join("");el("action-list").innerHTML=data.action_list.length?data.action_list.map(row=>`<tr><td>${esc(row.vendor)}</td><td class="number">${row.invoices}</td><td class="money">${indian(row.pay_now)}</td><td class="money">${indian(row.interest_exposure)}</td></tr>`).join(""):'<tr><td colspan="4" class="empty-cell">No covered invoice has an unpaid disallowable balance at 31 March. Check that payment data is complete before concluding no action is required.</td></tr>';el("interest-list").innerHTML=data.interest_only.length?data.interest_only.map(row=>`<tr><td>${esc(row.vendor)}</td><td class="number">${row.invoices}</td><td class="money">${indian(row.interest)}</td></tr>`).join(""):'<tr><td colspan="3" class="empty-cell">No invoice was identified as paid late within the selected year.</td></tr>'}
document.querySelectorAll("[data-drill]").forEach(card=>card.addEventListener("click",()=>openFindings(card.dataset.drill)));
async function openFindings(kind){const data=await api(`/api/findings?kind=${kind}`);el("modal-title").textContent=kind==="disallowance"?"Invoices creating the disallowance":kind==="interest"?"Invoices carrying s.16 interest":"Invoices protected by coverage gates";el("modal-content").innerHTML=data.findings.length?data.findings.map(row=>`<div class="finding-row"><div><strong>${esc(row.vendor)}</strong><small>${esc(row.invoice_id)} · Invoice ${esc(row.invoice_date)} · Due ${esc(row.due_date||"Not applicable")}</small><small>${esc(row.treatment)} — ${esc(row.reason)}</small></div><strong class="money">${esc(row.amount_display)}</strong><button class="button secondary small" data-detail="${esc(row.invoice_id)}">Show arithmetic</button></div>`).join(""):'<div class="empty-state">No invoices in this category.</div>';el("drill-modal").hidden=false;document.querySelectorAll("[data-detail]").forEach(button=>button.addEventListener("click",()=>openDetail(button.dataset.detail)))}
async function openDetail(invoice){const data=await api(`/api/findings/${encodeURIComponent(invoice)}`);el("modal-title").textContent=`${data.invoice_id} · ${data.vendor}`;const payments=data.payments.length?data.payments.map(p=>`${p.date} — ${p.amount_display}`).join("<br>"):"No allocated payments";const segments=data.interest_segments.length?`<div class="segments"><h3>Interest segments</h3><div class="table-wrap"><table><thead><tr><th>From</th><th>To</th><th>Basis</th><th>Bank rate</th><th>MSMED rate</th><th class="money">Opening</th><th class="money">Closing</th></tr></thead><tbody>${data.interest_segments.map(s=>`<tr><td class="number">${s.from}</td><td class="number">${s.to}</td><td>${esc(s.basis)}</td><td class="number">${s.bank_rate_pct}%</td><td class="number">${s.msmed_rate_pct}%</td><td class="money">${indian(s.opening)}</td><td class="money">${indian(s.closing)}</td></tr>`).join("")}</tbody></table></div></div>`:'<div class="empty-state">No interest segments for this invoice.</div>';el("modal-content").innerHTML=`<div class="detail-grid"><div class="detail-box"><span>Invoice amount</span><strong>${data.amount_display}</strong></div><div class="detail-box"><span>Invoice date</span><strong>${data.invoice_date}</strong></div><div class="detail-box"><span>Acceptance date</span><strong>${data.acceptance_date}</strong></div><div class="detail-box"><span>Credit period</span><strong>${data.credit_days} days${data.ceiling_applied?" (45-day ceiling applied)":""}</strong></div><div class="detail-box"><span>Due date</span><strong>${data.due_date||"Not applicable"}</strong></div><div class="detail-box"><span>Appointed day</span><strong>${data.appointed_day||"Not applicable"}</strong></div><div class="detail-box"><span>Disallowance</span><strong>${data.disallowance_display}</strong></div><div class="detail-box"><span>Interest</span><strong>${data.interest_display}</strong></div><div class="detail-box"><span>Payments received</span><strong>${payments}</strong></div></div><div class="detail-reason"><strong>Credit basis:</strong> ${esc(data.credit_basis)}<br><br><strong>Conclusion:</strong> ${esc(data.reason)}</div>${segments}`}
document.querySelectorAll("[data-close-modal]").forEach(item=>item.addEventListener("click",()=>el("drill-modal").hidden=true));

async function loadExclusions(){const data=await api("/api/exclusions");el("exclusion-total").textContent=data.grand_total_display;const r=data.reconciliation;el("exclusion-reconciliation").innerHTML=[["Original population",r.original_population_display],["Less: excluded population",r.excluded_population_display],["Population considered",r.considered_population_display],["Invoices reviewed",r.invoice_count],["Invoices excluded",r.excluded_invoice_count]].map(item=>`<div class="reconcile-item"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join("");el("exclusion-groups").innerHTML=data.groups.length?data.groups.map(group=>`<article class="gate-group"><div class="gate-header"><div><p class="eyebrow">${esc(group.gate)}</p><h3>${esc(group.label)}</h3><p>${esc(group.reason)}</p></div><div class="gate-total"><span>Wrongly addable by another tool</span><strong>${esc(group.total_display)}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Vendor</th><th>Invoices</th><th class="money">Turnover reviewed</th><th class="money">Correct exclusion</th><th>Evidence</th></tr></thead><tbody>${group.rows.map(row=>`<tr><td><strong>${esc(row.vendor)}</strong></td><td class="number">${row.invoices}</td><td class="money">${indian(row.turnover)}</td><td class="money"><strong>${esc(row.amount_display)}</strong></td><td><span class="status ${row.evidence_strength>=2?"green":"amber"}">${row.evidence_strength}/3</span></td></tr>`).join("")}</tbody></table></div></article>`).join(""):'<div class="empty-state">No vendor failed a coverage gate in this run. The original population therefore equals the population considered.</div>'}

async function loadExports(){const data=await api("/api/exports/preview");el("export-hash").textContent=data.run_hash;el("export-files").innerHTML=data.files.map(file=>`<article class="export-card"><span class="file-type">${file.name.endsWith(".pdf")?"PDF WORKING PAPER":"EXCEL WORKBOOK"}</span><h3>${esc(file.name)}</h3><p>${esc(file.description)}</p><small>${Number(file.rows).toLocaleString("en-IN")} supporting rows · included in Export All</small><button class="button secondary small" data-save-export="${esc(file.id)}">Save this file</button></article>`).join("");document.querySelectorAll("[data-save-export]").forEach(button=>button.addEventListener("click",()=>saveOneExport(button.dataset.saveExport)))}
async function saveOneExport(kind){if(window.pywebview?.api?.save_export){const result=await nativeInvoke("save_export",[kind],"Generating the selected finished report…");if(result.cancelled){notify("Export save cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Export saved: ${result.file}`);return}downloadApi(`/api/exports/${encodeURIComponent(kind)}`)}
el("export-all-folder").addEventListener("click",async()=>{if(!window.pywebview?.api?.choose_and_export){notify("Open this screen in the desktop window to choose an output folder.",true);return}try{const result=await nativeInvoke("choose_and_export",[],"Generating four finished reports…");if(result.cancelled){notify("Export cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Four files exported to ${result.folder}`)}catch(error){notify(String(error),true)}});
el("export-audit-pack").addEventListener("click",async()=>{if(!window.pywebview?.api?.choose_and_export_audit_pack){notify("Open this screen in the desktop window to choose an output folder.",true);return}try{const result=await nativeInvoke("choose_and_export_audit_pack",[],"Building the complete audit pack. Large ledgers can take a minute…");if(result.cancelled){notify("Audit Pack export cancelled.");return}if(result.error){notify(result.error,true);return}notify(`Complete Audit Pack created with ${result.files.length} files: ${result.folder}`)}catch(error){notify(String(error),true)}});
async function downloadApi(path){try{const response=await api(path);const blob=await response.blob();const disposition=response.headers.get("content-disposition")||"";const match=disposition.match(/filename="?([^";]+)"?/);const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=match?match[1]:"download";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000);notify("The browser download was started. Check the browser's Downloads list for the saved file.")}catch(error){notify(error.message,true)}}

async function loadHome(){const data=await api("/api/home");el("entity-list").innerHTML=data.entities.length?data.entities.map(item=>`<div class="entity-card"><strong>${esc(item.name)}</strong><span>FY ${esc(item.fy)} · ${esc(item.status)}</span></div>`).join(""):'<div class="empty-state">No client analysis has been saved yet.</div>';el("run-list").innerHTML=data.runs.length?data.runs.map(run=>`<tr><td><strong>${esc(run.entity)}</strong></td><td>${esc(run.fy)}</td><td class="money">${esc(run.disallowance_display)}</td><td class="number">${esc(run.run_date)}</td><td><code>${esc(run.run_hash)}</code></td></tr>`).join(""):'<tr><td colspan="5" class="empty-cell">No completed runs have been saved.</td></tr>';renderStorage(data.storage);renderReadiness(data.readiness);const profile=await api("/api/firm-profile");renderFirmProfile(profile);if(data.active_entity){state.entity=data.active_entity;state.fy=data.active_fy;setEntity()}const stage=data.active_stage||"home";state.ledger=["vendors","assumptions","results"].includes(stage);state.vendors=["assumptions","results"].includes(stage);state.assumptions=stage==="results";state.results=stage==="results";unlock()}
function renderReadiness(data){if(!data)return;const ready=data.status==="READY_FOR_REVIEW";const calculate=data.status==="READY_TO_CALCULATE";el("readiness-title").textContent=ready?"Ready for review":calculate?"Ready to calculate":`${data.issue_count} issue(s) require attention`;el("readiness-status").textContent=data.status.replaceAll("_"," ");el("readiness-status").className=`status ${ready?"green":"amber"}`;el("readiness-checks").innerHTML=data.checks.map(item=>`<div class="readiness-check"><span>${esc(item.label)}</span><strong>${typeof item.value==="boolean"?(item.value?"Complete":"Not complete"):esc(item.value)}</strong></div>`).join("");el("readiness-issues").hidden=!data.issues.length;el("readiness-issues").innerHTML=data.issues.length?`<strong>Resolve before review</strong><br>${data.issues.map(esc).join("<br>")}`:""}
function renderStorage(storage){const card=document.querySelector(".storage-card");card.classList.toggle("configured",storage.configured);el("storage-title").textContent=storage.configured?"Firm data is saved locally":"Choose where this firm's data will be kept";el("storage-path").textContent=storage.configured?`${storage.database_display} · integrity check: ${storage.integrity}`:"No database folder is configured. Work remains in this session until you choose one.";el("backup-database").disabled=!storage.configured;el("restore-database").disabled=!storage.configured}
function renderFirmProfile(profile){const ready=!!profile.firm_name;el("firm-profile-title").textContent=ready?profile.firm_name:"Set up the CA firm profile";el("firm-profile-summary").textContent=ready?`FRN ${profile.frn||"not provided"} · Prepared by ${profile.preparer||"not set"} · ${profile.document_status}`:"Firm name, FRN, preparer and reviewer will be printed on audit outputs."}
el("edit-firm-profile").addEventListener("click",async()=>{const p=await api("/api/firm-profile");el("firm-name").value=p.firm_name||"";el("firm-frn").value=p.frn||"";el("firm-address").value=p.address||"";el("firm-email").value=p.email||"";el("firm-phone").value=p.phone||"";el("firm-preparer").value=p.preparer||"";el("firm-reviewer").value=p.reviewer||"";el("firm-status").value=p.document_status||"DRAFT";el("firm-tax-rate").value=p.tax_rate_pct||"25.17";el("firm-tax-basis").value=p.tax_rate_basis||"";el("firm-modal").hidden=false});
document.querySelectorAll("[data-close-firm]").forEach(item=>item.addEventListener("click",()=>el("firm-modal").hidden=true));
el("save-firm-profile").addEventListener("click",async()=>{const payload={firm_name:el("firm-name").value,frn:el("firm-frn").value,address:el("firm-address").value,email:el("firm-email").value,phone:el("firm-phone").value,preparer:el("firm-preparer").value,reviewer:el("firm-reviewer").value,document_status:el("firm-status").value,tax_rate_pct:el("firm-tax-rate").value,tax_rate_basis:el("firm-tax-basis").value};try{const profile=await api("/api/firm-profile",{method:"POST",body:JSON.stringify(payload)});renderFirmProfile(profile);el("firm-modal").hidden=true;notify("Firm profile saved locally and will be used on future exports.")}catch(error){notify(error.message,true)}});
async function nativeStorage(action){if(!window.pywebview?.api?.[action]){notify("Open this in the desktop window to use a Windows folder dialog.",true);return}const result=await nativeInvoke(action,[],"Updating local storage…");if(result.cancelled){notify("No changes made.");return}if(result.error){notify(result.error,true);return}await loadHome();return result}
el("choose-data-folder").addEventListener("click",async()=>{const result=await nativeStorage("choose_data_folder");if(result)notify("Local database folder selected. Current and future work will be saved here.")});
el("backup-database").addEventListener("click",async()=>{const result=await nativeStorage("backup_database");if(result)notify(`Backup created: ${result.file}`)});
el("restore-database").addEventListener("click",async()=>{if(!window.confirm("Restore this backup? Current database contents will be replaced by the selected backup."))return;const result=await nativeStorage("restore_database");if(result)notify("Backup restored and the saved workspace reloaded.")});

function renderWelcome(data){const overlay=el("welcome-overlay");overlay.hidden=!data.needs_welcome;const configured=data.storage.configured;el("welcome-folder").classList.toggle("configured",configured);el("welcome-folder-title").textContent=configured?"Local data folder selected":"No data folder selected";el("welcome-folder-path").textContent=configured?data.storage.database_display:"Choose a folder before continuing.";el("welcome-choose-licence").disabled=!configured;el("welcome-continue").disabled=!configured;const licence=data.licence;el("welcome-licence-title").textContent=licence.mode==="LICENSED"?`Licensed to ${licence.firm_name}`:licence.mode==="TRIAL"?"30-day offline trial ready":"Start with the offline trial";el("welcome-licence-copy").textContent=licence.message}
async function loadStartup(){const data=await api("/api/startup");renderWelcome(data);return data}
el("welcome-choose-folder").addEventListener("click",async()=>{const result=await nativeStorage("choose_data_folder");if(result){await loadStartup();notify("Data folder selected. The offline trial has started.")}});
el("welcome-choose-licence").addEventListener("click",async()=>{if(!window.pywebview?.api?.choose_licence_file){notify("Open this in the desktop window to choose a licence file.",true);return}const result=await nativeInvoke("choose_licence_file",[],"Validating the offline licence…");if(result.cancelled)return;if(result.error){notify(result.error,true);return}await loadStartup();notify(result.licence.message)});
el("welcome-continue").addEventListener("click",async()=>{try{await api("/api/startup/complete",{method:"POST"});el("welcome-overlay").hidden=true;await loadHome()}catch(error){notify(error.message,true)}});
async function boot(){unlock();await loadHome();await loadStartup()}
boot();
