# Generated by Django 5.2.17 on 2026-08-21 06:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "cin",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Corporate Identity Number (CIN)",
                    ),
                ),
                ("is_listed_parent", models.BooleanField(default=False)),
                ("registered_office", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEntity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "cin",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Corporate Identity Number (CIN)",
                    ),
                ),
                ("is_listed_parent", models.BooleanField(default=False)),
                ("registered_office", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical entity",
                "verbose_name_plural": "historical Entities",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("SITE", "Site"),
                            ("BUILDING", "Building"),
                            ("FLOOR", "Floor"),
                            ("ROOM", "Room / Zone"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code used in the location breadcrumb, e.g. B2-F3-R01.",
                        max_length=32,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "floor_plan_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional floor-plan image for the site/floor-plan overlay view.",
                        null=True,
                        upload_to="floor_plans/",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.entity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "ordering": ["entity", "node_type", "name"],
                "unique_together": {("parent", "code")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("SITE", "Site"),
                            ("BUILDING", "Building"),
                            ("FLOOR", "Floor"),
                            ("ROOM", "Room / Zone"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code used in the location breadcrumb, e.g. B2-F3-R01.",
                        max_length=32,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "floor_plan_image",
                    models.TextField(
                        blank=True,
                        help_text="Optional floor-plan image for the site/floor-plan overlay view.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
