# Generated by Django 5.2.17 on 2026-08-21 06:01

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("SCRAP", "Scrap"),
                            ("WRITE_OFF", "Write-off (no proceeds)"),
                            ("DAMAGE", "Damaged / destroyed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("requested_disposal_date", models.DateField()),
                (
                    "net_book_value_at_request",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "sale_or_scrap_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "disposal_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "profit_or_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "is_material_section_180",
                    models.BooleanField(
                        default=False,
                        help_text="Could this disposal constitute selling a substantial part of an undertaking? Needs shareholder approval.",
                    ),
                ),
                (
                    "section_180_threshold_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Disposal value as % of total net PP&E at the time of request, for the Section 180 test.",
                        max_digits=5,
                    ),
                ),
                (
                    "board_resolution_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("buyer_or_scrap_vendor", models.CharField(blank=True, max_length=255)),
                (
                    "is_related_party",
                    models.BooleanField(
                        default=False,
                        help_text="Section 188 related-party disclosure flag.",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved & posted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposals_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_requests",
                        to="assets.asset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposals_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDisposalRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("SCRAP", "Scrap"),
                            ("WRITE_OFF", "Write-off (no proceeds)"),
                            ("DAMAGE", "Damaged / destroyed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("requested_disposal_date", models.DateField()),
                (
                    "net_book_value_at_request",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "sale_or_scrap_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "disposal_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "profit_or_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "is_material_section_180",
                    models.BooleanField(
                        default=False,
                        help_text="Could this disposal constitute selling a substantial part of an undertaking? Needs shareholder approval.",
                    ),
                ),
                (
                    "section_180_threshold_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Disposal value as % of total net PP&E at the time of request, for the Section 180 test.",
                        max_digits=5,
                    ),
                ),
                (
                    "board_resolution_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("buyer_or_scrap_vendor", models.CharField(blank=True, max_length=255)),
                (
                    "is_related_party",
                    models.BooleanField(
                        default=False,
                        help_text="Section 188 related-party disclosure flag.",
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, editable=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved & posted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical disposal request",
                "verbose_name_plural": "historical disposal requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
