table Dim_OpCo
	lineageTag: 6b4ca058-3d11-4e91-87e4-ad64d1f926cf

	column 'OpCo Code'
		dataType: string
		lineageTag: c86a505f-eec0-438f-953a-68287a52cafd
		summarizeBy: none
		sourceColumn: OpCo Code

		annotation SummarizationSetBy = User

	column 'OpCo Name'
		dataType: string
		lineageTag: 2f5ebd9c-3c8d-4dda-bebb-b3fab57899e9
		summarizeBy: none
		sourceColumn: OpCo Name

		annotation SummarizationSetBy = User

	column Country
		dataType: string
		lineageTag: 9f223e03-c6b7-4f06-b589-30097f9fddd0
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = User

	column Region
		dataType: string
		lineageTag: 7f5f53e2-f8cb-4618-b0ff-1da1f89e953f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = User

	column BU
		dataType: string
		lineageTag: 44634c32-3cc5-42d1-bcae-bd0107b24ed5
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = User

	column Functions
		dataType: string
		lineageTag: 7c301f99-30a8-4b57-b8a7-2a2af293791e
		summarizeBy: none
		sourceColumn: Functions

		annotation SummarizationSetBy = User

	column Active
		dataType: string
		lineageTag: 9050bffa-cf1f-4e15-99e5-6bfcbe74a591
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = User

	partition Dim_OpCo = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Dim_OpCo",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"OpCo Code", type text}, {"OpCo Name", type text}, {"Country", type text}, {"Region", type text}, {"BU", type text}, {"Functions", type text}, {"Active", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

