table Dim_KPI
	lineageTag: 57088ff0-8b02-403b-8263-f1f3a345b902

	column 'KPI ID'
		dataType: string
		lineageTag: 82fc22fb-daee-4e00-ad5a-9b73419de4c6
		summarizeBy: none
		sourceColumn: KPI ID

		annotation SummarizationSetBy = User

	column KPI
		dataType: string
		lineageTag: 97b996b2-6638-4432-b505-56a059af8218
		summarizeBy: none
		sourceColumn: KPI

		annotation SummarizationSetBy = User

	column 'KPI File Section'
		dataType: string
		lineageTag: 7f0dabec-304a-4ce9-9ae9-f31e0a9e3f25
		summarizeBy: none
		sourceColumn: KPI File Section

		annotation SummarizationSetBy = User

	column 'KPI Group'
		dataType: string
		lineageTag: f2b01ce7-1daa-44a9-9697-0116b28544b7
		summarizeBy: none
		sourceColumn: KPI Group

		annotation SummarizationSetBy = User

	column Description
		dataType: string
		lineageTag: 2b3e44b5-8fb3-4c25-966e-669c745793f1
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = User

	column Formula
		dataType: string
		lineageTag: 74afdb38-8aec-413c-8249-8c7408cb7b58
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = User

	column Unit
		dataType: string
		lineageTag: 5273ed15-41a7-41b8-a685-05f535bb3d54
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = User

	column Polarity
		dataType: string
		lineageTag: c70a588d-777e-48e5-b07b-c88ae8efe9a7
		summarizeBy: none
		sourceColumn: Polarity

		annotation SummarizationSetBy = User

	column 'Channel Scope'
		dataType: string
		lineageTag: 04edd814-d333-46d8-9013-72f559df7122
		summarizeBy: none
		sourceColumn: Channel Scope

		annotation SummarizationSetBy = User

	column Remarks
		dataType: string
		lineageTag: 8c99f607-6ce0-4be7-abd8-6d41b1d4ec81
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = User

	column 'Summary Card Section'
		dataType: string
		lineageTag: bc7db139-4ba0-44d1-a68d-ba7d34bedca8
		summarizeBy: none
		sourceColumn: Summary Card Section

		annotation SummarizationSetBy = User

	partition Dim_KPI = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Dim_KPI",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"Description (source)", "Description"}, {"Remarks (source)", "Remarks"}}),
				    Result = Table.TransformColumnTypes(Renamed, {{"KPI ID", type text}, {"KPI", type text}, {"KPI File Section", type text}, {"KPI Group", type text}, {"Description", type text}, {"Formula", type text}, {"Unit", type text}, {"Polarity", type text}, {"Channel Scope", type text}, {"Remarks", type text}, {"Summary Card Section", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

