table Dim_Date
	lineageTag: 7f2b0f8c-399d-4f0d-869f-e42936c60640
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: cfc97c20-471a-4485-a30e-d6aff74af239
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 954b2e3b-b869-4d36-b07b-de57e5013cbd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2f892a62-380c-4806-9817-e71f33bffc37
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: bcca4530-f4f5-479f-9a09-4e456ef7c2f2
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Short'
		dataType: string
		lineageTag: 944d9af6-2632-4bfd-b3a1-dcce0d0a705f
		summarizeBy: none
		sourceColumn: Month Short
		sortByColumn: Month

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: 76145570-3c64-45e3-88a4-6767e66cb977
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column Period
		dataType: int64
		formatString: 0
		lineageTag: 8adba439-c887-4ae4-9685-1ec989da0ec6
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = User

	partition Dim_Date = m
		mode: import
		source =
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2027, 12, 31),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    T = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    Typed = Table.TransformColumnTypes(T, {{"Date", type date}}),
				    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMName = Table.AddColumn(AddMonth, "Month Name", each Date.MonthName([Date], "en-US"), type text),
				    AddMShort = Table.AddColumn(AddMName, "Month Short", each Text.Start(Date.MonthName([Date], "en-US"), 3), type text),
				    AddQtr = Table.AddColumn(AddMShort, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    Result = Table.AddColumn(AddQtr, "Period", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type)
				in
				    Result

	annotation PBI_ResultType = Table

