table DQ_Exceptions
	lineageTag: 99a53823-3020-495c-be30-cbb28c3d1e5b

	column 'Run ID'
		dataType: string
		lineageTag: 92407abc-0c07-42b8-95c5-9b7fcc685874
		summarizeBy: none
		sourceColumn: Run ID

		annotation SummarizationSetBy = User

	column 'File Name'
		dataType: string
		lineageTag: 82a5e685-3ca9-4512-a39b-594f8a99aa73
		summarizeBy: none
		sourceColumn: File Name

		annotation SummarizationSetBy = User

	column 'Rule ID'
		dataType: string
		lineageTag: eb9998df-d596-4016-857c-0fabb41d2332
		summarizeBy: none
		sourceColumn: Rule ID

		annotation SummarizationSetBy = User

	column Severity
		dataType: string
		lineageTag: c0a4f878-5534-4010-bdd8-d57c619900f6
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = User

	column Row
		dataType: int64
		formatString: 0
		lineageTag: a8e3b32f-3112-42c0-abd2-98e136d066bb
		summarizeBy: none
		sourceColumn: Row

		annotation SummarizationSetBy = User

	column Column
		dataType: string
		lineageTag: 3602f672-6131-4895-93bc-80cde843e962
		summarizeBy: none
		sourceColumn: Column

		annotation SummarizationSetBy = User

	column Value
		dataType: string
		lineageTag: aedc104a-44c2-4941-bf9b-b58e2c46e54a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = User

	column Message
		dataType: string
		lineageTag: 5f54d0d4-1c75-4b75-9421-544733fe84ef
		summarizeBy: none
		sourceColumn: Message

		annotation SummarizationSetBy = User

	column Status
		dataType: string
		lineageTag: f896cc67-085e-40db-b03e-139072163c9a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = User

	partition DQ_Exceptions = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="DQ_Exceptions_Sample",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Run ID", type text}, {"File Name", type text}, {"Rule ID", type text}, {"Severity", type text}, {"Row", Int64.Type}, {"Column", type text}, {"Value", type text}, {"Message", type text}, {"Status", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

