table DQ_Rules
	lineageTag: d1cc8225-65b7-49ac-aa60-3d24f9caea56

	column 'Rule ID'
		dataType: string
		lineageTag: 862e1222-93e2-48d0-8603-d0e308b8a201
		summarizeBy: none
		sourceColumn: Rule ID

		annotation SummarizationSetBy = User

	column Check
		dataType: string
		lineageTag: 778aa59a-41fe-414a-b07b-a367a0738ebf
		summarizeBy: none
		sourceColumn: Check

		annotation SummarizationSetBy = User

	column 'Error Type'
		dataType: string
		lineageTag: 2c2f811a-bf90-4a14-bdec-664ac7fdfefb
		summarizeBy: none
		sourceColumn: Error Type

		annotation SummarizationSetBy = User

	column Severity
		dataType: string
		lineageTag: 37ce4337-cc05-45aa-af22-56693d4e95db
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = User

	column 'Where Implemented'
		dataType: string
		lineageTag: c51b9fd4-d097-42b8-9031-a11d9db910be
		summarizeBy: none
		sourceColumn: Where Implemented

		annotation SummarizationSetBy = User

	column 'Action if Failed'
		dataType: string
		lineageTag: d074775b-13fa-4f70-b590-8e7ba00bb5f3
		summarizeBy: none
		sourceColumn: Action if Failed

		annotation SummarizationSetBy = User

	partition DQ_Rules = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="DQ_Rules",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Rule ID", type text}, {"Check", type text}, {"Error Type", type text}, {"Severity", type text}, {"Where Implemented", type text}, {"Action if Failed", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

