table Publish_Control
	lineageTag: 61926d44-8318-4013-ae56-5c9f75901f9e

	column Period
		dataType: int64
		formatString: 0
		lineageTag: 37e24ba2-8749-4475-8956-5759cee1201b
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = User

	column Scenario
		dataType: string
		lineageTag: ff76268c-3068-4bfc-a05d-d4db515bedbc
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = User

	column 'File Name'
		dataType: string
		lineageTag: 30c1e2a6-2601-4638-b58a-b0a312b8e64f
		summarizeBy: none
		sourceColumn: File Name

		annotation SummarizationSetBy = User

	column Version
		dataType: int64
		formatString: 0
		lineageTag: c496d536-6f8e-4eb6-a4fe-e8b5e09d0da5
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = User

	column 'Rows Loaded'
		dataType: int64
		formatString: #,0
		lineageTag: 4bc0c799-bb23-44bf-b140-c69ac38ebe82
		summarizeBy: none
		sourceColumn: Rows Loaded

		annotation SummarizationSetBy = User

	column 'OpCos Loaded'
		dataType: int64
		formatString: 0
		lineageTag: acee3105-d318-4e02-9d74-128e3192c7db
		summarizeBy: none
		sourceColumn: OpCos Loaded

		annotation SummarizationSetBy = User

	column 'Critical Errors'
		dataType: int64
		formatString: 0
		lineageTag: 69d41dd3-c771-4ce4-a961-0a9f039b5249
		summarizeBy: none
		sourceColumn: Critical Errors

		annotation SummarizationSetBy = User

	column Warnings
		dataType: int64
		formatString: 0
		lineageTag: 4787d0e6-ee18-4aeb-b5b5-136f08e547e8
		summarizeBy: none
		sourceColumn: Warnings

		annotation SummarizationSetBy = User

	column Status
		dataType: string
		lineageTag: 16bba0f0-8953-40ad-a37e-824c3a66c0eb
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = User

	column 'Approved By'
		dataType: string
		lineageTag: a828f71f-0352-4f9e-afe0-0cbd828289d5
		summarizeBy: none
		sourceColumn: Approved By

		annotation SummarizationSetBy = User

	column 'Approved On'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9db9e4a1-b2b1-4100-a31b-b726940e7432
		summarizeBy: none
		sourceColumn: Approved On

		annotation SummarizationSetBy = User

	partition Publish_Control = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Publish_Control",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Period", Int64.Type}, {"Scenario", type text}, {"File Name", type text}, {"Version", Int64.Type}, {"Rows Loaded", Int64.Type}, {"OpCos Loaded", Int64.Type}, {"Critical Errors", Int64.Type}, {"Warnings", Int64.Type}, {"Status", type text}, {"Approved By", type text}, {"Approved On", type datetime}})
				in
				    Result

	annotation PBI_ResultType = Table

