<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Practice.Api/Practice.Api.csproj" />
    <ProjectReference Include="../../src/Practice.Billing/Practice.Billing.csproj" />
  </ItemGroup>
</Project>
