# -*- mode: python ; coding: utf-8 -*-
"""
Optimised single-file spec for LC Analyser.
- Uses targeted hidden-imports instead of collect_all to avoid pulling
  in the entire package tree (docs, tests, locale files, etc.).
- Explicitly excludes heavy packages that are installed globally but
  NOT used by this app (numpy, pandas, PyQt6, streamlit, selenium, etc.).
- Strips debug info and enables UPX for maximum compression.
- Does NOT change any application functionality.
"""

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        # python-docx
        'docx',
        'docx.document',
        'docx.opc',
        'docx.opc.constants',
        'docx.opc.package',
        'docx.opc.part',
        'docx.opc.rel',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.oxml.parser',
        'docx.oxml.table',
        'docx.oxml.text',
        'docx.oxml.section',
        'docx.oxml.styles',
        'docx.oxml.shape',
        'docx.oxml.shared',
        'docx.oxml.coreprops',
        'docx.oxml.document',
        'docx.oxml.numbering',
        'docx.shared',
        'docx.enum',
        'docx.enum.text',
        'docx.enum.table',
        'docx.enum.section',
        'docx.enum.style',
        'docx.table',
        'docx.text',
        'docx.text.paragraph',
        'docx.text.run',
        'docx.section',
        'docx.styles',
        'docx.styles.style',
        'docx.image',
        'docx.parts',
        'docx.parts.document',
        # reportlab
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.utils',
        'reportlab.lib.rl_accel',
        'reportlab.platypus',
        'reportlab.platypus.doctemplate',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.tables',
        'reportlab.platypus.frames',
        'reportlab.platypus.flowables',
        'reportlab.pdfbase',
        'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfbase._fontdata',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.graphics',
        # pypdf
        'pypdf',
        'pypdf._reader',
        'pypdf._page',
        'pypdf.generic',
        'pypdf._crypt_providers',
        'pypdf._crypt_providers._cryptography',
        # cryptography (for AES-encrypted bank/SWIFT PDFs)
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'cryptography.hazmat.primitives.ciphers.modes',
        '_cffi_backend',
        # lxml (required by python-docx / docx.oxml)
        'lxml',
        'lxml.etree',
        'lxml._elementpath',
        # PIL / Pillow (required by reportlab)
        'PIL',
        'PIL.Image',
        'PIL.PngImagePlugin',
        'PIL.JpegImagePlugin',
        # python-dateutil
        'dateutil',
        'dateutil.parser',
        'dateutil.relativedelta',
        # stdlib that pyinstaller sometimes misses
        'sqlite3',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Heavy unused submodules from lxml & PIL
        'lxml.objectify',
        'lxml.html',
        'lxml.sax',
        'lxml.builder',
        'lxml.isoschematron',
        'lxml.cssselect',
        'PIL._avif',
        'PIL._webp',
        'PIL._imagingcms',
        'PIL._imagingmath',
        'PIL._imagingtk',
        'PIL.SpiderImagePlugin',
        'PIL.TiffImagePlugin',
        'PIL.PdfImagePlugin',
        'PIL.EpsImagePlugin',
        'PIL.FpxImagePlugin',
        'PIL.MicImagePlugin',
        'PIL.MpegImagePlugin',
        'PIL.PalmImagePlugin',
        'PIL.PcdImagePlugin',
        'PIL.PixarImagePlugin',
        'PIL.PpmImagePlugin',
        'PIL.PsdImagePlugin',
        'PIL.SgiImagePlugin',
        'PIL.SunImagePlugin',
        'PIL.TgaImagePlugin',
        'PIL.WmfImagePlugin',
        'PIL.XbmImagePlugin',
        'PIL.XpmImagePlugin',
        'PIL.XVThumbImagePlugin',
        # Heavy packages NOT used by this app - exclude to shrink size
        'numpy',
        'pandas',
        'pyarrow',
        'streamlit',
        'altair',
        'pydeck',
        'selenium',
        'PyQt6',
        'PyQt5',
        'PySide6',
        'openpyxl',
        'xlsxwriter',
        'pymupdf',
        'fitz',
        'pytesseract',
        'winocr',
        'protobuf',
        'google',
        'uvicorn',
        'starlette',
        'watchdog',
        'requests',
        'urllib3',
        'certifi',
        'trio',
        'anyio',
        'httptools',
        'websockets',
        'websocket',
        'wsproto',
        'h11',
        'click',
        'jinja2',
        'markupsafe',
        'jsonschema',
        'toml',
        'dotenv',
        'python_dotenv',
        'narwhals',
        'tenacity',
        'blinker',
        'colorama',
        'winrt',
        # Test and dev tools
        'pytest',
        'unittest',
        'test',
        '_pytest',
        'doctest',
        'pdb',
        'pydoc',
        'lib2to3',
        # Unused stdlib that adds bulk
        'multiprocessing',
        'asyncio',
        'concurrent',
        'xmlrpc',
        'ftplib',
        'imaplib',
        'smtplib',
        'poplib',
        'nntplib',
        'telnetlib',
        'turtle',
        'turtledemo',
        'curses',
        'idlelib',
        'ensurepip',
        'distutils',
        'venv',
    ],
    noarchive=False,
    optimize=2,  # Strip docstrings & asserts
)

# Strip unnecessary heavy C-extension binaries collected by PyInstaller hooks
# (e.g. PIL._avif is 7.5MB raw / 4.2MB compressed and not needed for PDF/Word exports)
excluded_binary_patterns = [
    '_avif',
    '_webp',
    '_imagingcms',
    '_imagingmath',
    '_imagingtk',
    'objectify',
    'diff',
    '_difflib',
    'sax',
    'builder',
]

a.binaries = [
    b for b in a.binaries
    if not any(pat in b[0].lower() for pat in excluded_binary_patterns)
]

# Strip unnecessary datas (e.g. lxml schematron schemas, cyclonedx sboms)
a.datas = [
    d for d in a.datas
    if not any(pat in d[0].lower() for pat in ['isoschematron', 'cyclonedx', 'sbom'])
]

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='LC_Analyser',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,      # Strip is not available on Windows
    upx=True,         # Compress with UPX if available
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,     # Windowed app (no console)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
