# Generated by Django 5.2.17 on 2026-08-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(help_text="e.g. FY 2025-26", max_length=16)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_years",
                        to="locations.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("entity", "label")},
            },
        ),
        migrations.CreateModel(
            name="BenamiDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceedings_exist", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True)),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benami_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benami_declarations",
                        to="locations.entity",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benami_declarations",
                        to="compliance.financialyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-declared_at"],
                "unique_together": {("entity", "financial_year")},
            },
        ),
    ]
