<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Practice.Billing/Practice.Billing.csproj" />
    <ProjectReference Include="../Practice.BuildingBlocks/Practice.BuildingBlocks.csproj" />
    <ProjectReference Include="../Practice.Database/Practice.Database.csproj" />
    <ProjectReference Include="../Practice.Identity/Practice.Identity.csproj" />
    <ProjectReference Include="../Practice.Reporting/Practice.Reporting.csproj" />
    <ProjectReference Include="../Practice.Scheduling/Practice.Scheduling.csproj" />
  </ItemGroup>
</Project>
