<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Practice.BuildingBlocks/Practice.BuildingBlocks.csproj" />
    <ProjectReference Include="../Practice.Database/Practice.Database.csproj" />
  </ItemGroup>
</Project>
