import { BalanceSheetHeadConfig, EntityDetails, LedgerItem, ManualAdjustment } from '../types/accounting';

export const DEFAULT_HEAD_CONFIGS: BalanceSheetHeadConfig[] = [
  // Liabilities & Capital
  {
    id: 'head-L01',
    code: 'L01',
    mainHead: 'Capital & Liabilities',
    subHead: 'Capital Account / Owners\' Funds',
    scheduleNo: 1,
    scheduleTitle: 'Schedule 1 - Capital Account',
    nature: 'Liability',
    icaiMajorCategory: 'OWNERS_FUNDS',
    displayOrder: 1,
    active: true,
    isSpecialSchedule: 'CAPITAL',
    description: 'Proprietor / Partners capital, additional contributions, share of profit, drawings',
  },
  {
    id: 'head-L02',
    code: 'L02',
    mainHead: 'Capital & Liabilities',
    subHead: 'Reserves & Surplus',
    scheduleNo: 2,
    scheduleTitle: 'Schedule 2 - Reserves & Surplus',
    nature: 'Liability',
    icaiMajorCategory: 'OWNERS_FUNDS',
    displayOrder: 2,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'General reserves, revaluation reserves, retained earnings',
  },
  {
    id: 'head-L03',
    code: 'L03',
    mainHead: 'Capital & Liabilities',
    subHead: 'Long-Term Borrowings (Secured Loans)',
    scheduleNo: 3,
    scheduleTitle: 'Schedule 3 - Long-Term Borrowings',
    nature: 'Liability',
    icaiMajorCategory: 'NON_CURRENT_LIABILITIES',
    displayOrder: 3,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Term loans, vehicle loans, secured borrowings from banks/FIs',
  },
  {
    id: 'head-L04',
    code: 'L04',
    mainHead: 'Capital & Liabilities',
    subHead: 'Other Long-Term Liabilities (Unsecured Loans)',
    scheduleNo: 4,
    scheduleTitle: 'Schedule 4 - Other Long-Term Liabilities',
    nature: 'Liability',
    icaiMajorCategory: 'NON_CURRENT_LIABILITIES',
    displayOrder: 4,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Loans from relatives, partners, NBFCs, security deposits received (>12m)',
  },
  {
    id: 'head-L05',
    code: 'L05',
    mainHead: 'Capital & Liabilities',
    subHead: 'Trade Payables (Creditors & MSME)',
    scheduleNo: 5,
    scheduleTitle: 'Schedule 5 - Trade Payables',
    nature: 'Liability',
    icaiMajorCategory: 'CURRENT_LIABILITIES',
    displayOrder: 5,
    active: true,
    isSpecialSchedule: 'TRADE_PAYABLES',
    description: 'Sundry creditors for goods & services (with MSME disclosure)',
  },
  {
    id: 'head-L06',
    code: 'L06',
    mainHead: 'Capital & Liabilities',
    subHead: 'Other Current Liabilities & Provisions',
    scheduleNo: 6,
    scheduleTitle: 'Schedule 6 - Other Current Liabilities',
    nature: 'Liability',
    icaiMajorCategory: 'CURRENT_LIABILITIES',
    displayOrder: 6,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Statutory dues (GST, TDS, PF), advances from customers, expenses payable',
  },
  {
    id: 'head-L07',
    code: 'L07',
    mainHead: 'Capital & Liabilities',
    subHead: 'Short-Term Borrowings & Provisions',
    scheduleNo: 7,
    scheduleTitle: 'Schedule 7 - Short-Term Borrowings & Provisions',
    nature: 'Liability',
    icaiMajorCategory: 'CURRENT_LIABILITIES',
    displayOrder: 7,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Bank Cash Credit / Overdraft, short term provisions, income tax provision',
  },

  // Assets
  {
    id: 'head-A01',
    code: 'A01',
    mainHead: 'Assets',
    subHead: 'Property, Plant & Equipment (Fixed Assets)',
    scheduleNo: 8,
    scheduleTitle: 'Schedule 8 - Property, Plant & Equipment',
    nature: 'Asset',
    icaiMajorCategory: 'NON_CURRENT_ASSETS',
    displayOrder: 8,
    active: true,
    isSpecialSchedule: 'FIXED_ASSETS',
    description: 'Gross block, additions, deletions, accumulated depreciation & net block',
  },
  {
    id: 'head-A02',
    code: 'A02',
    mainHead: 'Assets',
    subHead: 'Non-Current Investments & Long-Term Assets',
    scheduleNo: 9,
    scheduleTitle: 'Schedule 9 - Non-Current Investments',
    nature: 'Asset',
    icaiMajorCategory: 'NON_CURRENT_ASSETS',
    displayOrder: 9,
    active: true,
    isSpecialSchedule: 'INVESTMENTS',
    description: 'Bank fixed deposits (>12m), long term shares, government securities, security deposits',
  },
  {
    id: 'head-A03',
    code: 'A03',
    mainHead: 'Assets',
    subHead: 'Inventories (Stock-in-Trade)',
    scheduleNo: 10,
    scheduleTitle: 'Schedule 10 - Inventories',
    nature: 'Asset',
    icaiMajorCategory: 'CURRENT_ASSETS',
    displayOrder: 10,
    active: true,
    isSpecialSchedule: 'INVENTORIES',
    description: 'Raw materials, work-in-progress, finished goods, stores & packing material',
  },
  {
    id: 'head-A04',
    code: 'A04',
    mainHead: 'Assets',
    subHead: 'Trade Receivables (Sundry Debtors)',
    scheduleNo: 11,
    scheduleTitle: 'Schedule 11 - Trade Receivables',
    nature: 'Asset',
    icaiMajorCategory: 'CURRENT_ASSETS',
    displayOrder: 11,
    active: true,
    isSpecialSchedule: 'TRADE_RECEIVABLES',
    description: 'Amounts due from customers for goods sold or services rendered',
  },
  {
    id: 'head-A05',
    code: 'A05',
    mainHead: 'Assets',
    subHead: 'Cash & Bank Balances',
    scheduleNo: 12,
    scheduleTitle: 'Schedule 12 - Cash & Bank Balances',
    nature: 'Asset',
    icaiMajorCategory: 'CURRENT_ASSETS',
    displayOrder: 12,
    active: true,
    isSpecialSchedule: 'CASH_BANK',
    description: 'Cash in hand, current accounts, auto-sweep deposits, term deposits (<12m)',
  },
  {
    id: 'head-A06',
    code: 'A06',
    mainHead: 'Assets',
    subHead: 'Short-Term Loans & Advances',
    scheduleNo: 13,
    scheduleTitle: 'Schedule 13 - Short-Term Loans & Advances',
    nature: 'Asset',
    icaiMajorCategory: 'CURRENT_ASSETS',
    displayOrder: 13,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Advance to suppliers, staff loans, GST input tax credits, advance tax / TDS paid',
  },
  {
    id: 'head-A07',
    code: 'A07',
    mainHead: 'Assets',
    subHead: 'Other Current Assets',
    scheduleNo: 14,
    scheduleTitle: 'Schedule 14 - Other Current Assets',
    nature: 'Asset',
    icaiMajorCategory: 'CURRENT_ASSETS',
    displayOrder: 14,
    active: true,
    isSpecialSchedule: 'STANDARD',
    description: 'Prepaid expenses, accrued interest, insurance claims receivable',
  },
];

export const DEFAULT_ENTITY: EntityDetails = {
  id: 'ent-01',
  name: 'M/s Apex Traders & Enterprises',
  entityType: 'Proprietorship',
  pan: 'ABCDE1234F',
  gstin: '27ABCDE1234F1Z5',
  address: 'Plot No. 42, Commercial Complex, Sector 18, Vashi, Navi Mumbai - 400703',
  financialYear: '2024-25',
  balanceSheetDate: '31st March 2025',
  previousYearDate: '31st March 2024',
  currencySymbol: '₹',
  currencyFormat: 'INR',
  auditorName: 'CA Priyanka Garg & Associates',
  membershipNumber: '512948',
  firmRegistrationNo: '124982W',
  udin: '25512948BGXYZW1234',
  placeOfSigning: 'Navi Mumbai',
  dateOfSigning: '25th August 2025',
  proprietorOrPartnerNames: ['Rajesh K. Sharma (Proprietor)'],
};

export const SAMPLE_ENTITIES: { entity: EntityDetails; ledgers: LedgerItem[]; adjustments?: ManualAdjustment[] }[] = [

  {
    entity: {
      id: 'ent-apex',
      name: 'M/s Apex Traders & Enterprises',
      entityType: 'Proprietorship',
      pan: 'ABCDE1234F',
      gstin: '27ABCDE1234F1Z5',
      address: 'Plot No. 42, Commercial Complex, Sector 18, Navi Mumbai - 400703',
      financialYear: '2024-25',
      balanceSheetDate: '31st March 2025',
      previousYearDate: '31st March 2024',
      currencySymbol: '₹',
      currencyFormat: 'INR',
      auditorName: 'CA Priyanka Garg & Associates',
      membershipNumber: '512948',
      firmRegistrationNo: '124982W',
      proprietorOrPartnerNames: ['Rajesh K. Sharma'],
    },
    ledgers: [
      // Capital & Drawings
      {
        id: 'led-1',
        ledgerName: 'Rajesh Sharma - Capital A/c',
        originalGroup: 'Capital Account',
        debit: 0,
        credit: 3500000,
        netBalance: -3500000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Proprietor opening capital account',
      },
      {
        id: 'led-2',
        ledgerName: 'Rajesh Sharma - Drawings A/c',
        originalGroup: 'Capital Account',
        debit: 480000,
        credit: 0,
        netBalance: 480000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Drawings account deducted from capital',
      },
      // Secured Loans
      {
        id: 'led-3',
        ledgerName: 'HDFC Bank - Cash Credit Facility (CC A/c)',
        originalGroup: 'Bank O/D Account',
        debit: 0,
        credit: 1850000,
        netBalance: -1850000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L03',
        mainHead: 'Capital & Liabilities',
        subHead: 'Secured Loans',
        scheduleNo: 3,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Bank Cash Credit against hypothecation of stock',
      },
      {
        id: 'led-4',
        ledgerName: 'ICICI Bank - Car Loan A/c',
        originalGroup: 'Secured Loans',
        debit: 0,
        credit: 420000,
        netBalance: -420000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L03',
        mainHead: 'Capital & Liabilities',
        subHead: 'Secured Loans',
        scheduleNo: 3,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Secured vehicle term loan',
      },
      // Unsecured Loans
      {
        id: 'led-5',
        ledgerName: 'Loan from Sunita Sharma (Relative)',
        originalGroup: 'Unsecured Loans',
        debit: 0,
        credit: 600000,
        netBalance: -600000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L04',
        mainHead: 'Capital & Liabilities',
        subHead: 'Unsecured Loans',
        scheduleNo: 4,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Unsecured family loan',
      },
      // Trade Payables
      {
        id: 'led-6',
        ledgerName: 'Vardhman Textiles Ltd.',
        originalGroup: 'Sundry Creditors',
        debit: 0,
        credit: 850000,
        netBalance: -850000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L05',
        mainHead: 'Capital & Liabilities',
        subHead: 'Trade Payables (Sundry Creditors)',
        scheduleNo: 5,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Trade supplier',
      },
      {
        id: 'led-7',
        ledgerName: 'Surat Poly-Fab Industries',
        originalGroup: 'Sundry Creditors',
        debit: 0,
        credit: 620000,
        netBalance: -620000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L05',
        mainHead: 'Capital & Liabilities',
        subHead: 'Trade Payables (Sundry Creditors)',
        scheduleNo: 5,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Trade supplier',
      },
      {
        id: 'led-8',
        ledgerName: 'Modern Yarn Suppliers',
        originalGroup: 'Sundry Creditors',
        debit: 0,
        credit: 340000,
        netBalance: -340000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L05',
        mainHead: 'Capital & Liabilities',
        subHead: 'Trade Payables (Sundry Creditors)',
        scheduleNo: 5,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Trade supplier',
      },
      // Other Current Liabilities
      {
        id: 'led-9',
        ledgerName: 'GST Output Liability Payable (CGST + SGST)',
        originalGroup: 'Duties & Taxes',
        debit: 0,
        credit: 145000,
        netBalance: -145000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L06',
        mainHead: 'Capital & Liabilities',
        subHead: 'Other Current Liabilities',
        scheduleNo: 6,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Statutory tax payable',
      },
      {
        id: 'led-10',
        ledgerName: 'TDS Payable (u/s 194C / 194J)',
        originalGroup: 'Duties & Taxes',
        debit: 0,
        credit: 38000,
        netBalance: -38000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L06',
        mainHead: 'Capital & Liabilities',
        subHead: 'Other Current Liabilities',
        scheduleNo: 6,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'TDS deducted at source payable',
      },
      {
        id: 'led-11',
        ledgerName: 'Outstanding Electricity & Rent Expenses',
        originalGroup: 'Current Liabilities',
        debit: 0,
        credit: 72000,
        netBalance: -72000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L06',
        mainHead: 'Capital & Liabilities',
        subHead: 'Other Current Liabilities',
        scheduleNo: 6,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Accrued expenses',
      },
      // Short term provisions
      {
        id: 'led-12',
        ledgerName: 'Audit Fees Payable Provision',
        originalGroup: 'Provisions',
        debit: 0,
        credit: 45000,
        netBalance: -45000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L07',
        mainHead: 'Capital & Liabilities',
        subHead: 'Short Term Provisions',
        scheduleNo: 7,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Statutory audit fee provision',
      },

      // Fixed Assets
      {
        id: 'led-13',
        ledgerName: 'Commercial Office Shop Premises',
        originalGroup: 'Fixed Assets',
        debit: 2400000,
        credit: 0,
        netBalance: 2400000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Immovable property asset',
      },
      {
        id: 'led-14',
        ledgerName: 'Plant & Packaging Machinery',
        originalGroup: 'Fixed Assets',
        debit: 950000,
        credit: 0,
        netBalance: 950000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Plant and machinery',
      },
      {
        id: 'led-15',
        ledgerName: 'Delivery Commercial Van',
        originalGroup: 'Fixed Assets',
        debit: 550000,
        credit: 0,
        netBalance: 550000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Vehicle asset',
      },
      {
        id: 'led-16',
        ledgerName: 'Computer Systems & Printers',
        originalGroup: 'Fixed Assets',
        debit: 145000,
        credit: 0,
        netBalance: 145000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Office IT equipment',
      },
      {
        id: 'led-17',
        ledgerName: 'Less: Accumulated Depreciation Provision',
        originalGroup: 'Fixed Assets',
        debit: 0,
        credit: 420000,
        netBalance: -420000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Cumulative depreciation reduction from fixed assets',
      },
      // Investments
      {
        id: 'led-18',
        ledgerName: 'Fixed Deposit with HDFC Bank (> 1 Year)',
        originalGroup: 'Investments',
        debit: 500000,
        credit: 0,
        netBalance: 500000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A02',
        mainHead: 'Assets',
        subHead: 'Investments',
        scheduleNo: 9,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Long term bank fixed deposit',
      },
      // Trade Receivables (Sundry Debtors)
      {
        id: 'led-19',
        ledgerName: 'Kolkata Fashion Garments',
        originalGroup: 'Sundry Debtors',
        debit: 920000,
        credit: 0,
        netBalance: 920000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A04',
        mainHead: 'Assets',
        subHead: 'Trade Receivables (Sundry Debtors)',
        scheduleNo: 11,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Customer receivable',
      },
      {
        id: 'led-20',
        ledgerName: 'Royal Retail Outlets',
        originalGroup: 'Sundry Debtors',
        debit: 740000,
        credit: 0,
        netBalance: 740000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A04',
        mainHead: 'Assets',
        subHead: 'Trade Receivables (Sundry Debtors)',
        scheduleNo: 11,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Customer receivable',
      },
      {
        id: 'led-21',
        ledgerName: 'Western Trendz Wholesale',
        originalGroup: 'Sundry Debtors',
        debit: 515000,
        credit: 0,
        netBalance: 515000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A04',
        mainHead: 'Assets',
        subHead: 'Trade Receivables (Sundry Debtors)',
        scheduleNo: 11,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Customer receivable',
      },
      // Cash & Bank
      {
        id: 'led-22',
        ledgerName: 'HDFC Bank - Current A/c No. 5020001284',
        originalGroup: 'Bank Accounts',
        debit: 462000,
        credit: 0,
        netBalance: 462000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A05',
        mainHead: 'Assets',
        subHead: 'Cash & Bank Balances',
        scheduleNo: 12,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Bank operational account',
      },
      {
        id: 'led-23',
        ledgerName: 'State Bank of India - Current A/c',
        originalGroup: 'Bank Accounts',
        debit: 218000,
        credit: 0,
        netBalance: 218000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A05',
        mainHead: 'Assets',
        subHead: 'Cash & Bank Balances',
        scheduleNo: 12,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Bank operational account',
      },
      {
        id: 'led-24',
        ledgerName: 'Cash in Hand (Petty Cash + Main)',
        originalGroup: 'Cash-in-hand',
        debit: 68000,
        credit: 0,
        netBalance: 68000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A05',
        mainHead: 'Assets',
        subHead: 'Cash & Bank Balances',
        scheduleNo: 12,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Physical cash balance',
      },
      // Loans & Advances / Other current assets
      {
        id: 'led-25',
        ledgerName: 'Security Deposit for Office Premises',
        originalGroup: 'Deposits (Asset)',
        debit: 200000,
        credit: 0,
        netBalance: 200000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A06',
        mainHead: 'Assets',
        subHead: 'Short Term Loans & Advances',
        scheduleNo: 13,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Rental security deposit',
      },
      {
        id: 'led-26',
        ledgerName: 'GST Electronic Credit Ledger (ITC Available)',
        originalGroup: 'Current Assets',
        debit: 182000,
        credit: 0,
        netBalance: 182000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A06',
        mainHead: 'Assets',
        subHead: 'Short Term Loans & Advances',
        scheduleNo: 13,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'GST ITC balance',
      },
      {
        id: 'led-27',
        ledgerName: 'Advance Income Tax & TDS Deducted by Clients',
        originalGroup: 'Current Assets',
        debit: 110000,
        credit: 0,
        netBalance: 110000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A06',
        mainHead: 'Assets',
        subHead: 'Short Term Loans & Advances',
        scheduleNo: 13,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Prepaid income taxes',
      },
      {
        id: 'led-28',
        ledgerName: 'Prepaid Commercial Fire & Burglary Insurance',
        originalGroup: 'Current Assets',
        debit: 28000,
        credit: 0,
        netBalance: 28000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A07',
        mainHead: 'Assets',
        subHead: 'Other Current Assets',
        scheduleNo: 14,
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Prepaid operational expenses',
      },

      // PROFIT & LOSS LEDGERS
      // Revenue / Direct Income
      {
        id: 'led-29',
        ledgerName: 'Sales - Domestic Finished Fabrics (GST 5%)',
        originalGroup: 'Sales Accounts',
        debit: 0,
        credit: 18450000,
        netBalance: -18450000,
        natureDrCr: 'Cr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_INCOME',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Revenue from operations',
      },
      {
        id: 'led-30',
        ledgerName: 'Job Work & Processing Receipts',
        originalGroup: 'Direct Incomes',
        debit: 0,
        credit: 780000,
        netBalance: -780000,
        natureDrCr: 'Cr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_INCOME',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Direct service revenue',
      },
      // Direct Expenses
      {
        id: 'led-31',
        ledgerName: 'Opening Stock of Fabrics & Yarn',
        originalGroup: 'Stock-in-hand',
        debit: 1420000,
        credit: 0,
        netBalance: 1420000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Opening inventory for trading P&L',
      },
      {
        id: 'led-32',
        ledgerName: 'Raw Material Purchases - Yarn & Grey Cloth',
        originalGroup: 'Purchase Accounts',
        debit: 11840000,
        credit: 0,
        netBalance: 11840000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Cost of materials consumed',
      },
      {
        id: 'led-33',
        ledgerName: 'Direct Wages & Labour Charges',
        originalGroup: 'Direct Expenses',
        debit: 960000,
        credit: 0,
        netBalance: 960000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Direct factory wages',
      },
      {
        id: 'led-34',
        ledgerName: 'Freight Inward & Cartage',
        originalGroup: 'Direct Expenses',
        debit: 215000,
        credit: 0,
        netBalance: 215000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Direct transportation on purchases',
      },
      {
        id: 'led-35',
        ledgerName: 'Power & Fuel Charges (Factory)',
        originalGroup: 'Direct Expenses',
        debit: 185000,
        credit: 0,
        netBalance: 185000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Direct manufacturing power',
      },

      // Indirect Incomes
      {
        id: 'led-36',
        ledgerName: 'Interest Received on Bank Fixed Deposits',
        originalGroup: 'Indirect Incomes',
        debit: 0,
        credit: 38000,
        netBalance: -38000,
        natureDrCr: 'Cr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_INCOME',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Non-operating financial income',
      },
      {
        id: 'led-37',
        ledgerName: 'Discount Received from Creditors',
        originalGroup: 'Indirect Incomes',
        debit: 0,
        credit: 24000,
        netBalance: -24000,
        natureDrCr: 'Cr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_INCOME',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Cash discount income',
      },

      // Indirect Expenses
      {
        id: 'led-38',
        ledgerName: 'Staff Salaries & Office Allowances',
        originalGroup: 'Indirect Expenses',
        debit: 1240000,
        credit: 0,
        netBalance: 1240000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Administrative employee expense',
      },
      {
        id: 'led-39',
        ledgerName: 'Rent, Rates & Taxes for Office',
        originalGroup: 'Indirect Expenses',
        debit: 480000,
        credit: 0,
        netBalance: 480000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Office rental expense',
      },
      {
        id: 'led-40',
        ledgerName: 'Bank Interest & CC Limit Processing Charges',
        originalGroup: 'Indirect Expenses',
        debit: 228000,
        credit: 0,
        netBalance: 228000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Finance costs',
      },
      {
        id: 'led-41',
        ledgerName: 'Depreciation on Fixed Assets',
        originalGroup: 'Indirect Expenses',
        debit: 240000,
        credit: 0,
        netBalance: 240000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Annual depreciation non-cash expense',
      },
      {
        id: 'led-42',
        ledgerName: 'Printing, Stationery & Courier',
        originalGroup: 'Indirect Expenses',
        debit: 42000,
        credit: 0,
        netBalance: 42000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Office overhead',
      },
      {
        id: 'led-43',
        ledgerName: 'Legal & Professional / Statutory Audit Fees',
        originalGroup: 'Indirect Expenses',
        debit: 75000,
        credit: 0,
        netBalance: 75000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Auditor & consultant remuneration',
      },
      {
        id: 'led-44',
        ledgerName: 'Telephone, Internet & Software Charges',
        originalGroup: 'Indirect Expenses',
        debit: 36000,
        credit: 0,
        netBalance: 36000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Communication and IT overhead',
      },
      {
        id: 'led-45',
        ledgerName: 'Sales Promotion & Traveling Expenses',
        originalGroup: 'Indirect Expenses',
        debit: 115000,
        credit: 0,
        netBalance: 115000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
        confidenceReason: 'Selling & distribution overhead',
      },
    ],
    adjustments: [
      {
        id: 'adj-1',
        date: '31/03/2025',
        description: 'Closing Stock of Raw Materials & Finished Goods (Valued at lower of cost or NRV)',
        debitHead: 'A03',
        creditHead: 'TRADING_CR',
        amount: 1850000,
        type: 'CLOSING_STOCK',
        notes: 'Physically verified and certified by management on 31st March 2025',
      },
    ],
  },
  {
    entity: {
      id: 'ent-kothari',
      name: 'Kothari & Sons Engineering Associates',
      entityType: 'Partnership Firm',
      pan: 'AABFK5432K',
      gstin: '24AABFK5432K1Z8',
      address: 'GIDC Industrial Estate, Phase 2, Vatva, Ahmedabad - 382445',
      financialYear: '2024-25',
      balanceSheetDate: '31st March 2025',
      previousYearDate: '31st March 2024',
      currencySymbol: '₹',
      currencyFormat: 'INR',
      auditorName: 'CA Snehal Mehta & Co.',
      membershipNumber: '118274',
      firmRegistrationNo: '109823W',
      proprietorOrPartnerNames: ['Sunil M. Kothari (Partner 50%)', 'Amit M. Kothari (Partner 50%)'],
    },
    ledgers: [
      {
        id: 'k-1',
        ledgerName: 'Sunil Kothari - Fixed Capital A/c',
        originalGroup: 'Capital Account',
        debit: 0,
        credit: 2500000,
        netBalance: -2500000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-2',
        ledgerName: 'Amit Kothari - Fixed Capital A/c',
        originalGroup: 'Capital Account',
        debit: 0,
        credit: 2500000,
        netBalance: -2500000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-3',
        ledgerName: 'Sunil Kothari - Drawings A/c',
        originalGroup: 'Capital Account',
        debit: 360000,
        credit: 0,
        netBalance: 360000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-4',
        ledgerName: 'Amit Kothari - Drawings A/c',
        originalGroup: 'Capital Account',
        debit: 360000,
        credit: 0,
        netBalance: 360000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L01',
        mainHead: 'Capital & Liabilities',
        subHead: 'Capital Account',
        scheduleNo: 1,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-5',
        ledgerName: 'SBI Term Loan (Factory Shed)',
        originalGroup: 'Secured Loans',
        debit: 0,
        credit: 3200000,
        netBalance: -3200000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L03',
        mainHead: 'Capital & Liabilities',
        subHead: 'Secured Loans',
        scheduleNo: 3,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-6',
        ledgerName: 'Precision Tools Raw Steel Suppliers',
        originalGroup: 'Sundry Creditors',
        debit: 0,
        credit: 1450000,
        netBalance: -1450000,
        natureDrCr: 'Cr',
        targetType: 'BALANCE_SHEET',
        headCode: 'L05',
        mainHead: 'Capital & Liabilities',
        subHead: 'Trade Payables (Sundry Creditors)',
        scheduleNo: 5,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-7',
        ledgerName: 'Factory Land & Building',
        originalGroup: 'Fixed Assets',
        debit: 4500000,
        credit: 0,
        netBalance: 4500000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-8',
        ledgerName: 'CNC Lathe & Milling Machinery',
        originalGroup: 'Fixed Assets',
        debit: 2800000,
        credit: 0,
        netBalance: 2800000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A01',
        mainHead: 'Assets',
        subHead: 'Fixed Assets (Property, Plant & Equipment)',
        scheduleNo: 8,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-9',
        ledgerName: 'Mahindra & Mahindra Ltd. (Customer)',
        originalGroup: 'Sundry Debtors',
        debit: 1650000,
        credit: 0,
        netBalance: 1650000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A04',
        mainHead: 'Assets',
        subHead: 'Trade Receivables (Sundry Debtors)',
        scheduleNo: 11,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-10',
        ledgerName: 'State Bank of India Current A/c',
        originalGroup: 'Bank Accounts',
        debit: 820000,
        credit: 0,
        netBalance: 820000,
        natureDrCr: 'Dr',
        targetType: 'BALANCE_SHEET',
        headCode: 'A05',
        mainHead: 'Assets',
        subHead: 'Cash & Bank Balances',
        scheduleNo: 12,
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-11',
        ledgerName: 'Manufactured Precision Components Sales',
        originalGroup: 'Sales Accounts',
        debit: 0,
        credit: 21500000,
        netBalance: -21500000,
        natureDrCr: 'Cr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_INCOME',
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-12',
        ledgerName: 'Special Alloy Steel Purchases',
        originalGroup: 'Purchase Accounts',
        debit: 13200000,
        credit: 0,
        netBalance: 13200000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-13',
        ledgerName: 'Machinists & Technician Wages',
        originalGroup: 'Direct Expenses',
        debit: 1800000,
        credit: 0,
        netBalance: 1800000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'DIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-14',
        ledgerName: 'Partner Working Remuneration (Sunil + Amit)',
        originalGroup: 'Indirect Expenses',
        debit: 1200000,
        credit: 0,
        netBalance: 1200000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
      {
        id: 'k-15',
        ledgerName: 'Interest on Partners Capital @ 12%',
        originalGroup: 'Indirect Expenses',
        debit: 600000,
        credit: 0,
        netBalance: 600000,
        natureDrCr: 'Dr',
        targetType: 'PROFIT_AND_LOSS',
        plCategory: 'INDIRECT_EXPENSE',
        status: 'CONFIRMED',
        confidence: 'HIGH',
      },
    ],
    adjustments: [
      {
        id: 'adj-k1',
        date: '31/03/2025',
        description: 'Closing Inventory of Raw Steel & Precision Components',
        debitHead: 'A03',
        creditHead: 'TRADING_CR',
        amount: 2400000,
        type: 'CLOSING_STOCK',
      },
    ],
  },
];

export const DEFAULT_ENTITIES: EntityDetails[] = SAMPLE_ENTITIES.map(s => s.entity);
export const SAMPLE_APEX_TRIAL_BALANCE: LedgerItem[] = SAMPLE_ENTITIES[0].ledgers;
export const SAMPLE_KOTHARI_TRIAL_BALANCE: LedgerItem[] = SAMPLE_ENTITIES[1].ledgers;

