table Dim_Scenario
	lineageTag: 3a0706d0-a0a8-40a9-b793-ca4b83b1dd0d

	column Scenario
		dataType: string
		lineageTag: 3eeb6050-1397-4d8b-bbe7-f0013d86f530
		summarizeBy: none
		sourceColumn: Scenario
		sortByColumn: Sort

		annotation SummarizationSetBy = User

	column Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 54925d68-6951-4c6f-a10a-8c85d776c20a
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = User

	column Description
		dataType: string
		lineageTag: 1a80c7fc-b149-4303-a7c7-405dadd21ada
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = User

	partition Dim_Scenario = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Dim_Scenario",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Scenario", type text}, {"Sort", Int64.Type}, {"Description", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

