table Dim_KPI
	lineageTag: 5115bed9-e590-4c0b-aa4d-3dabba2083f0

	column 'KPI ID'
		dataType: string
		lineageTag: 4f8ba311-7297-4a30-922b-f5a7142704e0
		summarizeBy: none
		sourceColumn: KPI ID

		annotation SummarizationSetBy = User

	column KPI
		dataType: string
		lineageTag: 6130f35a-5344-463e-935b-5eb527d16f8a
		summarizeBy: none
		sourceColumn: KPI

		annotation SummarizationSetBy = User

	column 'KPI File Section'
		dataType: string
		lineageTag: 7eac62db-3794-4220-8b10-be701020fc35
		summarizeBy: none
		sourceColumn: KPI File Section

		annotation SummarizationSetBy = User

	column 'KPI Group'
		dataType: string
		lineageTag: 42e13a6d-1066-4dd8-8c5a-8fc95ab14eea
		summarizeBy: none
		sourceColumn: KPI Group

		annotation SummarizationSetBy = User

	column Description
		dataType: string
		lineageTag: c9ff015c-a73b-448e-bf5b-707916749e28
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = User

	column Formula
		dataType: string
		lineageTag: af1c243d-b2a1-4b6e-b4bf-814d8d0b8097
		summarizeBy: none
		sourceColumn: Formula

		annotation SummarizationSetBy = User

	column Unit
		dataType: string
		lineageTag: 99c0540e-d5dc-41e6-a060-c5fb2b4938eb
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = User

	column Polarity
		dataType: string
		lineageTag: b480d843-bd18-42c7-b4b6-b7582a15d930
		summarizeBy: none
		sourceColumn: Polarity

		annotation SummarizationSetBy = User

	column 'Channel Scope'
		dataType: string
		lineageTag: 4324fa77-7fd1-4d69-a5f0-aa58ee865108
		summarizeBy: none
		sourceColumn: Channel Scope

		annotation SummarizationSetBy = User

	column Remarks
		dataType: string
		lineageTag: 0dbfe82b-9917-4570-97af-9216c2c37cd8
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = User

	column 'Summary Card Section'
		dataType: string
		lineageTag: 5d2cf60b-8922-44a6-a1c7-0d1f616f9347
		summarizeBy: none
		sourceColumn: Summary Card Section

		annotation SummarizationSetBy = User

	partition Dim_KPI = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Dim_KPI",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"Description (source)", "Description"}, {"Remarks (source)", "Remarks"}}),
				    Result = Table.TransformColumnTypes(Renamed, {{"KPI ID", type text}, {"KPI", type text}, {"KPI File Section", type text}, {"KPI Group", type text}, {"Description", type text}, {"Formula", type text}, {"Unit", type text}, {"Polarity", type text}, {"Channel Scope", type text}, {"Remarks", type text}, {"Summary Card Section", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

