table Dim_OpCo
	lineageTag: 8220bcc2-b5cb-43ff-aded-adcd32823f5c

	column 'OpCo Code'
		dataType: string
		lineageTag: e35beec9-197f-4dc6-a3be-cb5dd9dc6759
		summarizeBy: none
		sourceColumn: OpCo Code

		annotation SummarizationSetBy = User

	column 'OpCo Name'
		dataType: string
		lineageTag: c763c0f1-52a0-4a35-9ebe-1bd0bdf2020e
		summarizeBy: none
		sourceColumn: OpCo Name

		annotation SummarizationSetBy = User

	column Country
		dataType: string
		lineageTag: d13080b3-551b-4a57-9096-5e036dd51f96
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = User

	column Region
		dataType: string
		lineageTag: 78b71f61-3c8d-4683-af98-2ebece5b0179
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = User

	column BU
		dataType: string
		lineageTag: 5d1c9d0b-764a-4b23-b9b1-b82856ce926e
		summarizeBy: none
		sourceColumn: BU

		annotation SummarizationSetBy = User

	column Functions
		dataType: string
		lineageTag: 76b3b51a-86ed-47d8-948b-dfe2461b3aa2
		summarizeBy: none
		sourceColumn: Functions

		annotation SummarizationSetBy = User

	column Active
		dataType: string
		lineageTag: c110ea39-d1da-46bd-a34f-0997b671a2af
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = User

	partition Dim_OpCo = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Dim_OpCo",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"OpCo Code", type text}, {"OpCo Name", type text}, {"Country", type text}, {"Region", type text}, {"BU", type text}, {"Functions", type text}, {"Active", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

