table Dim_Date
	lineageTag: 4b50495d-9c14-4c8d-a77a-bd9dcc77662e
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 00531b3b-0d35-4d2c-b70d-703cc60dc7c6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: eb8b3dde-078d-4152-9861-683c664af72d
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7a0765ae-a2c3-4e62-9907-0aa8c6d68a75
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: b5055a8a-4f06-4406-ad9f-a511b7dc3746
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Short'
		dataType: string
		lineageTag: 5d454705-a494-4368-a9fe-f616f9abdf52
		summarizeBy: none
		sourceColumn: Month Short
		sortByColumn: Month

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: 48d05e38-de88-43f4-9fab-fac95089ed3f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column Period
		dataType: int64
		formatString: 0
		lineageTag: 8be274b6-af2e-42e8-b592-a9fc23c14651
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = User

	partition Dim_Date = m
		mode: import
		source =
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2027, 12, 31),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    T = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    Typed = Table.TransformColumnTypes(T, {{"Date", type date}}),
				    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMName = Table.AddColumn(AddMonth, "Month Name", each Date.MonthName([Date], "en-US"), type text),
				    AddMShort = Table.AddColumn(AddMName, "Month Short", each Text.Start(Date.MonthName([Date], "en-US"), 3), type text),
				    AddQtr = Table.AddColumn(AddMShort, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    Result = Table.AddColumn(AddQtr, "Period", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type)
				in
				    Result

	annotation PBI_ResultType = Table

