table DQ_Exceptions
	lineageTag: 5c8b5b03-31c1-460c-8a1a-6a0c4dcd262f

	column 'Run ID'
		dataType: string
		lineageTag: 282a5d9b-a98d-4f9e-8816-50cf8c2db6ff
		summarizeBy: none
		sourceColumn: Run ID

		annotation SummarizationSetBy = User

	column 'File Name'
		dataType: string
		lineageTag: 3cdd4c48-2851-4a8a-9e5d-17142145c8c7
		summarizeBy: none
		sourceColumn: File Name

		annotation SummarizationSetBy = User

	column 'Rule ID'
		dataType: string
		lineageTag: d354fe3a-be55-409d-b7ca-cebf7ecbe85f
		summarizeBy: none
		sourceColumn: Rule ID

		annotation SummarizationSetBy = User

	column Severity
		dataType: string
		lineageTag: f191a644-7ec4-4764-a917-da5c0b4c5aae
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = User

	column Row
		dataType: int64
		formatString: 0
		lineageTag: 37d65235-c899-4c13-8fd2-cb745a71afff
		summarizeBy: none
		sourceColumn: Row

		annotation SummarizationSetBy = User

	column Column
		dataType: string
		lineageTag: f8f1e51b-6c44-45d7-83f9-a8dc7226e249
		summarizeBy: none
		sourceColumn: Column

		annotation SummarizationSetBy = User

	column Value
		dataType: string
		lineageTag: c9884a00-9dbe-47c7-bae0-c0fa7e0a184e
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = User

	column Message
		dataType: string
		lineageTag: ade7e9ab-e7b9-4531-a363-25993f00b0ec
		summarizeBy: none
		sourceColumn: Message

		annotation SummarizationSetBy = User

	column Status
		dataType: string
		lineageTag: 8b1055ce-d4d1-49d6-a593-fcb6149292d0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = User

	partition DQ_Exceptions = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="DQ_Exceptions_Sample",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Run ID", type text}, {"File Name", type text}, {"Rule ID", type text}, {"Severity", type text}, {"Row", Int64.Type}, {"Column", type text}, {"Value", type text}, {"Message", type text}, {"Status", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

