table DQ_Rules
	lineageTag: 72446535-b362-4784-9501-d71d85b9e79c

	column 'Rule ID'
		dataType: string
		lineageTag: 5876d87e-78ad-469f-9099-1abc6af27fb7
		summarizeBy: none
		sourceColumn: Rule ID

		annotation SummarizationSetBy = User

	column Check
		dataType: string
		lineageTag: a8eef3f4-8a30-48a2-9299-8f1d1d04d49b
		summarizeBy: none
		sourceColumn: Check

		annotation SummarizationSetBy = User

	column 'Error Type'
		dataType: string
		lineageTag: e3c12180-e137-492a-802a-103b0f52cb18
		summarizeBy: none
		sourceColumn: Error Type

		annotation SummarizationSetBy = User

	column Severity
		dataType: string
		lineageTag: e3bf0685-d7cf-4cd3-9e07-e36728f4cffc
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = User

	column 'Where Implemented'
		dataType: string
		lineageTag: d2b63b7e-c07f-48cd-b50b-f622555b7ec6
		summarizeBy: none
		sourceColumn: Where Implemented

		annotation SummarizationSetBy = User

	column 'Action if Failed'
		dataType: string
		lineageTag: 03b912b8-bfe7-46c6-9d73-5009d86888f7
		summarizeBy: none
		sourceColumn: Action if Failed

		annotation SummarizationSetBy = User

	partition DQ_Rules = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="DQ_Rules",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Rule ID", type text}, {"Check", type text}, {"Error Type", type text}, {"Severity", type text}, {"Where Implemented", type text}, {"Action if Failed", type text}})
				in
				    Result

	annotation PBI_ResultType = Table

