table Fact_SC_PL
	lineageTag: 97c953d6-7718-4ecf-9d41-a8724117bb9f

	column 'Date Key'
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: a168b7f9-d9f9-4191-ae5f-11ee2084c8b1
		summarizeBy: none
		sourceColumn: Date Key

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'OpCo Code'
		dataType: string
		isHidden
		lineageTag: f4e7641b-e3fe-4a2c-8ede-5e7f6adc9aae
		summarizeBy: none
		sourceColumn: OpCo Code

		annotation SummarizationSetBy = User

	column 'SC Function'
		dataType: string
		isHidden
		lineageTag: 045c2493-f460-4626-9f64-76f0dce1e0d5
		summarizeBy: none
		sourceColumn: SC Function

		annotation SummarizationSetBy = User

	column 'Account Code'
		dataType: string
		isHidden
		lineageTag: 8d50b9c5-caf9-4b0e-b681-66862a89466f
		summarizeBy: none
		sourceColumn: Account Code

		annotation SummarizationSetBy = User

	column Scenario
		dataType: string
		isHidden
		lineageTag: 3ed1beb9-d679-4eef-89f9-72788f1c6d3a
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = User

	column Channel
		dataType: string
		lineageTag: fbdda1fa-5dba-418a-8ae9-cc7f23df9f22
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = User

	column AccDetail
		dataType: string
		lineageTag: 6245c20a-b5db-45d6-a7df-33947af18364
		summarizeBy: none
		sourceColumn: AccDetail

		annotation SummarizationSetBy = User

	column 'Amount USD'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 80cbdf55-3f83-481e-8d28-a548e41ba2fb
		summarizeBy: none
		sourceColumn: Amount USD

		annotation SummarizationSetBy = User

	column 'Volume Pairs'
		dataType: double
		isHidden
		formatString: #,0
		lineageTag: 8df37de0-cccc-4e26-84b3-ec6e47d77daa
		summarizeBy: none
		sourceColumn: Volume Pairs

		annotation SummarizationSetBy = User

	partition Fact_SC_PL = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Fact_Extract_Sample",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Year", Int64.Type}, {"Month", Int64.Type}, {"Amount", type number}, {"OpCo Code", type text}, {"SC Function", type text}, {"Account", type text}, {"Scenario", type text}, {"Channel", type text}, {"AccDetail", type text}}),
				    AddDate = Table.AddColumn(Typed, "Date Key", each #date([Year], [Month], 1), type date),
				    AddUSD = Table.AddColumn(AddDate, "Amount USD", each if List.Contains({"PURCH_PAIRS", "PROD_PAIRS"}, [Account]) then null else [Amount], type nullable number),
				    AddPairs = Table.AddColumn(AddUSD, "Volume Pairs", each if List.Contains({"PURCH_PAIRS", "PROD_PAIRS"}, [Account]) then [Amount] else null, type nullable number),
				    Selected = Table.SelectColumns(AddPairs, {"Date Key", "OpCo Code", "SC Function", "Account", "Scenario", "Channel", "AccDetail", "Amount USD", "Volume Pairs"}),
				    Result = Table.RenameColumns(Selected, {{"Account", "Account Code"}})
				in
				    Result

	annotation PBI_ResultType = Table

