table PL_Layout
	lineageTag: fab7b30c-c0ba-4cd3-b8ea-61947f1f749f

	column Sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 745dfde1-4aa3-4f0d-ba30-befac9be1096
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = User

	column 'Row Label'
		dataType: string
		lineageTag: 2608b0c7-d9e3-4eff-ad1f-f4d36d720d70
		summarizeBy: none
		sourceColumn: Row Label
		sortByColumn: Sort

		annotation SummarizationSetBy = User

	column 'Row Type'
		dataType: string
		lineageTag: 9e8d31a2-097a-4082-9a9f-9b02fb52cbc1
		summarizeBy: none
		sourceColumn: Row Type

		annotation SummarizationSetBy = User

	column Key
		dataType: string
		lineageTag: 075f8e34-2ba8-4e6b-b124-2c2a3d1263db
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = User

	column Format
		dataType: string
		lineageTag: cfd8744a-010b-423f-8f59-252249064f22
		summarizeBy: none
		sourceColumn: Format

		annotation SummarizationSetBy = User

	column Bold
		dataType: int64
		formatString: 0
		lineageTag: 609ee6eb-38fd-497c-9a4f-bec1bf41c57a
		summarizeBy: none
		sourceColumn: Bold

		annotation SummarizationSetBy = User

	partition PL_Layout = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="PL_Layout",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Renamed = Table.RenameColumns(Promoted, {{"Account Code / Measure", "Key"}}),
				    Result = Table.TransformColumnTypes(Renamed, {{"Sort", Int64.Type}, {"Row Label", type text}, {"Row Type", type text}, {"Key", type text}, {"Format", type text}, {"Bold", Int64.Type}})
				in
				    Result

	annotation PBI_ResultType = Table

