table Publish_Control
	lineageTag: 72de277a-a484-4b48-8f27-75459a5b85dd

	column Period
		dataType: int64
		formatString: 0
		lineageTag: 09e57fd9-3167-46e7-be10-490b2d06d94d
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = User

	column Scenario
		dataType: string
		lineageTag: 758bf9a6-1060-4ce0-b0c0-479111b21ae2
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = User

	column 'File Name'
		dataType: string
		lineageTag: 385f768a-f79b-4fa9-88ab-029bc99cce6f
		summarizeBy: none
		sourceColumn: File Name

		annotation SummarizationSetBy = User

	column Version
		dataType: int64
		formatString: 0
		lineageTag: fb8d7ac7-55a4-4533-b19a-fcbc43406d3a
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = User

	column 'Rows Loaded'
		dataType: int64
		formatString: #,0
		lineageTag: 40a9a822-7e53-4ef4-8564-60a7b5ab3257
		summarizeBy: none
		sourceColumn: Rows Loaded

		annotation SummarizationSetBy = User

	column 'OpCos Loaded'
		dataType: int64
		formatString: 0
		lineageTag: d611642c-d160-4877-99ca-e56c5f7883ad
		summarizeBy: none
		sourceColumn: OpCos Loaded

		annotation SummarizationSetBy = User

	column 'Critical Errors'
		dataType: int64
		formatString: 0
		lineageTag: ab4dc9dc-c2d1-4fbe-8dcd-7e61867b7530
		summarizeBy: none
		sourceColumn: Critical Errors

		annotation SummarizationSetBy = User

	column Warnings
		dataType: int64
		formatString: 0
		lineageTag: 79b52760-773d-490a-9234-4f9fce3e42b5
		summarizeBy: none
		sourceColumn: Warnings

		annotation SummarizationSetBy = User

	column Status
		dataType: string
		lineageTag: 1039a4cb-e808-470e-b568-167c912d1d1a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = User

	column 'Approved By'
		dataType: string
		lineageTag: a5a43565-7a15-441b-9343-411077bd8548
		summarizeBy: none
		sourceColumn: Approved By

		annotation SummarizationSetBy = User

	column 'Approved On'
		dataType: dateTime
		formatString: General Date
		lineageTag: 09472473-ef10-4bcb-8397-82ce5c6257e5
		summarizeBy: none
		sourceColumn: Approved On

		annotation SummarizationSetBy = User

	partition Publish_Control = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SampleDataFile), null, true),
				    Sheet = Source{[Item="Publish_Control",Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Result = Table.TransformColumnTypes(Promoted, {{"Period", Int64.Type}, {"Scenario", type text}, {"File Name", type text}, {"Version", Int64.Type}, {"Rows Loaded", Int64.Type}, {"OpCos Loaded", Int64.Type}, {"Critical Errors", Int64.Type}, {"Warnings", Int64.Type}, {"Status", type text}, {"Approved By", type text}, {"Approved On", type datetime}})
				in
				    Result

	annotation PBI_ResultType = Table

