import React, { useState } from 'react';
import { AlertTriangle, X, ShieldAlert, CheckCircle2 } from 'lucide-react';

interface DuplicateWarningModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirmOverride: (reason: string) => void;
  duplicateAssetId: string;
  existingRecord?: {
    id?: number;
    asset_id: string;
    company_name: string;
    description: string;
    asset_type: string;
    location?: string;
    status?: string;
    created_at: string;
    created_by: string;
  };
  loading?: boolean;
}

export const DuplicateWarningModal: React.FC<DuplicateWarningModalProps> = ({
  isOpen,
  onClose,
  onConfirmOverride,
  duplicateAssetId,
  existingRecord,
  loading = false,
}) => {
  const [reason, setReason] = useState('');
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const handleOverride = (e: React.FormEvent) => {
    e.preventDefault();
    if (!reason.trim() || reason.trim().length < 5) {
      setError('Please provide a mandatory justification comment of at least 5 characters.');
      return;
    }
    setError('');
    onConfirmOverride(reason.trim());
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="bg-white rounded-xl shadow-2xl border border-amber-200 max-w-lg w-full overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="bg-amber-50 px-6 py-4 border-b border-amber-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-amber-100 rounded-lg text-amber-700">
              <AlertTriangle className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">Duplicate Asset ID Detected</h3>
              <p className="text-xs text-amber-800 font-medium">Critical Control & Audit Verification</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 rounded-lg p-1 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleOverride} className="p-6 space-y-4">
          <div className="bg-amber-50/50 border border-amber-200/80 rounded-lg p-3 text-xs text-amber-900 leading-relaxed">
            The Asset ID <span className="font-bold font-mono text-slate-900 bg-amber-100 px-1.5 py-0.5 rounded">{duplicateAssetId}</span> is already registered in the database for this company.
          </div>

          {/* Existing Record Details */}
          {existingRecord && (
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 space-y-2 text-xs">
              <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                Existing Asset Information
              </div>
              <div className="grid grid-cols-2 gap-x-2 gap-y-1 text-slate-700">
                <div>
                  <span className="font-semibold text-slate-500">Company: </span>
                  <span className="font-medium text-slate-900">{existingRecord.company_name}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-500">Asset Type: </span>
                  <span className="font-medium text-slate-900">{existingRecord.asset_type}</span>
                </div>
                <div className="col-span-2">
                  <span className="font-semibold text-slate-500">Description: </span>
                  <span className="font-medium text-slate-900">{existingRecord.description}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-500">Location: </span>
                  <span className="font-medium text-slate-900">{existingRecord.location || '—'}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-500">Status: </span>
                  <span className="font-semibold text-emerald-700">{existingRecord.status || 'Active'}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-500">Generated By: </span>
                  <span className="font-medium text-slate-900">{existingRecord.created_by}</span>
                </div>
                <div>
                  <span className="font-semibold text-slate-500">Date: </span>
                  <span className="font-medium text-slate-900">{existingRecord.created_at}</span>
                </div>
              </div>
            </div>
          )}

          {/* Mandatory Override Reason */}
          <div>
            <label className="block text-xs font-bold text-slate-800 mb-1">
              Mandatory Override Justification <span className="text-red-600">*</span>
            </label>
            <textarea
              rows={3}
              value={reason}
              onChange={(e) => {
                setReason(e.target.value);
                if (error) setError('');
              }}
              placeholder="e.g., Replacement tag required for damaged physical sticker / SAP master correction..."
              className="w-full text-xs rounded-lg border border-slate-300 px-3 py-2 text-slate-900 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:border-amber-500"
            />
            {error && <p className="mt-1 text-xs text-red-600 font-medium">{error}</p>}
            <p className="mt-1 text-[11px] text-slate-500">
              This action will be logged in the permanent audit trail with your user account and timestamp.
            </p>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-100">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-white bg-amber-600 hover:bg-amber-700 disabled:opacity-50 rounded-lg shadow-sm transition"
            >
              <ShieldAlert className="w-4 h-4" />
              {loading ? 'Processing Override...' : 'Confirm Duplicate Override'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
