// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Practice.Database;

#nullable disable

namespace Practice.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819193112_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Practice.Database.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", "system");

                    b.HasData(
                        new
                        {
                            Key = "organization.time_zone",
                            Description = "IANA time zone used for firm-local dates and scheduling.",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "\"Asia/Kolkata\""
                        },
                        new
                        {
                            Key = "reporting.financial_year_start",
                            Description = "Start of the Indian financial reporting year.",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ValueJson = "{\"month\":4,\"day\":1}"
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_entity");

                    b.ToTable("audit_events", "audit");
                });

            modelBuilder.Entity("Practice.Database.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holiday_date");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("holiday_type");

                    b.Property<bool>("IsWorkingDayOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working_day_override");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_holidays");

                    b.HasIndex("HolidayCalendarId", "HolidayDate")
                        .IsUnique()
                        .HasDatabaseName("ux_holidays_calendar_date");

                    b.ToTable("holidays", "system", t =>
                        {
                            t.HasCheckConstraint("ck_holidays_type", "holiday_type IN ('Public', 'Firm', 'Optional')");
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.HolidayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_holiday_calendars");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_holiday_calendars_code");

                    b.ToTable("holiday_calendars", "system");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70a45f7b-dfde-4af0-a634-876797f19501"),
                            Code = "IN-DEFAULT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "India firm default",
                            RegionCode = "IN",
                            TimeZoneId = "Asia/Kolkata"
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.ImportIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("column_name");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_run_id");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("issue_code");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("RawValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("raw_value");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("SheetName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sheet_name");

                    b.HasKey("Id")
                        .HasName("pk_import_issues");

                    b.HasIndex("ImportRunId", "Severity", "IssueCode")
                        .HasDatabaseName("ix_import_issues_run_severity_code");

                    b.ToTable("import_issues", "import", t =>
                        {
                            t.HasCheckConstraint("ck_import_issues_severity", "severity IN ('Info', 'Warning', 'Error')");
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_summary");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<string>("ReportJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("report_json");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_sha256");

                    b.Property<long>("SourceSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("source_size_bytes");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.HasIndex("SourceSha256")
                        .HasDatabaseName("ix_import_runs_source_sha256");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_import_runs_started");

                    b.ToTable("import_runs", "import", t =>
                        {
                            t.HasCheckConstraint("ck_import_runs_mode", "mode IN ('Profile', 'DryRun', 'Import')");

                            t.HasCheckConstraint("ck_import_runs_size", "source_size_bytes >= 0");

                            t.HasCheckConstraint("ck_import_runs_status", "status IN ('Running', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.IndiaState", b =>
                {
                    b.Property<string>("GstCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("gst_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUnionTerritory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_union_territory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("GstCode")
                        .HasName("pk_india_states");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_india_states_name");

                    b.ToTable("india_states", "reference");

                    b.HasData(
                        new
                        {
                            GstCode = "01",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Jammu and Kashmir"
                        },
                        new
                        {
                            GstCode = "02",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Himachal Pradesh"
                        },
                        new
                        {
                            GstCode = "03",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Punjab"
                        },
                        new
                        {
                            GstCode = "04",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Chandigarh"
                        },
                        new
                        {
                            GstCode = "05",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Uttarakhand"
                        },
                        new
                        {
                            GstCode = "06",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Haryana"
                        },
                        new
                        {
                            GstCode = "07",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Delhi"
                        },
                        new
                        {
                            GstCode = "08",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Rajasthan"
                        },
                        new
                        {
                            GstCode = "09",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Uttar Pradesh"
                        },
                        new
                        {
                            GstCode = "10",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Bihar"
                        },
                        new
                        {
                            GstCode = "11",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Sikkim"
                        },
                        new
                        {
                            GstCode = "12",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Arunachal Pradesh"
                        },
                        new
                        {
                            GstCode = "13",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Nagaland"
                        },
                        new
                        {
                            GstCode = "14",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Manipur"
                        },
                        new
                        {
                            GstCode = "15",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Mizoram"
                        },
                        new
                        {
                            GstCode = "16",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Tripura"
                        },
                        new
                        {
                            GstCode = "17",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Meghalaya"
                        },
                        new
                        {
                            GstCode = "18",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Assam"
                        },
                        new
                        {
                            GstCode = "19",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "West Bengal"
                        },
                        new
                        {
                            GstCode = "20",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Jharkhand"
                        },
                        new
                        {
                            GstCode = "21",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Odisha"
                        },
                        new
                        {
                            GstCode = "22",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Chhattisgarh"
                        },
                        new
                        {
                            GstCode = "23",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Madhya Pradesh"
                        },
                        new
                        {
                            GstCode = "24",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Gujarat"
                        },
                        new
                        {
                            GstCode = "26",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Dadra and Nagar Haveli and Daman and Diu"
                        },
                        new
                        {
                            GstCode = "27",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            GstCode = "29",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Karnataka"
                        },
                        new
                        {
                            GstCode = "30",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Goa"
                        },
                        new
                        {
                            GstCode = "31",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Lakshadweep"
                        },
                        new
                        {
                            GstCode = "32",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Kerala"
                        },
                        new
                        {
                            GstCode = "33",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Tamil Nadu"
                        },
                        new
                        {
                            GstCode = "34",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Puducherry"
                        },
                        new
                        {
                            GstCode = "35",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Andaman and Nicobar Islands"
                        },
                        new
                        {
                            GstCode = "36",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Telangana"
                        },
                        new
                        {
                            GstCode = "37",
                            IsActive = true,
                            IsUnionTerritory = false,
                            Name = "Andhra Pradesh"
                        },
                        new
                        {
                            GstCode = "38",
                            IsActive = true,
                            IsUnionTerritory = true,
                            Name = "Ladakh"
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "system", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Practice.Database.Entities.Holiday", b =>
                {
                    b.HasOne("Practice.Database.Entities.HolidayCalendar", "HolidayCalendar")
                        .WithMany("Holidays")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holidays_calendar");

                    b.Navigation("HolidayCalendar");
                });

            modelBuilder.Entity("Practice.Database.Entities.ImportIssue", b =>
                {
                    b.HasOne("Practice.Database.Entities.ImportRun", "ImportRun")
                        .WithMany("Issues")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_issues_run");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("Practice.Database.Entities.HolidayCalendar", b =>
                {
                    b.Navigation("Holidays");
                });

            modelBuilder.Entity("Practice.Database.Entities.ImportRun", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
