#!/usr/bin/env python3
"""
DCF Valuation Professional
Offline desktop valuation utility for listed and unlisted companies.

Features:
- Listed / Unlisted valuation modes
- 5-year historical financial input
- 5-year FCFF forecast
- CAPM / WACC
- Bottom-up beta for unlisted companies using listed comparables
- Gordon Growth terminal value
- Enterprise value -> Equity value bridge
- Value per share
- WACC x terminal growth sensitivity
- Bear / Base / Bull scenarios
- Save / Open project (.json)
- Export Excel, Word, PDF and PowerPoint reports
- No API key, cloud service or internet connection required

Academic/professional support tool only. Users remain responsible for assumptions,
data accuracy and compliance with applicable valuation standards/regulations.
"""

import json
import math
import os
import sys
import traceback
import re
import hashlib
import hmac
import platform
import uuid
import base64
import statistics
import urllib.request
import urllib.error
import urllib.parse
import ssl
import subprocess
import shutil
import socket
import threading
import time
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
import tkinter as tk
from tkinter import ttk, filedialog, messagebox

APP_NAME = "DCF Valuation Professional"
APP_VERSION = "3.0.6"


# ---------------------------------------------------------------------------
# OFFLINE DEMO / ASYMMETRIC LICENSING - v3.0
# ---------------------------------------------------------------------------
LICENSE_CONTACT = "airajeshkamath07@gmail.com"
LICENSE_PUBLIC_KEY_B64 = "RkYjqomJtIkMaxh0QDMI7e+dzXwv0JxttQSA3capDBY="

def _license_dir():
    if os.name == "nt":
        root = os.environ.get("LOCALAPPDATA") or os.environ.get("APPDATA") or str(Path.home())
    else:
        root = os.environ.get("XDG_DATA_HOME") or str(Path.home() / ".local" / "share")
    p = Path(root) / "DCFValuationProfessional"
    p.mkdir(parents=True, exist_ok=True)
    return p

def machine_code():
    parts = [platform.system(), platform.machine(), platform.node(), str(uuid.getnode())]
    raw = "|".join(parts).encode("utf-8", "ignore")
    digest = hashlib.sha256(raw).hexdigest().upper()
    return "-".join([digest[i:i+4] for i in range(0, 20, 4)])

def _state_path():
    return _license_dir() / "license_state_v306.json"

def _load_license_state():
    try:
        p = _state_path()
        return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}
    except Exception:
        return {}

def _save_license_state(state):
    _state_path().write_text(json.dumps(state, indent=2), encoding="utf-8")

def _registry_demo_used():
    if os.name != "nt":
        return False
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Software\DCFValuationProfessional", 0, winreg.KEY_READ) as k:
            val, _ = winreg.QueryValueEx(k, "DemoUsedV3")
            return str(val) == "1"
    except Exception:
        return False

def _set_registry_demo_used():
    if os.name != "nt":
        return
    try:
        import winreg
        k = winreg.CreateKey(winreg.HKEY_CURRENT_USER, r"Software\DCFValuationProfessional")
        winreg.SetValueEx(k, "DemoUsedV3", 0, winreg.REG_SZ, "1")
        winreg.CloseKey(k)
    except Exception:
        pass

def _verify_activation_token_detailed(token_text):
    """
    Returns (ok, reason, payload_obj).
    This gives precise diagnostics without exposing the private signing key.
    """
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
    except Exception as e:
        return False, f"Cryptography library unavailable: {e}", None

    try:
        token_text = (token_text or "").strip()
        # Remove accidental spaces/newlines copied from wrapped text boxes.
        token_text = "".join(token_text.split())
        if not token_text:
            return False, "No reuse key was entered.", None
        if "." not in token_text:
            return False, "Malformed key: separator is missing.", None

        payload_b64, sig_b64 = token_text.split(".", 1)
        try:
            payload = base64.urlsafe_b64decode(payload_b64 + "=" * (-len(payload_b64) % 4))
            signature = base64.urlsafe_b64decode(sig_b64 + "=" * (-len(sig_b64) % 4))
        except Exception:
            return False, "Malformed key: Base64 decoding failed.", None

        try:
            pub = Ed25519PublicKey.from_public_bytes(base64.b64decode(LICENSE_PUBLIC_KEY_B64))
            pub.verify(signature, payload)
        except Exception:
            return False, "Signature verification failed. This key was not generated by the matching v3.0.6 private generator.", None

        try:
            obj = json.loads(payload.decode("utf-8"))
        except Exception:
            return False, "Signed payload is not valid JSON.", None

        if obj.get("product") != "DCFVP306":
            return False, f"Wrong product/version token: {obj.get('product')!r}. Expected DCFVP306.", obj

        signed_machine = str(obj.get("machine", "")).strip().upper()
        current_machine = machine_code().strip().upper()
        if signed_machine != current_machine:
            return False, f"Machine-code mismatch. Key is for {signed_machine}; this PC is {current_machine}.", obj

        return True, "Signature, product and machine code are valid.", obj
    except Exception as e:
        return False, f"Unexpected verification error: {e}", None


def _verify_activation_token(token_text):
    ok, _, _ = _verify_activation_token_detailed(token_text)
    return ok

def license_gate():
    state = _load_license_state()
    token = state.get("activation_token", "")
    if token and _verify_activation_token(token):
        return True

    used = bool(state.get("demo_used")) or _registry_demo_used()
    if not used:
        state["demo_used"] = True
        state["first_launch"] = datetime.now().isoformat(timespec="seconds")
        state["machine_code"] = machine_code()
        _save_license_state(state)
        _set_registry_demo_used()
        return True

    root = tk.Tk()
    root.withdraw()
    dlg = tk.Toplevel(root)
    dlg.title(f"{APP_NAME} - Activation")
    dlg.geometry("620x380")
    dlg.resizable(False, False)
    dlg.grab_set()

    ttk.Label(dlg, text="🔒 Demo is over", font=("Segoe UI", 18, "bold")).pack(pady=(22, 8))
    ttk.Label(
        dlg,
        text=f"Demo is over, contact {LICENSE_CONTACT} for reuse key.",
        font=("Segoe UI", 11),
        wraplength=550,
        justify="center"
    ).pack(padx=20, pady=6)

    ttk.Label(dlg, text="Machine Code", font=("Segoe UI", 10, "bold")).pack(pady=(18, 3))
    mc = machine_code()
    mc_var = tk.StringVar(value=mc)
    ttk.Entry(dlg, textvariable=mc_var, width=34, justify="center", state="readonly").pack()

    ttk.Label(dlg, text="Signed Reuse Key", font=("Segoe UI", 10, "bold")).pack(pady=(16, 3))
    token_var = tk.StringVar()
    token_entry = ttk.Entry(dlg, textvariable=token_var, width=72, justify="center")
    token_entry.pack(padx=18)
    token_entry.focus_set()
    result = {"ok": False}

    def activate():
        supplied = token_var.get().strip()
        ok, reason, _ = _verify_activation_token_detailed(supplied)
        if ok:
            clean_token = "".join(supplied.split())
            state["activation_token"] = clean_token
            state["activated_on"] = datetime.now().isoformat(timespec="seconds")
            state["machine_code"] = mc
            state["activated_version"] = APP_VERSION
            _save_license_state(state)
            result["ok"] = True
            messagebox.showinfo("Activated", "Reuse key accepted. This system is activated.", parent=dlg)
            dlg.destroy()
        else:
            messagebox.showerror("Invalid Key", reason, parent=dlg)

    def diagnose_key():
        ok, reason, payload = _verify_activation_token_detailed(token_var.get())
        details = reason
        if payload:
            details += "\n\nSigned product: " + str(payload.get("product"))
            details += "\nSigned machine: " + str(payload.get("machine"))
            details += "\nCurrent machine: " + machine_code()
        messagebox.showinfo("Activation Diagnostics" if ok else "Activation Diagnostics", details, parent=dlg)

    def copy_code():
        root.clipboard_clear(); root.clipboard_append(mc)
        messagebox.showinfo("Machine Code", "Machine code copied to clipboard.", parent=dlg)

    bf = ttk.Frame(dlg); bf.pack(pady=20)
    ttk.Button(bf, text="Copy Machine Code", command=copy_code).pack(side="left", padx=5)
    ttk.Button(bf, text="Diagnose Key", command=diagnose_key).pack(side="left", padx=5)
    ttk.Button(bf, text="Activate", command=activate).pack(side="left", padx=5)
    ttk.Button(bf, text="Exit", command=dlg.destroy).pack(side="left", padx=5)

    dlg.protocol("WM_DELETE_WINDOW", dlg.destroy)
    root.wait_window(dlg)
    root.destroy()
    return result["ok"]

YEARS_HIST = ["FY-4", "FY-3", "FY-2", "FY-1", "FY0"]
YEARS_FCST = ["FY1E", "FY2E", "FY3E", "FY4E", "FY5E"]

def num(v, default=0.0):
    try:
        if v is None:
            return default
        s = str(v).strip().replace(",", "").replace("₹", "").replace("%", "")
        if not s:
            return default
        return float(s)
    except Exception:
        return default

def pct(v, default=0.0):
    x = num(v, default)
    return x / 100.0

def fmt_money(v):
    try:
        return f"{v:,.2f}"
    except Exception:
        return "-"

def fmt_pct(v):
    try:
        return f"{v*100:.2f}%"
    except Exception:
        return "-"

def safe_div(a, b, default=0.0):
    return a / b if b not in (0, 0.0, None) else default


FINANCIAL_ALIASES = {
    "sales": ["revenue from operations","revenue from operation","net revenue from operations","revenue","net sales","sales","turnover","income from operations"],
    "other_income": ["other income"],
    "ebitda": ["ebitda","pbdt","pbdit","pbitda","profit before depreciation interest and tax","earnings before interest tax depreciation and amortisation"],
    "finance_cost": ["finance costs","finance cost","interest expense"],
    "da": ["depreciation and amortisation expense","depreciation and amortisation","depreciation & amortisation","depreciation expense","depreciation"],
    "pbt": ["profit before tax","profit before exceptional items and tax","profit before exceptional item and tax"],
    "ebit": ["ebit","profit before interest and tax","profit before finance cost and tax","operating profit"],
    "capex": ["purchase of property plant and equipment","purchase of property, plant and equipment","purchase of fixed assets","capital expenditure","capex"],
    "inventories": ["inventories","inventory","stock in trade","stock-in-trade"],
    "trade_receivables": ["trade receivables","sundry debtors","debtors"],
    "other_current_assets": ["other current assets","current tax assets","loans current","other financial assets current"],
    "trade_payables": ["trade payables","sundry creditors","creditors"],
    "other_current_liabilities": ["other current liabilities","other financial liabilities current","current provisions"],
    "nwc": ["net working capital"],
}

def _extract_numbers(text):
    if text is None:
        return []
    # Financial statement-friendly number extraction, including brackets as negatives.
    pats = re.findall(r"(?<![A-Za-z])(?:\(?-?\s*[₹$€£]?\s*\d[\d,]*(?:\.\d+)?\)?)(?![A-Za-z])", str(text))
    vals = []
    for p in pats:
        s = p.replace("₹","").replace("$","").replace("€","").replace("£","").replace(",","").replace(" ","")
        neg = s.startswith("(") and s.endswith(")")
        s = s.strip("()")
        try:
            v = float(s)
            vals.append(-v if neg else v)
        except Exception:
            pass
    return vals

def _clean_label(value):
    s = str(value or "").strip().lower()
    return re.sub(r"\s+", " ", s)

def _numeric_cells(row):
    vals = []
    for x in row:
        if isinstance(x, (int, float)) and not isinstance(x, bool):
            vals.append(float(x))
        else:
            vals.extend(_extract_numbers(x))
    return vals

def _score_label_match(label, aliases):
    label = _clean_label(label)
    if not label:
        return 0
    score = 0
    for a in aliases:
        aa = a.lower()
        if label == aa:
            score = max(score, 100)
        elif label.startswith(aa) or aa.startswith(label):
            score = max(score, 85)
        elif aa in label:
            score = max(score, 70)
    if any(b in label for b in ["note", "ratio", "per share", "eps", "tax audit"]):
        score -= 25
    return score

def _pick_best_row(candidates, periods=5):
    ranked = []
    for score, ridx, label, vals in candidates:
        vals = [v for v in vals if math.isfinite(v)]
        if not vals:
            continue
        period_bonus = min(len(vals), periods) * 3
        nonzero_bonus = sum(1 for v in vals[-periods:] if abs(v) > 1e-9)
        magnitude_penalty = 30 if any(abs(v) > 1e12 for v in vals) else 0
        ranked.append((score + period_bonus + nonzero_bonus - magnitude_penalty, ridx, label, vals))
    if not ranked:
        return None
    ranked.sort(key=lambda x: (x[0], x[1]), reverse=True)
    return ranked[0]

def _validate_mapped_financials(mapped):
    warnings = []
    if "sales" in mapped:
        sales = mapped["sales"]
        for metric in ["ebitda", "da", "ebit", "capex"]:
            if metric in mapped:
                ratios = [abs(mapped[metric][i] / sales[i]) for i in range(5) if abs(sales[i]) > 1e-9]
                if ratios and statistics.median(ratios) > 1.0:
                    warnings.append(f"{metric.upper()} appears unusually large relative to revenue; verify the source row.")
        if "ebitda" in mapped:
            if any(abs(sales[i]) > 1e-9 and abs(mapped["ebitda"][i] / sales[i]) > 0.75 for i in range(5)):
                warnings.append("One or more EBITDA margins exceed 75%; verify the imported EBITDA row.")
    if "nwc" not in mapped:
        warnings.append("Net Working Capital was not mapped automatically. Enter NWC manually after reviewing operating current assets and liabilities.")
    return warnings


def _cell_year_score(v):
    return 1 if re.search(r"(?:19|20)\d{2}", str(v or "")) else 0

def _find_year_columns(rows):
    scores={}
    for row in rows[:50]:
        for idx,v in enumerate(row):
            if _cell_year_score(v):
                scores[idx]=scores.get(idx,0)+1
    if not scores:
        return []
    ranked=sorted(scores,key=lambda i:(-scores[i],i))
    return sorted(ranked[:5])

def _row_label(row):
    return " ".join(str(x).strip() for x in row[:8] if isinstance(x,str) and str(x).strip())

def _row_numeric_values(row,year_cols=None):
    if year_cols:
        vals=[]
        for idx in year_cols:
            x=row[idx] if idx<len(row) else None
            if isinstance(x,(int,float)) and not isinstance(x,bool):
                vals.append(float(x))
            else:
                nums=_extract_numbers(x)
                vals.append(nums[-1] if nums else 0.0)
        return vals
    nums=[]
    for x in row:
        if isinstance(x,(int,float)) and not isinstance(x,bool):
            nums.append(float(x))
        else:
            nums.extend(_extract_numbers(x))
    return nums[-5:]

def _statement_context(sheet_name,text):
    s=(str(sheet_name)+" "+str(text)).lower()
    if any(k in s for k in ["profit and loss","profit & loss","statement of profit","p&l","pl account"]): return "P&L"
    if any(k in s for k in ["cash flow","cashflow"]): return "CASHFLOW"
    if any(k in s for k in ["balance sheet","balance-sheet"]): return "BALANCE"
    return "UNKNOWN"

def _semantic_score(metric,label,context):
    score=_score_label_match(label,FINANCIAL_ALIASES.get(metric,[]))
    if metric in ("sales","other_income","ebitda","finance_cost","da","pbt","ebit") and context=="P&L": score+=25
    if metric=="capex" and context=="CASHFLOW": score+=25
    if metric in ("inventories","trade_receivables","other_current_assets","trade_payables","other_current_liabilities","nwc") and context=="BALANCE": score+=25
    low=(label or "").lower()
    if any(b in low for b in ["ratio","note no","earnings per share","eps","segment"]): score-=25
    return score

def _confidence(score):
    if score>=110:return "High"
    if score>=85:return "Medium"
    if score>=60:return "Low"
    return "Reject"

def extract_financials_from_excel(path):
    from openpyxl import load_workbook
    wb=load_workbook(path,data_only=True,read_only=True)
    candidates={k:[] for k in FINANCIAL_ALIASES}
    preview=[]; warnings=[]; provenance={}; confidence={}
    for ws in wb.worksheets:
        rows=[list(r) for r in ws.iter_rows(values_only=True)]
        year_cols=_find_year_columns(rows)
        head=" ".join(_row_label(r) for r in rows[:20])
        sheet_ctx=_statement_context(ws.title,head)
        for ridx,row in enumerate(rows,start=1):
            nonempty=[x for x in row if x not in ("",None)]
            if not nonempty:continue
            line=" | ".join(str(x) for x in nonempty)
            preview.append(f"[{ws.title}!{ridx}] {line}")
            label=_row_label(row)
            if not label:continue
            ctx=sheet_ctx if sheet_ctx!="UNKNOWN" else _statement_context(ws.title,label)
            vals=_row_numeric_values(row,year_cols)
            if not vals or not any(abs(v)>1e-12 for v in vals):continue
            for metric in FINANCIAL_ALIASES:
                sc=_semantic_score(metric,label,ctx)
                if sc>0:
                    candidates[metric].append((sc,ridx,f"{ws.title}!{ridx}: {label}",vals[-5:],ctx))
    mapped={}
    for metric,cands in candidates.items():
        if not cands:continue
        cands.sort(key=lambda x:(x[0],sum(abs(v)>1e-12 for v in x[3]),x[1]),reverse=True)
        sc,_,label,vals,_=cands[0]
        vals=[0.0]*(5-len(vals))+vals[-5:]
        mapped[metric]=vals; provenance[metric]=label; confidence[metric]=_confidence(sc)

    if "ebit" not in mapped:
        if "pbt" in mapped and "finance_cost" in mapped:
            mapped["ebit"]=[mapped["pbt"][i]+mapped["finance_cost"][i] for i in range(5)]
            provenance["ebit"]="Derived: PBT + Finance Cost"; confidence["ebit"]="Medium"
        elif "ebitda" in mapped and "da" in mapped:
            mapped["ebit"]=[mapped["ebitda"][i]-mapped["da"][i] for i in range(5)]
            provenance["ebit"]="Derived: EBITDA - D&A"; confidence["ebit"]="Medium"
    if "ebitda" not in mapped and "ebit" in mapped and "da" in mapped:
        mapped["ebitda"]=[mapped["ebit"][i]+mapped["da"][i] for i in range(5)]
        provenance["ebitda"]="Derived: EBIT + D&A"; confidence["ebitda"]="Medium"

    if "nwc" not in mapped:
        assets=[mapped[k] for k in ["inventories","trade_receivables","other_current_assets"] if k in mapped]
        liabs=[mapped[k] for k in ["trade_payables","other_current_liabilities"] if k in mapped]
        if assets or liabs:
            mapped["nwc"]=[sum(v[i] for v in assets)-sum(v[i] for v in liabs) for i in range(5)]
            provenance["nwc"]="Derived from operating current assets less operating current liabilities"
            confidence["nwc"]="Medium"
        else:
            warnings.append("Net Working Capital could not be derived reliably; enter it manually.")

    sales=mapped.get("sales")
    if not sales or max(abs(v) for v in sales)<=1e-9:
        warnings.append("CRITICAL: Revenue / Net Sales could not be mapped reliably.")
        confidence["sales"]="Reject"
    if sales:
        for metric in ["ebitda","da","ebit","capex"]:
            if metric in mapped:
                ratios=[abs(mapped[metric][i]/sales[i]) for i in range(5) if abs(sales[i])>1e-9]
                if ratios:
                    med=statistics.median(ratios)
                    limit=0.75 if metric in ("ebitda","ebit") else 0.40
                    if med>limit:
                        warnings.append(f"CRITICAL: {metric.upper()} is implausibly large relative to revenue.")
                        confidence[metric]="Reject"

    return mapped,"\n".join(preview[:2200]),provenance,warnings,confidence


def extract_financials_from_pdf(path):
    from pypdf import PdfReader
    reader=PdfReader(path); parts=[]
    for i,page in enumerate(reader.pages[:100]):
        try:t=page.extract_text() or ""
        except Exception:t=""
        if t:parts.append(f"--- PAGE {i+1} ---\n{t}")
    text="\n".join(parts)
    lines=[ln.strip() for ln in text.splitlines() if ln.strip()]
    result={}; provenance={}; confidence={}; warnings=[]
    for metric in FINANCIAL_ALIASES:
        matches=[]
        for idx,ln in enumerate(lines):
            ctx=_statement_context("",ln)
            sc=_semantic_score(metric,ln,ctx)
            nums=_extract_numbers(ln) if sc>0 else []
            if nums:matches.append((sc,idx,ln,nums[-5:]))
        if matches:
            matches.sort(key=lambda x:(x[0],len(x[3]),x[1]),reverse=True)
            sc,_,label,vals=matches[0]
            result[metric]=[0.0]*(5-len(vals))+vals[-5:]
            provenance[metric]=label[:250]; confidence[metric]=_confidence(sc)
    if "ebit" not in result and "pbt" in result and "finance_cost" in result:
        result["ebit"]=[result["pbt"][i]+result["finance_cost"][i] for i in range(5)]
        provenance["ebit"]="Derived: PBT + Finance Cost"; confidence["ebit"]="Medium"
    if "ebitda" not in result and "ebit" in result and "da" in result:
        result["ebitda"]=[result["ebit"][i]+result["da"][i] for i in range(5)]
        provenance["ebitda"]="Derived: EBIT + D&A"; confidence["ebitda"]="Medium"
    if "sales" not in result or max(abs(v) for v in result.get("sales",[0]))<=1e-9:
        warnings.append("CRITICAL: Revenue not mapped reliably."); confidence["sales"]="Reject"
    if "nwc" not in result:warnings.append("NWC not mapped from PDF; manual review required.")
    return result,text[:60000],provenance,warnings,confidence

def offline_assumption_engine(data):
    """Deterministic offline analytics. No model/API call."""
    hist = data["historical"]
    sales = [num(x) for x in hist["sales"]]
    ebitda = [num(x) for x in hist["ebitda"]]
    da = [num(x) for x in hist["da"]]
    capex = [num(x) for x in hist["capex"]]
    nwc = [num(x) for x in hist["nwc"]]

    positive_sales = [(i,v) for i,v in enumerate(sales) if v > 0]
    cagr = 0.08
    if len(positive_sales) >= 2:
        i0,v0 = positive_sales[0]
        i1,v1 = positive_sales[-1]
        yrs = max(1, i1-i0)
        cagr = (v1/v0)**(1/yrs)-1 if v0 > 0 and v1 > 0 else 0.08
    cagr = min(max(cagr, -0.05), 0.25)

    margins = [safe_div(e,s) for e,s in zip(ebitda,sales) if s>0 and e!=0]
    margin = statistics.median(margins[-3:]) if margins else 0.18
    margin = min(max(margin, 0.05), 0.40)

    da_ratios = [safe_div(d,s) for d,s in zip(da,sales) if s>0 and d>=0]
    capex_ratios = [safe_div(c,s) for c,s in zip(capex,sales) if s>0 and c>=0]
    da_pct = statistics.median(da_ratios[-3:]) if da_ratios else 0.03
    capex_pct = statistics.median(capex_ratios[-3:]) if capex_ratios else max(0.04, da_pct*1.15)

    growth = []
    start = cagr
    terminal_operating_growth = min(max(0.06, cagr*0.55), 0.10)
    for i in range(5):
        growth.append(start + (terminal_operating_growth-start)*(i/4))
    margin_target = min(0.40, max(0.05, margin + 0.01))
    margins_fcst = [margin + (margin_target-margin)*(i/4) for i in range(5)]

    # NWC intensity based on ending NWC/sales; use conservative fraction of incremental revenue.
    nwc_ratios = [safe_div(n,s) for n,s in zip(nwc,sales) if s>0 and n!=0]
    nwc_inc = statistics.median(nwc_ratios[-3:]) if nwc_ratios else 0.08
    nwc_inc = min(max(nwc_inc, 0.02), 0.25)

    return {
        "growth": [round(x*100,2) for x in growth],
        "ebitda_margin": [round(x*100,2) for x in margins_fcst],
        "tax_rate": 25.0,
        "da_pct": round(da_pct*100,2),
        "capex_pct": round(capex_pct*100,2),
        "nwc_increment_pct": round(nwc_inc*100,2),
        "terminal_growth": 5.0,
        "rationale": (
            f"Offline engine used historical sales CAGR of {cagr*100:.2f}%, "
            f"median EBITDA margin of {margin*100:.2f}%, and normalized reinvestment ratios. "
            "Forecast growth is mean-reverting rather than a straight extrapolation."
        )
    }

def _extract_json_object(text):
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        raise ValueError("AI response did not contain a JSON object.")
    return json.loads(m.group(0))

def build_ai_prompt(data, preview=""):
    compact = {
        "company": data["company"],
        "historical": data["historical"],
        "current_inputs": {
            "risk_free": data["capital"]["risk_free"],
            "erp": data["capital"]["erp"],
            "beta": data["capital"]["beta"],
            "cost_debt": data["capital"]["cost_debt"]
        }
    }
    return f"""You are a valuation analyst. Review the supplied historical financial data and propose a conservative, internally consistent five-year FCFF DCF assumption set.
Return JSON only, with this exact schema:
{{
  "growth":[5 numbers in percent],
  "ebitda_margin":[5 numbers in percent],
  "tax_rate":number percent,
  "da_pct":number percent of revenue,
  "capex_pct":number percent of revenue,
  "nwc_increment_pct":number percent of incremental revenue,
  "terminal_growth":number percent,
  "rationale":"brief explanation",
  "warnings":["data quality or valuation warnings"]
}}
Rules:
- Do not invent historical numbers.
- Normalize one-off volatility.
- Terminal growth must be below a reasonable WACC and should be sustainable.
- Flag missing or weak data.
- This is an assumption recommendation, not an investment recommendation.

STRUCTURED DATA:
{json.dumps(compact, indent=2)}

OPTIONAL EXTRACTED DOCUMENT TEXT:
{preview[:18000]}
"""


def ollama_health():
    """Return (ok, message, installed_models)."""
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags", method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            obj = json.loads(resp.read().decode("utf-8"))
        models = []
        for m in obj.get("models", []):
            name = m.get("name") or m.get("model")
            if name:
                models.append(name)
        return True, "Ollama is running locally.", models
    except urllib.error.URLError as e:
        reason = getattr(e, "reason", e)
        # Friendly distinction for connection refused
        if isinstance(reason, ConnectionRefusedError) or "10061" in str(reason) or "refused" in str(reason).lower():
            exe = shutil.which("ollama")
            if exe:
                return False, "Ollama is installed but its local service is not running. Start Ollama, or run: ollama serve", []
            return False, "Ollama is not reachable. Install Ollama for Windows, start it, then download a model such as: ollama pull gemma3", []
        return False, f"Ollama connection failed: {reason}", []
    except Exception as e:
        return False, f"Ollama check failed: {e}", []

def try_start_ollama():
    """Best-effort start of local Ollama server if executable is available."""
    exe = shutil.which("ollama")
    if not exe:
        return False, "Ollama executable was not found in PATH."
    try:
        # Avoid console popup on Windows where possible.
        creationflags = 0
        if os.name == "nt" and hasattr(subprocess, "CREATE_NO_WINDOW"):
            creationflags = subprocess.CREATE_NO_WINDOW
        subprocess.Popen(
            [exe, "serve"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            creationflags=creationflags
        )
        import time
        for _ in range(10):
            time.sleep(0.5)
            ok, msg, models = ollama_health()
            if ok:
                return True, msg
        return False, "Ollama was started but the local API did not become ready in time."
    except Exception as e:
        return False, f"Could not start Ollama automatically: {e}"

def provider_default_model(provider):
    p = provider.lower()
    if p.startswith("ollama"):
        return "gemma3"
    if p.startswith("openai"):
        return "gpt-5.6-terra"
    if p.startswith("gemini"):
        return "gemini-3.7-flash"
    return ""

def friendly_ai_error(provider, exc):
    msg = str(exc)
    p = provider.lower()
    if p.startswith("ollama") and ("timed out" in msg.lower() or "timeout" in msg.lower()):
        return (
            "Ollama is running, but the local model did not finish within the allowed time.\n\n"
            "DCF Professional now allows up to 10 minutes for local AI generation. "
            "The first request can be slower while the model loads into memory.\n\n"
            "You can warm up the model first with: ollama run gemma3"
        )
    if p.startswith("ollama") and ("10061" in msg or "refused" in msg.lower() or "urlopen" in msg.lower()):
        return (
            "Ollama Local AI is not currently available.\n\n"
            "Your DCF application is working normally. To use Local AI:\n"
            "1. Install Ollama for Windows if it is not installed.\n"
            "2. Start Ollama.\n"
            "3. Download a model, for example: ollama pull gemma3\n"
            "4. Click 'Test AI Connection' and then Generate AI Assumptions.\n\n"
            "You can continue immediately with 'Offline Assumptions' without Ollama."
        )
    if p.startswith("openai"):
        if "api key" in msg.lower() or "authentication" in msg.lower() or "401" in msg:
            return "OpenAI authentication failed. Enter a valid OpenAI API key or set OPENAI_API_KEY."
        return f"OpenAI request failed: {msg}"
    if p.startswith("gemini"):
        if "api key" in msg.lower() or "authentication" in msg.lower() or "401" in msg or "403" in msg:
            return "Gemini authentication failed. Enter a valid Gemini API key or set GEMINI_API_KEY."
        return f"Gemini request failed: {msg}"
    return msg


def ai_assumptions(provider, model, api_key, data, preview=""):
    prompt = build_ai_prompt(data, preview)
    provider = provider.lower()
    if provider.startswith("ollama"):
        ok, health_msg, installed = ollama_health()
        if not ok:
            raise ConnectionError(health_msg)
        chosen = model or "gemma3"
        # Accept either exact model or base model before colon.
        if installed and not any(chosen == m or m.startswith(chosen + ":") or chosen.startswith(m + ":") for m in installed):
            raise ValueError(
                f"Ollama is running, but model '{chosen}' is not installed. "
                f"Installed models: {', '.join(installed) if installed else 'none'}. "
                f"Run: ollama pull {chosen}"
            )
        payload = json.dumps({
            "model": chosen,
            "messages": [{"role":"user","content":prompt}],
            "stream": False,
            "format": "json",
            "keep_alive": "10m",
            "options": {"temperature": 0.2, "num_ctx": 4096}
        }).encode("utf-8")
        req = urllib.request.Request(
            "http://localhost:11434/api/chat",
            data=payload,
            headers={"Content-Type":"application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=600) as resp:
            obj = json.loads(resp.read().decode("utf-8"))
        return _extract_json_object(obj["message"]["content"])

    if provider.startswith("openai"):
        key = api_key or os.environ.get("OPENAI_API_KEY")
        if not key:
            raise ValueError("No OpenAI API key supplied.")
        chosen = model or "gpt-5.6-terra"
        payload = json.dumps({
            "model": chosen,
            "input": prompt
        }).encode("utf-8")
        req = urllib.request.Request(
            "https://api.openai.com/v1/responses",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {key}"
            },
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                obj = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            raise RuntimeError(f"OpenAI HTTP {e.code}: {body[:500]}")
        text = ""
        if isinstance(obj, dict):
            if obj.get("output_text"):
                text = obj["output_text"]
            else:
                # Responses API structured output traversal
                for item in obj.get("output", []):
                    for content in item.get("content", []):
                        if isinstance(content, dict) and content.get("text"):
                            text += content.get("text", "")
        if not text:
            raise ValueError("OpenAI returned no text response.")
        return _extract_json_object(text)

    if provider.startswith("gemini"):
        key = api_key or os.environ.get("GEMINI_API_KEY")
        if not key:
            raise ValueError("No Gemini API key supplied.")
        chosen = model or "gemini-3.7-flash"
        url = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            + urllib.parse.quote(chosen, safe="")
            + ":generateContent?key="
            + urllib.parse.quote(key, safe="")
        )
        payload = json.dumps({
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseMimeType": "application/json"}
        }).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        try:
            with urllib.request.urlopen(req, timeout=180) as resp:
                obj = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "ignore")
            raise RuntimeError(f"Gemini HTTP {e.code}: {body[:500]}")
        try:
            text = obj["candidates"][0]["content"]["parts"][0]["text"]
        except Exception:
            raise ValueError("Gemini returned no text response.")
        return _extract_json_object(text)

    raise ValueError("Unknown AI provider.")

@dataclass
class ValuationResult:
    forecast_sales: list
    forecast_ebitda: list
    forecast_ebit: list
    nopat: list
    da: list
    capex: list
    delta_nwc: list
    fcff: list
    discount_factors: list
    pv_fcff: list
    cost_equity: float
    after_tax_cost_debt: float
    wacc: float
    terminal_growth: float
    terminal_value: float
    pv_terminal_value: float
    enterprise_value: float
    equity_value: float
    value_per_share: float
    bottom_up_beta: float
    scenario_values: dict
    sensitivity: dict

class DCFEngine:
    @staticmethod
    def bottom_up_beta(comps):
        unlevered = []
        for c in comps:
            beta_l = num(c.get("beta"))
            de = num(c.get("de"))
            tax = pct(c.get("tax"))
            if beta_l > 0:
                denom = 1 + (1-tax) * de
                if denom > 0:
                    unlevered.append(beta_l / denom)
        return sum(unlevered) / len(unlevered) if unlevered else 0.0

    @staticmethod
    def calculate(data):
        hist_sales = [num(x) for x in data["historical"]["sales"]]
        base_sales = hist_sales[-1]
        growth = [pct(x) for x in data["forecast"]["growth"]]
        margins = [pct(x) for x in data["forecast"]["ebitda_margin"]]
        tax = pct(data["assumptions"]["tax_rate"])
        da_pct = pct(data["assumptions"]["da_pct"])
        capex_pct = pct(data["assumptions"]["capex_pct"])
        nwc_pct = pct(data["assumptions"]["nwc_increment_pct"])
        terminal_g = pct(data["assumptions"]["terminal_growth"])

        mode = data["company"]["mode"]
        comps = data.get("comparables", [])
        bottom_beta = DCFEngine.bottom_up_beta(comps)
        if mode == "Unlisted":
            target_de = num(data["capital"]["target_de"])
            beta = bottom_beta * (1 + (1-tax) * target_de) if bottom_beta > 0 else num(data["capital"]["beta"])
        else:
            beta = num(data["capital"]["beta"])

        rf = pct(data["capital"]["risk_free"])
        erp = pct(data["capital"]["erp"])
        csrp = pct(data["capital"]["csrp"])
        cost_equity = rf + beta * erp + csrp
        pre_tax_kd = pct(data["capital"]["cost_debt"])
        after_tax_kd = pre_tax_kd * (1-tax)

        debt_weight = pct(data["capital"]["debt_weight"])
        debt_weight = min(max(debt_weight, 0), 1)
        equity_weight = 1 - debt_weight
        wacc = cost_equity * equity_weight + after_tax_kd * debt_weight

        if wacc <= terminal_g:
            raise ValueError("WACC must be greater than terminal growth rate.")

        sales, ebitda, ebit, nopat, da, capex, d_nwc, fcff = [], [], [], [], [], [], [], []
        prev_sales = base_sales
        for i in range(5):
            s = prev_sales * (1 + growth[i])
            e = s * margins[i]
            dep = s * da_pct
            eb = e - dep
            npat = eb * (1-tax)
            cx = s * capex_pct
            dn = max(0.0, (s - prev_sales) * nwc_pct)
            f = npat + dep - cx - dn
            sales.append(s); ebitda.append(e); da.append(dep); ebit.append(eb)
            nopat.append(npat); capex.append(cx); d_nwc.append(dn); fcff.append(f)
            prev_sales = s

        dfs = [1 / ((1+wacc)**(i+1)) for i in range(5)]
        pv_fcff = [fcff[i]*dfs[i] for i in range(5)]
        tv = fcff[-1] * (1+terminal_g) / (wacc-terminal_g)
        pv_tv = tv * dfs[-1]
        ev = sum(pv_fcff) + pv_tv

        cash = num(data["bridge"]["cash"])
        investments = num(data["bridge"]["investments"])
        debt = num(data["bridge"]["debt"])
        minorities = num(data["bridge"]["minority_interest"])
        other_claims = num(data["bridge"]["other_claims"])
        other_assets = num(data["bridge"]["other_assets"])
        eq = ev - debt - minorities - other_claims + cash + investments + other_assets
        shares = num(data["company"]["shares"])
        value_per_share = eq / shares if shares > 0 else eq

        sensitivity = {}
        wacc_offsets = [-0.02, -0.01, 0, 0.01, 0.02]
        g_offsets = [-0.01, -0.005, 0, 0.005, 0.01]
        for wo in wacc_offsets:
            rw = wacc + wo
            row = {}
            for go in g_offsets:
                rg = terminal_g + go
                if rw <= rg or rw <= 0:
                    val = None
                else:
                    t = fcff[-1]*(1+rg)/(rw-rg)
                    df = [1/((1+rw)**(i+1)) for i in range(5)]
                    re = sum(fcff[i]*df[i] for i in range(5)) + t*df[-1]
                    req = re - debt - minorities - other_claims + cash + investments + other_assets
                    val = req/shares if shares > 0 else req
                row[round(rg,6)] = val
            sensitivity[round(rw,6)] = row

        scenarios = {}
        scenario_inputs = data.get("scenarios", {})
        for name in ["Bear","Base","Bull"]:
            sc = scenario_inputs.get(name, {})
            g_adj = pct(sc.get("growth_adj", 0))
            m_adj = pct(sc.get("margin_adj", 0))
            w_adj = pct(sc.get("wacc_adj", 0))
            tg_adj = pct(sc.get("terminal_growth_adj", 0))
            rw = wacc + w_adj
            rg = terminal_g + tg_adj
            p_sales = base_sales
            s_fcff = []
            for i in range(5):
                gs = max(-0.99, growth[i] + g_adj)
                ms = max(0, margins[i] + m_adj)
                ss = p_sales*(1+gs)
                ee = ss*ms
                dd = ss*da_pct
                eb = ee-dd
                nn = eb*(1-tax)
                cc = ss*capex_pct
                dn = max(0, (ss-p_sales)*nwc_pct)
                s_fcff.append(nn+dd-cc-dn)
                p_sales = ss
            if rw <= rg:
                scenarios[name] = None
            else:
                df = [1/((1+rw)**(i+1)) for i in range(5)]
                tvs = s_fcff[-1]*(1+rg)/(rw-rg)
                sev = sum(s_fcff[i]*df[i] for i in range(5)) + tvs*df[-1]
                seq = sev - debt - minorities - other_claims + cash + investments + other_assets
                scenarios[name] = seq/shares if shares > 0 else seq

        return ValuationResult(
            forecast_sales=sales, forecast_ebitda=ebitda, forecast_ebit=ebit,
            nopat=nopat, da=da, capex=capex, delta_nwc=d_nwc, fcff=fcff,
            discount_factors=dfs, pv_fcff=pv_fcff, cost_equity=cost_equity,
            after_tax_cost_debt=after_tax_kd, wacc=wacc, terminal_growth=terminal_g,
            terminal_value=tv, pv_terminal_value=pv_tv, enterprise_value=ev,
            equity_value=eq, value_per_share=value_per_share,
            bottom_up_beta=bottom_beta, scenario_values=scenarios,
            sensitivity=sensitivity
        )

class DCFApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(f"{APP_NAME} v{APP_VERSION}")
        self.geometry("1320x820")
        self.minsize(1100,700)
        self.configure(bg="#eef3f8")
        self.project_path = None
        self.result = None
        self.entries = {}
        self.hist_entries = {}
        self.fcst_entries = {}
        self.comp_tree = None
        self.imported_preview = ""
        self.imported_file = ""
        self.sensitivity_tree = None
        self.scenario_tree = None
        self._style()
        self._build_ui()
        self._defaults()
        try:
            ok,msg,models=ollama_health()
            self.after(800, lambda: self._log_import("Startup AI status: "+msg))
            if ok and hasattr(self,"ai_model_box") and models:
                self.ai_model_box["values"]=models
                self.ai_model.set(models[0])
        except Exception:
            pass

    def _style(self):
        style = ttk.Style(self)
        try: style.theme_use("clam")
        except: pass
        style.configure("TNotebook", background="#eef3f8", borderwidth=0)
        style.configure("TNotebook.Tab", padding=[14,8], font=("Segoe UI",10,"bold"))
        style.map("TNotebook.Tab", background=[("selected","#1f4e78")], foreground=[("selected","white")])
        style.configure("TFrame", background="#eef3f8")
        style.configure("Card.TFrame", background="white")
        style.configure("Title.TLabel", background="#17365d", foreground="white", font=("Segoe UI",18,"bold"), padding=12)
        style.configure("Section.TLabel", background="#1f4e78", foreground="white", font=("Segoe UI",11,"bold"), padding=6)
        style.configure("TLabel", background="#eef3f8", font=("Segoe UI",10))
        style.configure("Card.TLabel", background="white", font=("Segoe UI",10))
        style.configure("KPI.TLabel", background="white", foreground="#17365d", font=("Segoe UI",16,"bold"))
        style.configure("Accent.TButton", font=("Segoe UI",10,"bold"))
        style.configure("Treeview", rowheight=26, font=("Segoe UI",9))
        style.configure("Treeview.Heading", font=("Segoe UI",9,"bold"))

    def _build_ui(self):
        ttk.Label(self, text="📊 DCF VALUATION PROFESSIONAL", style="Title.TLabel").pack(fill="x")
        toolbar = ttk.Frame(self); toolbar.pack(fill="x", padx=8, pady=6)
        for txt,cmd in [("📁 Open Project",self.open_project),("💾 Save Project",self.save_project),
                        ("🧮 Calculate",self.calculate),("📦 Export Pack",self.export_pack),("❓ Help",self.show_help)]:
            ttk.Button(toolbar,text=txt,command=cmd,style="Accent.TButton").pack(side="left",padx=4)
        self.status = tk.StringVar(value="Ready. All calculations are performed locally.")
        ttk.Label(toolbar,textvariable=self.status).pack(side="right",padx=8)

        self.nb = ttk.Notebook(self); self.nb.pack(fill="both",expand=True,padx=8,pady=(0,8))
        self.tabs = {}
        for name in ["Company","Import & AI","Historical","Forecast","Cost of Capital","Comparables","Bridge","Scenarios","Results","Sensitivity"]:
            f=ttk.Frame(self.nb); self.nb.add(f,text=name); self.tabs[name]=f

        self._company_tab(); self._import_ai_tab(); self._historical_tab(); self._forecast_tab()
        self._capital_tab(); self._comparables_tab(); self._bridge_tab()
        self._scenarios_tab(); self._results_tab(); self._sensitivity_tab()

    def _entry(self, parent, key, row, col, label, width=18, default="", suffix=None):
        ttk.Label(parent,text=label,style="Card.TLabel").grid(row=row,column=col,sticky="w",padx=8,pady=6)
        v=tk.StringVar(value=str(default))
        e=ttk.Entry(parent,textvariable=v,width=width)
        e.grid(row=row,column=col+1,sticky="ew",padx=8,pady=6)
        if suffix: ttk.Label(parent,text=suffix,style="Card.TLabel").grid(row=row,column=col+2,sticky="w")
        self.entries[key]=v
        return v

    def _card(self, tab, title, row=0, col=0, colspan=1):
        f=ttk.Frame(tab,style="Card.TFrame",padding=10)
        f.grid(row=row,column=col,columnspan=colspan,sticky="nsew",padx=8,pady=8)
        ttk.Label(f,text=title,style="Section.TLabel").grid(row=0,column=0,columnspan=8,sticky="ew",pady=(0,8))
        return f

    def _company_tab(self):
        t=self.tabs["Company"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Company & Valuation Setup")
        self._entry(f,"company_name",1,0,"Company Name",32)
        self._entry(f,"industry",2,0,"Industry",32)
        self._entry(f,"valuation_date",3,0,"Valuation Date",18,datetime.now().strftime("%d-%m-%Y"))
        ttk.Label(f,text="Company Type",style="Card.TLabel").grid(row=4,column=0,sticky="w",padx=8,pady=6)
        self.mode=tk.StringVar(value="Listed")
        ttk.Combobox(f,textvariable=self.mode,values=["Listed","Unlisted"],state="readonly",width=16).grid(row=4,column=1,sticky="w",padx=8)
        self._entry(f,"shares",5,0,"Shares Outstanding / Units",18,"100")
        self._entry(f,"currency",6,0,"Currency / Units",18,"₹ Crores")
        ttk.Label(f,text="For a whole-company unlisted valuation, shares may be entered as 1.",style="Card.TLabel").grid(row=7,column=0,columnspan=3,sticky="w",padx=8,pady=8)


    def _import_ai_tab(self):
        t=self.tabs["Import & AI"]; t.columnconfigure(0,weight=1); t.rowconfigure(1,weight=1)
        f=self._card(t,"Financial Statement Import & AI-Assisted Assumptions")
        ttk.Label(f,text="Input File",style="Card.TLabel").grid(row=1,column=0,sticky="w",padx=8,pady=6)
        self.import_file_var=tk.StringVar(value="")
        ttk.Entry(f,textvariable=self.import_file_var,width=70,state="readonly").grid(row=1,column=1,columnspan=4,sticky="ew",padx=8)
        ttk.Button(f,text="📥 Import Excel / PDF",command=self.import_financial_file).grid(row=1,column=5,padx=6)
        ttk.Button(f,text="🧠 Offline Assumptions",command=self.apply_offline_assumptions).grid(row=2,column=0,padx=6,pady=8,sticky="w")

        ttk.Label(f,text="AI Provider",style="Card.TLabel").grid(row=2,column=1,sticky="e",padx=4)
        self.ai_provider=tk.StringVar(value="Ollama (Local Offline)")
        self.ai_provider_box=ttk.Combobox(
            f,textvariable=self.ai_provider,
            values=["Ollama (Local Offline)","OpenAI (Online)","Gemini (Online)"],
            state="readonly",width=24
        )
        self.ai_provider_box.grid(row=2,column=2,padx=4)
        self.ai_provider_box.bind("<<ComboboxSelected>>", self.on_ai_provider_changed)
        ttk.Label(f,text="Model",style="Card.TLabel").grid(row=2,column=3,sticky="e",padx=4)
        self.ai_model=tk.StringVar(value="gemma3")
        self.ai_model_box=ttk.Combobox(f,textvariable=self.ai_model,width=24)
        self.ai_model_box["values"]=["gemma3"]
        self.ai_model_box.grid(row=2,column=4,padx=4)
        ai_buttons=ttk.Frame(f,style="Card.TFrame")
        ai_buttons.grid(row=2,column=5,padx=6,sticky="w")
        ttk.Button(ai_buttons,text="🔌 Test AI Connection",command=self.test_ai_connection).pack(side="left",padx=(0,4))
        ttk.Button(ai_buttons,text="✨ Generate AI Assumptions",command=self.generate_ai_assumptions).pack(side="left")

        ttk.Label(f,text="API Key (online providers only)",style="Card.TLabel").grid(row=3,column=0,sticky="w",padx=8,pady=6)
        self.ai_key=tk.StringVar(value="")
        ttk.Entry(f,textvariable=self.ai_key,width=60,show="•").grid(row=3,column=1,columnspan=3,sticky="ew",padx=8)
        ttk.Label(f,text="Keys are kept in memory only; environment variables OPENAI_API_KEY / GEMINI_API_KEY are also supported.",style="Card.TLabel").grid(row=3,column=4,columnspan=2,sticky="w",padx=4)

        ttk.Label(f,text="Import / AI Log",style="Card.TLabel",font=("Segoe UI",10,"bold")).grid(row=4,column=0,columnspan=6,sticky="w",padx=8,pady=(10,4))
        self.import_log=tk.Text(f,height=19,wrap="word",font=("Consolas",9))
        self.import_log.grid(row=5,column=0,columnspan=6,sticky="nsew",padx=8,pady=6)
        f.rowconfigure(5,weight=1)
        for c in range(6): f.columnconfigure(c,weight=1 if c in (1,4) else 0)

        ttk.Label(f,text="Privacy control: Excel/PDF parsing is local. Online AI receives extracted text/data only when you explicitly click Generate AI Assumptions.",style="Card.TLabel").grid(row=6,column=0,columnspan=6,sticky="w",padx=8,pady=6)

    def _log_import(self,msg):
        try:
            self.import_log.insert("end",msg.rstrip()+"\n")
            self.import_log.see("end")
        except Exception:
            pass


    def review_import_mapping(self,mapped,provenance,confidence,warnings):
        win=tk.Toplevel(self); win.title("Review Imported Financial Mapping"); win.geometry("1180x560")
        win.transient(self); win.grab_set()
        ttk.Label(win,text="Review Imported Financials Before Posting",font=("Segoe UI",14,"bold")).pack(pady=(12,4))
        ttk.Label(win,text="Double-click any row to toggle YES/NO. Rejected mappings default to NO.").pack()
        cols=("use","metric","confidence","fy4","fy3","fy2","fy1","fy0","source")
        tree=ttk.Treeview(win,columns=cols,show="headings",height=14)
        heads={"use":"Use","metric":"Metric","confidence":"Confidence","fy4":"FY-4","fy3":"FY-3","fy2":"FY-2","fy1":"FY-1","fy0":"FY0","source":"Source"}
        widths={"use":55,"metric":120,"confidence":80,"fy4":90,"fy3":90,"fy2":90,"fy1":90,"fy0":90,"source":390}
        for c in cols:
            tree.heading(c,text=heads[c]); tree.column(c,width=widths[c],anchor="w" if c=="source" else "center")
        tree.pack(fill="both",expand=True,padx=10,pady=8)
        for m in ["sales","ebitda","da","ebit","capex","nwc"]:
            if m in mapped:
                conf=confidence.get(m,"Low"); use="NO" if conf=="Reject" else "YES"
                tree.insert("","end",values=(use,m,conf,*[f"{v:,.2f}" for v in mapped[m]],provenance.get(m,"")))
        def toggle(event=None):
            sel=tree.selection()
            if not sel:return
            iid=sel[0]; vals=list(tree.item(iid,"values")); vals[0]="NO" if vals[0]=="YES" else "YES"; tree.item(iid,values=vals)
        tree.bind("<Double-1>",toggle)
        warn="\n".join("• "+w for w in warnings) if warnings else "No critical warnings."
        ttk.Label(win,text=warn,foreground="#8B0000",wraplength=1120,justify="left").pack(fill="x",padx=12,pady=6)
        result={"accepted":None}
        def accept():
            accepted={}
            for iid in tree.get_children():
                vals=tree.item(iid,"values")
                if vals[0]=="YES":accepted[vals[1]]=mapped[vals[1]]
            result["accepted"]=accepted; win.destroy()
        bf=ttk.Frame(win); bf.pack(pady=8)
        ttk.Button(bf,text="Accept Selected",command=accept).pack(side="left",padx=5)
        ttk.Button(bf,text="Cancel Import",command=win.destroy).pack(side="left",padx=5)
        self.wait_window(win)
        return result["accepted"]

    def import_financial_file(self):
        path=filedialog.askopenfilename(title="Select financial statements",
            filetypes=[("Financial files","*.xlsx *.xlsm *.pdf"),("Excel","*.xlsx *.xlsm"),("PDF","*.pdf")])
        if not path:return
        self.import_file_var.set(path); self.imported_file=path; self._log_import(f"Importing: {path}")
        try:
            ext=Path(path).suffix.lower()
            if ext in (".xlsx",".xlsm"):
                mapped,preview,provenance,warnings,confidence=extract_financials_from_excel(path)
            elif ext==".pdf":
                mapped,preview,provenance,warnings,confidence=extract_financials_from_pdf(path)
            else:raise ValueError("Unsupported file format.")
            self.imported_preview=preview
            if not mapped:
                self._log_import("No reliable financial metrics found."); return
            self._log_import("Candidate financial mappings:")
            for k,v in mapped.items():
                self._log_import(f"  {k}: {v}")
                self._log_import(f"     confidence: {confidence.get(k,'Low')}")
                self._log_import(f"     source: {provenance.get(k,'unknown')}")
            for w in warnings:self._log_import("WARNING: "+w)
            accepted=self.review_import_mapping(mapped,provenance,confidence,warnings)
            if accepted is None:
                self._log_import("Import cancelled by user."); return
            for metric,vals in accepted.items():
                if metric in self.hist_entries:
                    for i,v in enumerate(vals[-5:]):self.hist_entries[metric][i].set(f"{v:.2f}")
            self._log_import("Accepted mappings posted to Historical: "+", ".join(accepted.keys()))
            self.nb.select(self.tabs["Historical"])
        except Exception as e:
            self._log_import(f"ERROR: {e}"); messagebox.showerror("Import Financials",str(e))


    def _apply_ai_result(self,res):
        required=["growth","ebitda_margin","tax_rate","da_pct","capex_pct","nwc_increment_pct","terminal_growth"]
        missing=[x for x in required if x not in res]
        if missing: raise ValueError("AI response missing: "+", ".join(missing))
        for i,v in enumerate(res["growth"][:5]): self.fcst_entries["growth"][i].set(str(round(num(v),2)))
        for i,v in enumerate(res["ebitda_margin"][:5]): self.fcst_entries["ebitda_margin"][i].set(str(round(num(v),2)))
        for k in ["tax_rate","da_pct","capex_pct","nwc_increment_pct","terminal_growth"]:
            self.entries[k].set(str(round(num(res[k]),2)))
        self._log_import("Assumptions applied:")
        self._log_import(json.dumps(res,indent=2))
        self.nb.select(self.tabs["Forecast"])

    def apply_offline_assumptions(self):
        try:
            res=offline_assumption_engine(self.gather())
            self._apply_ai_result(res)
            messagebox.showinfo("Offline Assumptions","Historical trends were analysed locally and the proposed assumptions were applied. Please review them.")
        except Exception as e:
            messagebox.showerror("Offline Assumptions",str(e))


    def on_ai_provider_changed(self, event=None):
        provider=self.ai_provider.get()
        if provider.startswith("Ollama"):
            ok,msg,models=ollama_health()
            if models:
                self.ai_model_box["values"]=models
                if self.ai_model.get() not in models:
                    self.ai_model.set(models[0])
            else:
                self.ai_model_box["values"]=["gemma3","llama3.2","qwen3"]
                self.ai_model.set("gemma3")
            self._log_import("Ollama status: "+msg)
        elif provider.startswith("OpenAI"):
            self.ai_model_box["values"]=["gpt-5.6-terra","gpt-5.6-sol","gpt-5.6-luna"]
            self.ai_model.set("gpt-5.6-terra")
            self._log_import("OpenAI selected. Enter API key or set OPENAI_API_KEY.")
        elif provider.startswith("Gemini"):
            self.ai_model_box["values"]=["gemini-3.7-flash","gemini-3.6-flash","gemini-3.5-flash"]
            self.ai_model.set("gemini-3.7-flash")
            self._log_import("Gemini selected. Enter API key or set GEMINI_API_KEY.")

    def test_ai_connection(self):
        provider=self.ai_provider.get()
        try:
            if provider.startswith("Ollama"):
                ok,msg,models=ollama_health()
                if not ok:
                    # If installed, offer to start service automatically.
                    if shutil.which("ollama"):
                        start=messagebox.askyesno(
                            "Ollama Not Running",
                            msg+"\\n\\nOllama appears to be installed. Would you like DCF Professional to try starting the local Ollama service now?"
                        )
                        if start:
                            ok2,msg2=try_start_ollama()
                            if ok2:
                                ok,msg,models=ollama_health()
                            else:
                                msg=msg2
                if ok:
                    if models:
                        self.ai_model_box["values"]=models
                        if self.ai_model.get() not in models:
                            self.ai_model.set(models[0])
                    messagebox.showinfo("AI Connection",msg+"\\n\\nInstalled models: "+(", ".join(models) if models else "None"))
                    self._log_import("AI TEST OK: "+msg+" Models: "+(", ".join(models) if models else "none"))
                else:
                    messagebox.showwarning("Ollama Local AI",msg+"\\n\\nYou can still use Offline Assumptions without Ollama.")
                    self._log_import("AI TEST FAILED: "+msg)
                return

            if provider.startswith("OpenAI"):
                key=self.ai_key.get().strip() or os.environ.get("OPENAI_API_KEY")
                if not key:
                    raise ValueError("No OpenAI API key supplied.")
                req=urllib.request.Request(
                    "https://api.openai.com/v1/models",
                    headers={"Authorization":f"Bearer {key}"},
                    method="GET"
                )
                with urllib.request.urlopen(req,timeout=20) as resp:
                    if resp.status != 200:
                        raise ValueError("OpenAI authentication test failed.")
                messagebox.showinfo("AI Connection","OpenAI connection and API authentication succeeded.")
                self._log_import("AI TEST OK: OpenAI authenticated.")
                return

            if provider.startswith("Gemini"):
                key=self.ai_key.get().strip() or os.environ.get("GEMINI_API_KEY")
                if not key:
                    raise ValueError("No Gemini API key supplied.")
                chosen=self.ai_model.get() or "gemini-3.7-flash"
                url=(
                    "https://generativelanguage.googleapis.com/v1beta/models/"
                    + urllib.parse.quote(chosen,safe="")
                    + ":generateContent?key="
                    + urllib.parse.quote(key,safe="")
                )
                payload=json.dumps({
                    "contents":[{"parts":[{"text":"Reply only: OK"}]}]
                }).encode("utf-8")
                req=urllib.request.Request(
                    url,data=payload,headers={"Content-Type":"application/json"},method="POST"
                )
                with urllib.request.urlopen(req,timeout=30) as resp:
                    if resp.status != 200:
                        raise ValueError("Gemini authentication test failed.")
                messagebox.showinfo("AI Connection","Gemini connection and API authentication succeeded.")
                self._log_import("AI TEST OK: Gemini authenticated.")
                return
        except Exception as e:
            friendly=friendly_ai_error(provider,e)
            messagebox.showerror("AI Connection Test",friendly)
            self._log_import("AI TEST FAILED: "+friendly.replace("\\n"," "))


    def generate_ai_assumptions(self):
        provider=self.ai_provider.get()
        model=self.ai_model.get().strip() or provider_default_model(provider)
        self.ai_model.set(model)
        if provider.startswith(("OpenAI","Gemini")):
            ok=messagebox.askyesno(
                "Online AI Privacy Notice",
                "This will send the extracted financial data and document text shown by this application to the selected online AI provider. The original file itself is not uploaded by this function.\n\nContinue?"
            )
            if not ok:return
        if provider.startswith("Ollama"):
            ok,msg,models=ollama_health()
            if not ok:
                messagebox.showwarning("Ollama Local AI",msg)
                return
            if not models:
                messagebox.showwarning("Ollama Local AI",f"Ollama is running, but no local model is installed.\n\nRun:\nollama pull {model or 'gemma3'}")
                return

        progress=tk.Toplevel(self)
        progress.title("Generating AI Assumptions")
        progress.geometry("520x200")
        progress.resizable(False,False)
        progress.transient(self); progress.grab_set()
        ttk.Label(progress,text="🧠 AI analysis in progress",font=("Segoe UI",14,"bold")).pack(pady=(22,8))
        ttk.Label(progress,text=f"Provider: {provider}\nModel: {model}\n\nLocal Ollama analysis may take several minutes on the first run while the model loads into memory.",justify="center",wraplength=470).pack(padx=20)
        pb=ttk.Progressbar(progress,mode="indeterminate",length=400); pb.pack(pady=16); pb.start(12)
        self.status.set(f"Generating assumptions with {provider}...")
        self.update_idletasks()
        holder={"result":None,"error":None}
        data_snapshot=self.gather()
        preview_snapshot=self.imported_preview
        api_key_snapshot=self.ai_key.get().strip()

        def worker():
            try:
                holder["result"]=ai_assumptions(provider,model,api_key_snapshot,data_snapshot,preview_snapshot)
            except Exception as e:
                holder["error"]=e
            self.after(100,finish)

        def finish():
            try:
                pb.stop(); progress.grab_release(); progress.destroy()
            except Exception:
                pass
            if holder["error"] is not None:
                friendly=friendly_ai_error(provider,holder["error"])
                self._log_import("AI ERROR: "+friendly.replace("\n"," "))
                messagebox.showerror("AI Assumptions",friendly)
                self.status.set("AI assumption generation failed.")
                return
            try:
                self._apply_ai_result(holder["result"])
                messagebox.showinfo("AI Assumptions","AI-generated assumptions were applied. Review all assumptions before using the valuation.")
                self.status.set("AI assumptions generated.")
            except Exception as e:
                messagebox.showerror("AI Assumptions",str(e))
                self.status.set("AI assumption generation failed.")

        threading.Thread(target=worker,daemon=True).start()


    def _historical_tab(self):
        t=self.tabs["Historical"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Historical Financials - 5 Years")
        headers=["Metric"]+YEARS_HIST
        for c,h in enumerate(headers):
            ttk.Label(f,text=h,style="Card.TLabel",font=("Segoe UI",10,"bold")).grid(row=1,column=c,padx=6,pady=5)
        metrics=[("sales","Revenue / Net Sales"),("ebitda","EBITDA"),("da","D&A"),("ebit","EBIT"),("capex","Capital Expenditure"),("nwc","Net Working Capital")]
        for r,(key,label) in enumerate(metrics,start=2):
            ttk.Label(f,text=label,style="Card.TLabel").grid(row=r,column=0,sticky="w",padx=6,pady=4)
            self.hist_entries[key]=[]
            for c in range(5):
                v=tk.StringVar(value="0")
                ttk.Entry(f,textvariable=v,width=15).grid(row=r,column=c+1,padx=4,pady=4)
                self.hist_entries[key].append(v)
        ttk.Label(f,text="Historical data supports analysis and provides the FY0 revenue base for projection.",style="Card.TLabel").grid(row=9,column=0,columnspan=6,sticky="w",padx=6,pady=8)

    def _forecast_tab(self):
        t=self.tabs["Forecast"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Explicit Forecast Assumptions")
        for c,h in enumerate(["Assumption"]+YEARS_FCST):
            ttk.Label(f,text=h,style="Card.TLabel",font=("Segoe UI",10,"bold")).grid(row=1,column=c,padx=6,pady=5)
        for r,(key,label,defaults) in enumerate([
            ("growth","Revenue Growth %",[10,9,8.5,8,7.5]),
            ("ebitda_margin","EBITDA Margin %",[18,18.5,19,19.5,20])
        ],start=2):
            ttk.Label(f,text=label,style="Card.TLabel").grid(row=r,column=0,sticky="w",padx=6,pady=5)
            self.fcst_entries[key]=[]
            for c,d in enumerate(defaults):
                v=tk.StringVar(value=str(d)); ttk.Entry(f,textvariable=v,width=14).grid(row=r,column=c+1,padx=4,pady=4)
                self.fcst_entries[key].append(v)
        self._entry(f,"tax_rate",5,0,"Normalized Tax Rate",15,"25","%")
        self._entry(f,"da_pct",6,0,"D&A as % Revenue",15,"3","%")
        self._entry(f,"capex_pct",7,0,"Capex as % Revenue",15,"4","%")
        self._entry(f,"nwc_increment_pct",8,0,"ΔNWC as % of Incremental Revenue",15,"8","%")
        self._entry(f,"terminal_growth",9,0,"Terminal Growth Rate",15,"5","%")

    def _capital_tab(self):
        t=self.tabs["Cost of Capital"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Cost of Capital Parameters")
        self._entry(f,"risk_free",1,0,"Risk-Free Rate",16,"7","%")
        self._entry(f,"erp",2,0,"Equity Risk Premium",16,"5.5","%")
        self._entry(f,"beta",3,0,"Levered Beta (Listed / fallback)",16,"1.0")
        self._entry(f,"csrp",4,0,"Company-Specific / Size Risk Premium",16,"0","%")
        self._entry(f,"cost_debt",5,0,"Pre-Tax Cost of Debt",16,"9","%")
        self._entry(f,"debt_weight",6,0,"Debt Weight in Capital",16,"10","%")
        self._entry(f,"target_de",7,0,"Target D/E for Unlisted Relevering",16,"0.20")
        ttk.Label(f,text="Unlisted mode: if comparables are entered, the app un-levers peer betas, averages them, then re-levers to the target D/E.",style="Card.TLabel").grid(row=8,column=0,columnspan=3,sticky="w",padx=8,pady=8)

    def _comparables_tab(self):
        t=self.tabs["Comparables"]; t.columnconfigure(0,weight=1); t.rowconfigure(0,weight=1)
        f=self._card(t,"Comparable Listed Companies - for Bottom-Up Beta")
        cols=("company","beta","de","tax")
        self.comp_tree=ttk.Treeview(f,columns=cols,show="headings",height=12)
        heads={"company":"Comparable Company","beta":"Levered Beta","de":"Debt / Equity","tax":"Tax Rate %"}
        widths={"company":260,"beta":120,"de":120,"tax":120}
        for c in cols: self.comp_tree.heading(c,text=heads[c]); self.comp_tree.column(c,width=widths[c],anchor="center")
        self.comp_tree.grid(row=1,column=0,columnspan=6,sticky="nsew",padx=5,pady=5)
        f.rowconfigure(1,weight=1); f.columnconfigure(0,weight=1)
        ttk.Button(f,text="➕ Add Comparable",command=self.add_comparable).grid(row=2,column=0,sticky="w",padx=5,pady=5)
        ttk.Button(f,text="✏ Edit Selected",command=self.edit_comparable).grid(row=2,column=1,sticky="w",padx=5)
        ttk.Button(f,text="🗑 Delete Selected",command=lambda:[self.comp_tree.delete(x) for x in self.comp_tree.selection()]).grid(row=2,column=2,sticky="w",padx=5)

    def _bridge_tab(self):
        t=self.tabs["Bridge"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Enterprise Value to Equity Value Bridge")
        self._entry(f,"debt",1,0,"Debt + Lease Liabilities",18,"0")
        self._entry(f,"cash",2,0,"Cash & Cash Equivalents",18,"0")
        self._entry(f,"investments",3,0,"Non-Operating Investments",18,"0")
        self._entry(f,"minority_interest",4,0,"Minority / NCI",18,"0")
        self._entry(f,"other_claims",5,0,"Other Non-Equity Claims",18,"0")
        self._entry(f,"other_assets",6,0,"Other Non-Operating Assets",18,"0")
        ttk.Label(f,text="Use note-level adjustments where material. Avoid double counting cash/investments already embedded in operating cash flows.",style="Card.TLabel").grid(row=7,column=0,columnspan=3,sticky="w",padx=8,pady=8)

    def _scenarios_tab(self):
        t=self.tabs["Scenarios"]; t.columnconfigure(0,weight=1)
        f=self._card(t,"Scenario Adjustments vs Base")
        for c,h in enumerate(["Scenario","Revenue Growth Adj %","EBITDA Margin Adj %","WACC Adj %","Terminal Growth Adj %"]):
            ttk.Label(f,text=h,style="Card.TLabel",font=("Segoe UI",10,"bold")).grid(row=1,column=c,padx=6,pady=5)
        self.scenario_vars={}
        defs={"Bear":(-2,-1.5,1,-0.5),"Base":(0,0,0,0),"Bull":(2,1.5,-1,0.5)}
        for r,name in enumerate(["Bear","Base","Bull"],start=2):
            ttk.Label(f,text=name,style="Card.TLabel").grid(row=r,column=0,sticky="w",padx=6)
            self.scenario_vars[name]={}
            for c,(key,val) in enumerate(zip(["growth_adj","margin_adj","wacc_adj","terminal_growth_adj"],defs[name]),start=1):
                v=tk.StringVar(value=str(val)); ttk.Entry(f,textvariable=v,width=16).grid(row=r,column=c,padx=4,pady=5)
                self.scenario_vars[name][key]=v

    def _results_tab(self):
        t=self.tabs["Results"]; t.columnconfigure(0,weight=1); t.columnconfigure(1,weight=1)
        left=self._card(t,"Valuation Summary",0,0); right=self._card(t,"FCFF Forecast",0,1)
        self.kpis={}
        for r,(key,label) in enumerate([("cost_equity","Cost of Equity"),("wacc","WACC"),("ev","Enterprise Value"),
                                         ("eq","Equity Value"),("vps","Intrinsic Value / Share"),("beta","Bottom-Up Beta")],start=1):
            ttk.Label(left,text=label,style="Card.TLabel").grid(row=r,column=0,sticky="w",padx=8,pady=9)
            v=tk.StringVar(value="-"); ttk.Label(left,textvariable=v,style="KPI.TLabel").grid(row=r,column=1,sticky="e",padx=8)
            self.kpis[key]=v
        self.fcff_tree=ttk.Treeview(right,columns=("yr","sales","ebitda","fcff","pv"),show="headings",height=10)
        for c,h,w in [("yr","Year",80),("sales","Sales",120),("ebitda","EBITDA",120),("fcff","FCFF",120),("pv","PV FCFF",120)]:
            self.fcff_tree.heading(c,text=h); self.fcff_tree.column(c,width=w,anchor="e" if c!="yr" else "center")
        self.fcff_tree.grid(row=1,column=0,sticky="nsew")
        right.rowconfigure(1,weight=1); right.columnconfigure(0,weight=1)
        bottom=self._card(t,"Scenario Values",1,0,2)
        self.scenario_tree=ttk.Treeview(bottom,columns=("scenario","value"),show="headings",height=4)
        self.scenario_tree.heading("scenario",text="Scenario"); self.scenario_tree.heading("value",text="Intrinsic Value / Share")
        self.scenario_tree.column("scenario",width=180,anchor="center"); self.scenario_tree.column("value",width=220,anchor="e")
        self.scenario_tree.grid(row=1,column=0,sticky="w")

    def _sensitivity_tab(self):
        t=self.tabs["Sensitivity"]; t.columnconfigure(0,weight=1); t.rowconfigure(0,weight=1)
        f=self._card(t,"WACC × Terminal Growth Sensitivity")
        self.sensitivity_tree=ttk.Treeview(f,show="headings",height=14)
        self.sensitivity_tree.grid(row=1,column=0,sticky="nsew",padx=5,pady=5)
        f.columnconfigure(0,weight=1); f.rowconfigure(1,weight=1)

    def _defaults(self):
        self.entries["company_name"].set("Sample Company")
        self.entries["industry"].set("Manufacturing / Consumer")
        self.hist_entries["sales"][-1].set("1000")
        self.hist_entries["ebitda"][-1].set("180")
        self.hist_entries["da"][-1].set("30")
        self.hist_entries["ebit"][-1].set("150")
        self.hist_entries["capex"][-1].set("40")
        self.hist_entries["nwc"][-1].set("120")

    def add_comparable(self):
        self._comp_dialog()

    def edit_comparable(self):
        sel=self.comp_tree.selection()
        if not sel: return
        vals=self.comp_tree.item(sel[0],"values")
        self._comp_dialog(sel[0],vals)

    def _comp_dialog(self,item=None,values=None):
        win=tk.Toplevel(self); win.title("Comparable Company"); win.transient(self); win.grab_set()
        labels=["Company","Levered Beta","Debt / Equity","Tax Rate %"]
        vars=[]
        for i,l in enumerate(labels):
            ttk.Label(win,text=l).grid(row=i,column=0,padx=8,pady=6,sticky="w")
            v=tk.StringVar(value=values[i] if values else ("25" if i==3 else ""))
            ttk.Entry(win,textvariable=v,width=25).grid(row=i,column=1,padx=8,pady=6); vars.append(v)
        def save():
            vals=[v.get() for v in vars]
            if item: self.comp_tree.item(item,values=vals)
            else: self.comp_tree.insert("", "end", values=vals)
            win.destroy()
        ttk.Button(win,text="Save",command=save).grid(row=5,column=0,columnspan=2,pady=10)

    def gather(self):
        return {
            "app_version":APP_VERSION,
            "import_info":{"source_file":self.imported_file,"preview_excerpt":self.imported_preview[:5000]},
            "company":{"name":self.entries["company_name"].get(),"industry":self.entries["industry"].get(),
                       "valuation_date":self.entries["valuation_date"].get(),"mode":self.mode.get(),
                       "shares":self.entries["shares"].get(),"currency":self.entries["currency"].get()},
            "historical":{k:[v.get() for v in arr] for k,arr in self.hist_entries.items()},
            "forecast":{k:[v.get() for v in arr] for k,arr in self.fcst_entries.items()},
            "assumptions":{"tax_rate":self.entries["tax_rate"].get(),"da_pct":self.entries["da_pct"].get(),
                           "capex_pct":self.entries["capex_pct"].get(),"nwc_increment_pct":self.entries["nwc_increment_pct"].get(),
                           "terminal_growth":self.entries["terminal_growth"].get()},
            "capital":{"risk_free":self.entries["risk_free"].get(),"erp":self.entries["erp"].get(),
                       "beta":self.entries["beta"].get(),"csrp":self.entries["csrp"].get(),
                       "cost_debt":self.entries["cost_debt"].get(),"debt_weight":self.entries["debt_weight"].get(),
                       "target_de":self.entries["target_de"].get()},
            "comparables":[{"company":v[0],"beta":v[1],"de":v[2],"tax":v[3]} for i in self.comp_tree.get_children()
                           for v in [self.comp_tree.item(i,"values")]],
            "bridge":{"debt":self.entries["debt"].get(),"cash":self.entries["cash"].get(),
                      "investments":self.entries["investments"].get(),"minority_interest":self.entries["minority_interest"].get(),
                      "other_claims":self.entries["other_claims"].get(),"other_assets":self.entries["other_assets"].get()},
            "scenarios":{n:{k:v.get() for k,v in d.items()} for n,d in self.scenario_vars.items()}
        }

    def load_data(self,data):
        imp=data.get("import_info",{})
        self.imported_file=imp.get("source_file",""); self.imported_preview=imp.get("preview_excerpt","")
        if hasattr(self,"import_file_var"): self.import_file_var.set(self.imported_file)
        c=data.get("company",{})
        for key,field in [("company_name","name"),("industry","industry"),("valuation_date","valuation_date"),("shares","shares"),("currency","currency")]:
            if field in c:self.entries[key].set(c[field])
        self.mode.set(c.get("mode","Listed"))
        for k,arr in data.get("historical",{}).items():
            if k in self.hist_entries:
                for i,v in enumerate(arr[:5]): self.hist_entries[k][i].set(v)
        for k,arr in data.get("forecast",{}).items():
            if k in self.fcst_entries:
                for i,v in enumerate(arr[:5]): self.fcst_entries[k][i].set(v)
        for section in ["assumptions","capital","bridge"]:
            for k,v in data.get(section,{}).items():
                if k in self.entries:self.entries[k].set(v)
        for i in self.comp_tree.get_children(): self.comp_tree.delete(i)
        for c in data.get("comparables",[]): self.comp_tree.insert("","end",values=(c.get("company",""),c.get("beta",""),c.get("de",""),c.get("tax","")))
        for n,d in data.get("scenarios",{}).items():
            if n in self.scenario_vars:
                for k,v in d.items():
                    if k in self.scenario_vars[n]: self.scenario_vars[n][k].set(v)

    def calculate(self):
        try:
            data=self.gather()
            if num(data["historical"]["sales"][-1])<=0:
                raise ValueError("Please enter positive FY0 revenue in Historical Financials.")
            self.result=DCFEngine.calculate(data)
            r=self.result
            self.kpis["cost_equity"].set(fmt_pct(r.cost_equity)); self.kpis["wacc"].set(fmt_pct(r.wacc))
            self.kpis["ev"].set(fmt_money(r.enterprise_value)); self.kpis["eq"].set(fmt_money(r.equity_value))
            self.kpis["vps"].set(fmt_money(r.value_per_share)); self.kpis["beta"].set(f"{r.bottom_up_beta:.3f}" if r.bottom_up_beta else "-")
            for x in self.fcff_tree.get_children(): self.fcff_tree.delete(x)
            for i,y in enumerate(YEARS_FCST):
                self.fcff_tree.insert("","end",values=(y,fmt_money(r.forecast_sales[i]),fmt_money(r.forecast_ebitda[i]),fmt_money(r.fcff[i]),fmt_money(r.pv_fcff[i])))
            for x in self.scenario_tree.get_children(): self.scenario_tree.delete(x)
            for name,val in r.scenario_values.items():
                self.scenario_tree.insert("","end",values=(name,fmt_money(val) if val is not None else "N/M"))
            self._render_sensitivity()
            self.nb.select(self.tabs["Results"])
            self.status.set(f"Calculated successfully. Intrinsic value: {fmt_money(r.value_per_share)}")
        except Exception as e:
            messagebox.showerror("Calculation Error",str(e))
            self.status.set("Calculation failed.")

    def _render_sensitivity(self):
        r=self.result
        if not r:return
        cols=["wacc"]+[f"g{i}" for i in range(5)]
        self.sensitivity_tree["columns"]=cols
        self.sensitivity_tree.heading("wacc",text="WACC \\ g"); self.sensitivity_tree.column("wacc",width=120,anchor="center")
        gkeys=list(next(iter(r.sensitivity.values())).keys())
        for i,g in enumerate(gkeys):
            self.sensitivity_tree.heading(f"g{i}",text=fmt_pct(g)); self.sensitivity_tree.column(f"g{i}",width=135,anchor="e")
        for x in self.sensitivity_tree.get_children():self.sensitivity_tree.delete(x)
        for w,row in r.sensitivity.items():
            vals=[fmt_pct(w)]+[fmt_money(row[g]) if row[g] is not None else "N/M" for g in gkeys]
            self.sensitivity_tree.insert("","end",values=vals)

    def save_project(self):
        path=filedialog.asksaveasfilename(defaultextension=".json",filetypes=[("DCF Project","*.json")],initialfile="DCF_Project.json")
        if not path:return
        with open(path,"w",encoding="utf-8") as f:json.dump(self.gather(),f,indent=2)
        self.project_path=path; self.status.set(f"Project saved: {path}")

    def open_project(self):
        path=filedialog.askopenfilename(filetypes=[("DCF Project","*.json"),("JSON","*.json")])
        if not path:return
        try:
            with open(path,"r",encoding="utf-8") as f:data=json.load(f)
            self.load_data(data); self.project_path=path; self.calculate()
            self.status.set(f"Project opened: {path}")
        except Exception as e: messagebox.showerror("Open Project",str(e))

    def export_pack(self):
        if self.result is None:
            self.calculate()
            if self.result is None:return
        folder=filedialog.askdirectory(title="Choose output folder")
        if not folder:return
        try:
            data=self.gather(); company=data["company"]["name"] or "Company"
            stem="".join(c if c.isalnum() or c in "-_" else "_" for c in company).strip("_")
            paths=[]
            paths.append(self._export_excel(folder,stem,data,self.result))
            paths.append(self._export_word(folder,stem,data,self.result))
            paths.append(self._export_pdf(folder,stem,data,self.result))
            paths.append(self._export_ppt(folder,stem,data,self.result))
            jpath=os.path.join(folder,f"{stem}_DCF_Project.json")
            with open(jpath,"w",encoding="utf-8") as f:json.dump(data,f,indent=2)
            paths.append(jpath)
            messagebox.showinfo("Export Complete","Created:\n\n"+"\n".join(os.path.basename(p) for p in paths))
            self.status.set(f"Exported complete valuation pack to {folder}")
        except Exception as e:
            traceback.print_exc()
            messagebox.showerror("Export Error",f"{e}\n\nInstall all libraries from requirements.txt if needed.")

    def _export_excel(self,folder,stem,data,r):
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
        from openpyxl.comments import Comment
        from openpyxl.chart import LineChart, Reference
        from openpyxl.utils import get_column_letter
        wb=Workbook(); ws=wb.active; ws.title="Summary"
        dark="17365D"; blue="0000FF"; green="008000"; white="FFFFFF"; yellow="FFFF00"; black="000000"; red="FF0000"
        ws.sheet_view.showGridLines=False
        ws["A1"]=f"DCF VALUATION PROFESSIONAL - {data['company']['name']}"; ws["A1"].font=Font(size=18,bold=True,color=white)
        ws["A1"].fill=PatternFill("solid",fgColor=dark); ws.merge_cells("A1:F1")
        summary=[("Company Type",data["company"]["mode"]),("Valuation Date",data["company"]["valuation_date"]),
                 ("Cost of Equity",r.cost_equity),("WACC",r.wacc),("Terminal Growth",r.terminal_growth),
                 ("Enterprise Value",r.enterprise_value),("Equity Value",r.equity_value),("Intrinsic Value / Share",r.value_per_share)]
        for i,(a,b) in enumerate(summary,start=3):
            ws.cell(i,1,a); ws.cell(i,2,b)
            ws.cell(i,1).font=Font(bold=True)
            if isinstance(b,float):
                ws.cell(i,2).number_format="0.00%;[Red](0.00%);-" if "Cost" in a or "WACC" in a or "Growth" in a else '#,##0.00;[Red](#,##0.00);-'
        ws.column_dimensions["A"].width=28; ws.column_dimensions["B"].width=22

        wh=wb.create_sheet("Historical"); wh.sheet_view.showGridLines=False
        wh.append(["Metric"]+YEARS_HIST)
        for key,label in [("sales","Revenue"),("ebitda","EBITDA"),("da","D&A"),("ebit","EBIT"),("capex","Capex"),("nwc","Net Working Capital")]:
            wh.append([label]+[num(x) for x in data["historical"][key]])
        for cell in wh[1]: cell.fill=PatternFill("solid",fgColor=dark); cell.font=Font(color=white,bold=True)

        wa=wb.create_sheet("Assumptions"); wa.sheet_view.showGridLines=False
        wa.append(["DCF Assumption","Value","Source / Rationale"])
        ass=[
            ("Tax Rate",pct(data["assumptions"]["tax_rate"]),"User input / normalized tax"),
            ("D&A % Revenue",pct(data["assumptions"]["da_pct"]),"User input"),
            ("Capex % Revenue",pct(data["assumptions"]["capex_pct"]),"User input"),
            ("ΔNWC % Incremental Revenue",pct(data["assumptions"]["nwc_increment_pct"]),"User input"),
            ("Terminal Growth",pct(data["assumptions"]["terminal_growth"]),"User input"),
            ("Risk-Free Rate",pct(data["capital"]["risk_free"]),"User input / market data"),
            ("ERP",pct(data["capital"]["erp"]),"User input / market data"),
            ("Beta",num(data["capital"]["beta"]),"Listed beta or fallback"),
            ("Company-Specific Risk Premium",pct(data["capital"]["csrp"]),"Optional user judgment"),
            ("Pre-Tax Cost of Debt",pct(data["capital"]["cost_debt"]),"User input"),
            ("Debt Weight",pct(data["capital"]["debt_weight"]),"Target / observed structure"),
            ("Bottom-Up Beta",r.bottom_up_beta,"Derived from comparables")
        ]
        for row in ass: wa.append(row)
        for cell in wa[1]: cell.fill=PatternFill("solid",fgColor=dark); cell.font=Font(color=white,bold=True)
        for row in range(2,wa.max_row+1):
            wa.cell(row,2).font=Font(color=blue)
            wa.cell(row,2).fill=PatternFill("solid",fgColor="FFF2CC")
            wa.cell(row,2).comment=Comment(str(wa.cell(row,3).value),"DCF Valuation Professional")

        wf=wb.create_sheet("DCF"); wf.sheet_view.showGridLines=False
        wf.append(["₹ / Units"]+YEARS_FCST)
        rows=[
            ("Revenue",r.forecast_sales),("EBITDA",r.forecast_ebitda),("D&A",r.da),("EBIT",r.forecast_ebit),
            ("NOPAT",r.nopat),("Capex",r.capex),("ΔNWC",r.delta_nwc),("FCFF",r.fcff),
            ("Discount Factor",r.discount_factors),("PV of FCFF",r.pv_fcff)]
        for label,vals in rows:wf.append([label]+vals)
        wf.append(["Terminal Value",None,None,None,None,r.terminal_value])
        wf.append(["PV Terminal Value",None,None,None,None,r.pv_terminal_value])
        wf.append(["Enterprise Value",r.enterprise_value])
        wf.append(["Equity Value",r.equity_value])
        wf.append(["Value / Share",r.value_per_share])
        for cell in wf[1]: cell.fill=PatternFill("solid",fgColor=dark); cell.font=Font(color=white,bold=True)
        for row in range(2,wf.max_row+1):
            wf.cell(row,1).font=Font(bold=True)
            for col in range(2,7):
                wf.cell(row,col).number_format='#,##0.00;[Red](#,##0.00);-'
        # charts
        chart=LineChart(); chart.title="Forecast Revenue"; chart.y_axis.title="Value"; chart.x_axis.title="Year"
        chart.add_data(Reference(wf,min_col=2,max_col=6,min_row=2,max_row=2),titles_from_data=False)
        chart.set_categories(Reference(wf,min_col=2,max_col=6,min_row=1,max_row=1)); chart.height=7; chart.width=13
        wf.add_chart(chart,"H2")

        wsens=wb.create_sheet("Sensitivity"); wsens.sheet_view.showGridLines=False
        gkeys=list(next(iter(r.sensitivity.values())).keys())
        wsens.append(["WACC \\ g"]+list(gkeys))
        for w,row in r.sensitivity.items(): wsens.append([w]+[row[g] for g in gkeys])
        for cell in wsens[1]: cell.fill=PatternFill("solid",fgColor=dark); cell.font=Font(color=white,bold=True)
        for rr in range(2,wsens.max_row+1): wsens.cell(rr,1).number_format="0.00%"
        for cc in range(2,wsens.max_column+1): wsens.cell(1,cc).number_format="0.00%"
        for rr in range(2,wsens.max_row+1):
            for cc in range(2,wsens.max_column+1): wsens.cell(rr,cc).number_format='#,##0.00;[Red](#,##0.00);-'

        wc=wb.create_sheet("Comparables"); wc.append(["Company","Levered Beta","D/E","Tax %"])
        for c in data["comparables"]: wc.append([c["company"],num(c["beta"]),num(c["de"]),pct(c["tax"])])
        for cell in wc[1]: cell.fill=PatternFill("solid",fgColor=dark); cell.font=Font(color=white,bold=True)

        for sh in wb.worksheets:
            for col in range(1,sh.max_column+1): sh.column_dimensions[get_column_letter(col)].width=max(12,min(28,max((len(str(sh.cell(r,col).value or "")) for r in range(1,sh.max_row+1)),default=10)+2))
            sh.freeze_panes="B2"
        path=os.path.join(folder,f"{stem}_DCF_Model.xlsx"); wb.save(path); return path

    def _export_word(self,folder,stem,data,r):
        from docx import Document
        from docx.shared import Pt
        doc=Document()
        doc.add_heading(f"DCF Valuation Report - {data['company']['name']}",0)
        doc.add_paragraph(f"Valuation Date: {data['company']['valuation_date']} | Company Type: {data['company']['mode']}")
        doc.add_heading("Executive Summary",1)
        doc.add_paragraph(f"The FCFF DCF produces an enterprise value of {fmt_money(r.enterprise_value)}, equity value of {fmt_money(r.equity_value)}, and intrinsic value per share/unit of {fmt_money(r.value_per_share)}.")
        doc.add_heading("Methodology",1)
        doc.add_paragraph("FCFF = EBIT × (1 − Tax Rate) + D&A − Capex − ΔNWC. FCFF is discounted using WACC. Terminal value uses the Gordon Growth Model.")
        doc.add_heading("Cost of Capital",1)
        doc.add_paragraph(f"Cost of Equity: {fmt_pct(r.cost_equity)} | WACC: {fmt_pct(r.wacc)} | Terminal Growth: {fmt_pct(r.terminal_growth)}.")
        if data["company"]["mode"]=="Unlisted":
            doc.add_paragraph(f"Bottom-up unlevered beta from comparable companies: {r.bottom_up_beta:.3f}. The beta is re-levered to the subject company's target D/E where comparable data is available.")
        doc.add_heading("Forecast",1)
        table=doc.add_table(rows=1,cols=6); table.style="Table Grid"
        for j,h in enumerate(["Metric"]+YEARS_FCST):table.cell(0,j).text=h
        for label,vals in [("Revenue",r.forecast_sales),("EBITDA",r.forecast_ebitda),("FCFF",r.fcff),("PV FCFF",r.pv_fcff)]:
            cells=table.add_row().cells; cells[0].text=label
            for j,v in enumerate(vals,1):cells[j].text=fmt_money(v)
        doc.add_heading("Scenario Analysis",1)
        for n,v in r.scenario_values.items(): doc.add_paragraph(f"{n}: {fmt_money(v) if v is not None else 'Not meaningful'}")
        doc.add_heading("Important Limitations",1)
        doc.add_paragraph("This software is a decision-support and modelling utility. Outputs depend on user-entered assumptions and data quality. For statutory, regulatory, transaction or litigation valuations, the user should apply the relevant valuation standards, professional judgment, documentation, and any legally prescribed method.")
        path=os.path.join(folder,f"{stem}_DCF_Report.docx"); doc.save(path); return path

    def _export_pdf(self,folder,stem,data,r):
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        path=os.path.join(folder,f"{stem}_DCF_Report.pdf")
        styles=getSampleStyleSheet(); story=[]
        story.append(Paragraph(f"<b>DCF Valuation Report - {data['company']['name']}</b>",styles["Title"]))
        story.append(Paragraph(f"Valuation Date: {data['company']['valuation_date']} | Type: {data['company']['mode']}",styles["Normal"]))
        story.append(Spacer(1,12)); story.append(Paragraph("Valuation Summary",styles["Heading2"]))
        rows=[["Metric","Result"],["Cost of Equity",fmt_pct(r.cost_equity)],["WACC",fmt_pct(r.wacc)],["Terminal Growth",fmt_pct(r.terminal_growth)],
              ["Enterprise Value",fmt_money(r.enterprise_value)],["Equity Value",fmt_money(r.equity_value)],["Intrinsic Value / Share",fmt_money(r.value_per_share)]]
        table=Table(rows,colWidths=[220,180]); table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#17365D")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),0.5,colors.grey),("PADDING",(0,0),(-1,-1),6)])); story.append(table)
        story.append(Spacer(1,12)); story.append(Paragraph("Methodology",styles["Heading2"]))
        story.append(Paragraph("The model forecasts five years of FCFF and discounts those cash flows at WACC. Terminal value is calculated using the Gordon Growth Model. Equity value is obtained by adjusting enterprise value for debt, cash, investments, minority interest and other non-operating items.",styles["BodyText"]))
        story.append(Spacer(1,10)); story.append(Paragraph("Forecast FCFF",styles["Heading2"]))
        rows=[["Year","Revenue","EBITDA","FCFF","PV FCFF"]]+[[YEARS_FCST[i],fmt_money(r.forecast_sales[i]),fmt_money(r.forecast_ebitda[i]),fmt_money(r.fcff[i]),fmt_money(r.pv_fcff[i])] for i in range(5)]
        table=Table(rows,colWidths=[70,95,95,95,95]); table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1F4E78")),("TEXTCOLOR",(0,0),(-1,0),colors.white),("GRID",(0,0),(-1,-1),0.4,colors.grey),("ALIGN",(1,1),(-1,-1),"RIGHT"),("FONTSIZE",(0,0),(-1,-1),8)])); story.append(table)
        story.append(Spacer(1,12)); story.append(Paragraph("Disclaimer",styles["Heading2"]))
        story.append(Paragraph("Offline analytical utility only. Valuation conclusions are sensitive to assumptions. Apply applicable ICAI/IVS/registered-valuer/regulatory requirements where relevant.",styles["BodyText"]))
        SimpleDocTemplate(path,pagesize=A4,rightMargin=36,leftMargin=36,topMargin=36,bottomMargin=36).build(story)
        return path

    def _export_ppt(self,folder,stem,data,r):
        from pptx import Presentation
        from pptx.util import Inches, Pt
        prs=Presentation()
        def add_slide(title, bullets):
            s=prs.slides.add_slide(prs.slide_layouts[1]); s.shapes.title.text=title
            tf=s.placeholders[1].text_frame; tf.clear()
            for i,b in enumerate(bullets):
                p=tf.paragraphs[0] if i==0 else tf.add_paragraph(); p.text=b; p.font.size=Pt(20)
        s=prs.slides.add_slide(prs.slide_layouts[0]); s.shapes.title.text=f"DCF Valuation - {data['company']['name']}"; s.placeholders[1].text=f"{data['company']['mode']} Company | {data['company']['valuation_date']}"
        add_slide("Valuation Summary",[f"Enterprise Value: {fmt_money(r.enterprise_value)}",f"Equity Value: {fmt_money(r.equity_value)}",f"Intrinsic Value / Share: {fmt_money(r.value_per_share)}"])
        add_slide("Methodology",["Five-year FCFF forecast","CAPM / WACC","Gordon Growth terminal value","Enterprise-to-equity bridge","Sensitivity and scenario analysis"])
        add_slide("Cost of Capital",[f"Cost of Equity: {fmt_pct(r.cost_equity)}",f"WACC: {fmt_pct(r.wacc)}",f"Terminal Growth: {fmt_pct(r.terminal_growth)}",f"Bottom-Up Beta: {r.bottom_up_beta:.3f}" if r.bottom_up_beta else "Listed-company beta used"])
        add_slide("Forecast FCFF",[f"{YEARS_FCST[i]}: {fmt_money(r.fcff[i])}" for i in range(5)])
        add_slide("Scenarios",[f"{n}: {fmt_money(v) if v is not None else 'N/M'}" for n,v in r.scenario_values.items()])
        add_slide("Limitations",["Outputs depend on data quality and assumptions","Unlisted valuations require careful comparable-company selection","Company-specific risk premiums require professional support","Regulatory/statutory valuations may prescribe additional methods or standards"])
        path=os.path.join(folder,f"{stem}_DCF_Presentation.pptx"); prs.save(path); return path

    def show_help(self):
        messagebox.showinfo("How to Use", """1. Select Listed or Unlisted.
2. Enter company details and FY0 revenue.
3. Fill forecast growth and margin assumptions.
4. Enter risk-free rate, ERP, beta/cost of debt.
5. For unlisted companies, add listed comparables with levered beta, D/E and tax rate.
6. Enter debt, cash and non-operating adjustments.
7. Review Bear/Base/Bull adjustments.
8. Click Calculate.
9. Review Results and Sensitivity.
10. Export Pack to create Excel, Word, PDF and PowerPoint files.

Offline calculations and imports do not require internet or an API key.
AI choices:
- Offline heuristic engine: no AI model or internet.
- Ollama: local/offline LLM via http://localhost:11434. Use Test AI Connection first.
- OpenAI / Gemini: optional online AI using your own API key. Use Test AI Connection to verify credentials.

Always verify imported financial figures and AI-generated assumptions before relying on a valuation.""")

if __name__ == "__main__":
    if license_gate():
        app = DCFApp()
        app.mainloop()
