<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Practice.Database/Practice.Database.csproj" />
    <ProjectReference Include="../Practice.WorkbookProfiler/Practice.WorkbookProfiler.csproj" />
  </ItemGroup>
</Project>
