// Build CMA-Pro-Builder.exe — single-file LAN server via Node SEA.
// Steps: embed public key → esbuild bundle → SEA blob → copy node.exe → postject.
// Run:  node tools/build-exe.cjs
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const OUT_DIR = path.join(ROOT, 'dist-server');
const RELEASE_DIR = path.join(ROOT, 'release');
const EXE_NAME = 'CMA-Pro-Builder.exe';

function walk(dir, base = dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p, base));
    else out.push(path.relative(base, p).replace(/\\/g, '/'));
  }
  return out;
}

// 0. sanity
if (!fs.existsSync(path.join(DIST, 'index.html'))) {
  console.error('dist/ not built — run "npm run build" first');
  process.exit(1);
}

// 1. embed the license HMAC secret (derived from the vendor private key).
//    EVALUATION BUILD: no private key in this copy — licensing is disabled in
//    server/license.cjs (EVALUATION_MODE), so a placeholder secret is embedded.
const crypto = require('crypto');
const pemPath = path.join(ROOT, 'tools', 'keygen-private.pem');
const secret = fs.existsSync(pemPath)
  ? crypto.createHash('sha256').update(fs.readFileSync(pemPath, 'utf8')).digest('hex')
  : 'evaluation-build-no-secret';
fs.writeFileSync(
  path.join(ROOT, 'server', 'license-secret.cjs'),
  `// GENERATED by tools/build-exe.cjs — embedded license secret\nmodule.exports = ${JSON.stringify(secret)};\n`
);
console.log('✓ license secret embedded');

// 2. esbuild bundle (express + license inlined, node builtins external)
fs.mkdirSync(OUT_DIR, { recursive: true });
const esbuild = require('esbuild');
esbuild.buildSync({
  entryPoints: [path.join(ROOT, 'server', 'server.cjs')],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  outfile: path.join(OUT_DIR, 'bundle.cjs'),
  external: ['node:*'],
});
console.log('✓ server bundled → dist-server/bundle.cjs');

// 3. SEA config with dist assets
const assets = {};
for (const rel of walk(DIST)) assets[`dist/${rel}`] = path.join(DIST, rel);
const seaConfig = {
  main: path.join(OUT_DIR, 'bundle.cjs'),
  output: path.join(OUT_DIR, 'sea-prep.blob'),
  disableExperimentalSEAWarning: true,
  assets,
};
fs.writeFileSync(path.join(OUT_DIR, 'sea-config.json'), JSON.stringify(seaConfig, null, 2));
execSync(`"${process.execPath}" --experimental-sea-config "${path.join(OUT_DIR, 'sea-config.json')}"`, { stdio: 'inherit' });
console.log(`✓ SEA blob (${Object.keys(assets).length} assets embedded)`);

// 4. copy node.exe → release exe
fs.mkdirSync(RELEASE_DIR, { recursive: true });
const exePath = path.join(RELEASE_DIR, EXE_NAME);
fs.copyFileSync(process.execPath, exePath);

// 5. inject the blob
const postject = path.join(ROOT, 'node_modules', '.bin', process.platform === 'win32' ? 'postject.cmd' : 'postject');
const cmd = fs.existsSync(postject)
  ? `"${postject}" "${exePath}" NODE_SEA_BLOB "${path.join(OUT_DIR, 'sea-prep.blob')}" --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`
  : `npx --yes postject "${exePath}" NODE_SEA_BLOB "${path.join(OUT_DIR, 'sea-prep.blob')}" --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`;
execSync(cmd, { stdio: 'inherit', cwd: ROOT });

const mb = (fs.statSync(exePath).size / 1024 / 1024).toFixed(1);
console.log('');
console.log(`✓ DONE → release\\${EXE_NAME} (${mb} MB)`);
console.log('  Double-click it on the office server PC, activate with a license key,');
console.log('  then every PC on the LAN opens http://<server-ip>:8080 in a browser.');
