"""Identifier validation. Build Prompt v2 §2 (`core/validators`) and §8.6.

Every one of these is typed and validated at entry. The prototype accepted
free text for all of them, which is how a malformed CIN reaches a signed
document.
"""

from __future__ import annotations

import re
from datetime import date

# --------------------------------------------------------------------------
# Corporate Identity Number
# --------------------------------------------------------------------------
# 21 characters: L/U + 5-digit industry code + 2-letter state + 4-digit year
# + 3-letter ownership + 6-digit registration number.
#   U   72200 KA 2010 PTC 054288
_CIN = re.compile(
    r"^([LU])(\d{5})([A-Z]{2})(\d{4})([A-Z]{3})(\d{6})$",
)

_OWNERSHIP: frozenset[str] = frozenset(
    {
        "PTC",  # private limited
        "PLC",  # public limited
        "OPC",  # one person company
        "SGC",  # State Government company
        "GOI",  # Union Government company
        "NPL",  # not-for-profit, section 8
        "FTC",  # subsidiary of a foreign company
        "GAP",  # general association public
        "GAT",  # general association private
        "ULL",  # unlimited liability, public
        "ULT",  # unlimited liability, private
    }
)

# Indian state and union territory codes used in a CIN.
_STATE_CODES: frozenset[str] = frozenset(
    {
        "AN",
        "AP",
        "AR",
        "AS",
        "BR",
        "CH",
        "CG",
        "DL",
        "DN",
        "DD",
        "GA",
        "GJ",
        "HR",
        "HP",
        "JK",
        "JH",
        "KA",
        "KL",
        "LD",
        "LA",
        "MP",
        "MH",
        "MN",
        "ML",
        "MZ",
        "NL",
        "OR",
        "OD",
        "PY",
        "PB",
        "RJ",
        "SK",
        "TN",
        "TS",
        "TR",
        "UP",
        "UK",
        "UR",
        "WB",
    }
)


class ValidationError(ValueError):
    """A user-facing validation failure. Message is safe to display."""


def normalise(value: str) -> str:
    return value.strip().upper().replace(" ", "").replace("-", "")


def validate_cin(value: str) -> str:
    """Structure-check a CIN and return it normalised.

    There is no published check digit for a CIN, so this validates structure
    only — length, listing status, state code, incorporation year and
    ownership class. Claiming a check-digit validation we cannot perform
    would be worse than validating less.
    """
    cin = normalise(value)
    if len(cin) != 21:
        raise ValidationError(f"CIN must be 21 characters, got {len(cin)}")

    match = _CIN.match(cin)
    if match is None:
        raise ValidationError("CIN structure is invalid")

    listing, _industry, state, year, ownership, _serial = match.groups()

    if state not in _STATE_CODES:
        raise ValidationError(f"CIN state code {state!r} is not recognised")

    incorporation_year = int(year)
    if not 1857 <= incorporation_year <= date.today().year:
        raise ValidationError(f"CIN incorporation year {year} is implausible")

    if ownership not in _OWNERSHIP:
        raise ValidationError(f"CIN ownership class {ownership!r} is not recognised")

    if listing == "L" and ownership == "PTC":
        raise ValidationError("CIN cannot be listed (L) and private (PTC)")

    return cin


# --------------------------------------------------------------------------
# Other identifiers
# --------------------------------------------------------------------------

_PAN = re.compile(r"^[A-Z]{5}\d{4}[A-Z]$")
_PAN_HOLDER_TYPES = frozenset("CPHFATBLJGK")

_GSTIN = re.compile(r"^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")
_DIN = re.compile(r"^\d{8}$")
_FRN = re.compile(r"^\d{6}[A-Z]?$")
_MEMBERSHIP = re.compile(r"^\d{5,6}$")
# 18 characters: 2-digit year + 6-digit ICAI membership number + 10
# alphanumeric characters generated by the UDIN portal.
# NEEDS REVIEW: this structure is my own reading, not taken from the ICAI
# UDIN Guidelines. Confirm before Gate A — a wrong pattern here rejects
# valid UDINs at the point a partner is trying to sign.
_UDIN = re.compile(r"^\d{2}\d{6}[A-Z0-9]{10}$")


def validate_pan(value: str) -> str:
    pan = normalise(value)
    if not _PAN.match(pan):
        raise ValidationError("PAN must be five letters, four digits, one letter")
    if pan[3] not in _PAN_HOLDER_TYPES:
        raise ValidationError(f"PAN holder-type character {pan[3]!r} is invalid")
    return pan


def validate_gstin(value: str) -> str:
    gstin = normalise(value)
    if not _GSTIN.match(gstin):
        raise ValidationError("GSTIN must be 15 characters in the prescribed format")
    return gstin


def validate_din(value: str) -> str:
    din = normalise(value)
    if not _DIN.match(din):
        raise ValidationError("DIN must be exactly 8 digits")
    return din


def validate_frn(value: str) -> str:
    frn = normalise(value)
    if not _FRN.match(frn):
        raise ValidationError("FRN must be 6 digits, optionally followed by a letter")
    return frn


def validate_membership_no(value: str) -> str:
    membership = normalise(value)
    if not _MEMBERSHIP.match(membership):
        raise ValidationError("Membership number must be 5 or 6 digits")
    return membership


def validate_udin(value: str) -> str:
    """UDIN: 2-digit year + 6-digit membership number + 10 alphanumeric.

    See the NEEDS REVIEW note on `_UDIN` — the structure is derived, not
    sourced from the ICAI guidelines.
    """
    udin = normalise(value)
    if not _UDIN.match(udin):
        raise ValidationError("UDIN must be 18 characters in the ICAI format")
    return udin


# --------------------------------------------------------------------------
# Dates
# --------------------------------------------------------------------------


def validate_fy(fy_start: date, fy_end: date) -> None:
    if fy_end <= fy_start:
        raise ValidationError("Financial year end must fall after its start")
    if (fy_end - fy_start).days > 550:
        # The first financial year of a company may exceed twelve months but
        # cannot exceed fifteen (s.2(41)).
        raise ValidationError("A financial year cannot exceed fifteen months")


def validate_report_date(report_date: date, fy_end: date) -> None:
    if report_date < fy_end:
        raise ValidationError("The report date cannot precede the financial year end")
