import { IndustryType, KpiMetric, MonthlyFinancialRecord, ClientProfile } from '../types';
import { FinancialEngine } from './financialEngine';

export interface IndustryProfileDef {
  id: IndustryType;
  name: string;
  description: string;
  keyDrivers: string[];
  commonRedFlags: string[];
  kpiDefinitions: {
    id: string;
    name: string;
    category: 'profitability' | 'liquidity' | 'efficiency' | 'growth' | 'industry';
    benchmark: number;
    benchmarkFormatted: string;
    unit: string;
    formulaDesc: string;
    whatIsIt: string;
    whyItMatters: string;
  }[];
}

export const INDUSTRY_PROFILES: Record<IndustryType, IndustryProfileDef> = {
  medical: {
    id: 'medical',
    name: 'Medical & Healthcare Practices',
    description: 'Outpatient clinics, specialized medical groups, surgical centers, and healthcare providers.',
    keyDrivers: ['Provider Count', 'Patient Encounter Volume', 'Payer Mix (Commercial vs Medicare/Medicaid)', 'Clean Claim Rate'],
    commonRedFlags: ['AR Days > 50 days due to billing delays', 'Declining revenue per provider', 'High credentialing lag time'],
    kpiDefinitions: [
      {
        id: 'med_ar_days',
        name: 'Medical Days in AR',
        category: 'efficiency',
        benchmark: 35,
        benchmarkFormatted: '35 - 42 days',
        unit: 'days',
        formulaDesc: '(Total Accounts Receivable / Annualized Net Patient Revenue) * 365',
        whatIsIt: 'The average number of days it takes your practice to collect payments from insurance payers and patients.',
        whyItMatters: 'Healthcare collections above 45 days tie up critical cash and indicate claim denials or billing cycle friction.',
      },
      {
        id: 'med_rev_per_provider',
        name: 'Revenue per Provider / Month',
        category: 'industry',
        benchmark: 95000,
        benchmarkFormatted: '$90,000 - $120,000',
        unit: '$',
        formulaDesc: 'Monthly Net Patient Revenue / Full-Time Equivalent (FTE) Providers',
        whatIsIt: 'Average monthly top-line clinical revenue generated by each practicing physician or specialist.',
        whyItMatters: 'Measures clinical throughput, scheduling density, and optimal billing coding capture.',
      },
      {
        id: 'med_operating_margin',
        name: 'Practice Operating Margin',
        category: 'profitability',
        benchmark: 22,
        benchmarkFormatted: '18% - 25%',
        unit: '%',
        formulaDesc: 'Operating Profit (EBITDA) / Net Patient Collections',
        whatIsIt: 'Percentage of revenue remaining after paying staff salaries, clinical supplies, and facility overhead before physician distribution.',
        whyItMatters: 'Healthy practice margins fund medical equipment upgrades, physician partner draws, and reserve stability.',
      },
      {
        id: 'med_payroll_ratio',
        name: 'Clinical & Admin Staff Ratio',
        category: 'efficiency',
        benchmark: 38,
        benchmarkFormatted: '34% - 40%',
        unit: '%',
        formulaDesc: 'Total Non-Owner Wages / Net Patient Revenue',
        whatIsIt: 'The portion of collections consumed by nurses, medical assistants, front-desk, and billing staff.',
        whyItMatters: 'Controls staffing bloat and ensures high support ratio without overhead drag.',
      }
    ]
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant & Hospitality',
    description: 'Full-service dining, casual dining, franchises, bars, and catering operations.',
    keyDrivers: ['Food Cost %', 'Direct Pour Cost %', 'Prime Cost', 'Table Turn Rate', 'Average Check Size'],
    commonRedFlags: ['Prime Cost > 65%', 'Food waste spikes', 'Slow inventory turnover causing spoilage'],
    kpiDefinitions: [
      {
        id: 'rest_prime_cost',
        name: 'Prime Cost %',
        category: 'industry',
        benchmark: 60,
        benchmarkFormatted: '55% - 60%',
        unit: '%',
        formulaDesc: '(Food & Beverage COGS + Total Labor & Payroll Taxes) / Total Sales',
        whatIsIt: 'The total combination of your two largest operational expenses: Cost of Goods (Food/Bev) plus all labor costs.',
        whyItMatters: 'Prime cost is the golden rule of restaurant viability. Operating above 63% severely constricts net profits.',
      },
      {
        id: 'rest_food_cost',
        name: 'Food Cost %',
        category: 'profitability',
        benchmark: 29,
        benchmarkFormatted: '28% - 32%',
        unit: '%',
        formulaDesc: 'Food Cost of Goods Sold / Food Revenue',
        whatIsIt: 'The percentage of food revenue spent purchasing raw ingredients and culinary consumables.',
        whyItMatters: 'Tracks recipe portioning, supplier price inflation, kitchen waste, and menu pricing discipline.',
      },
      {
        id: 'rest_labor_cost',
        name: 'Labor & Staff Cost %',
        category: 'efficiency',
        benchmark: 30,
        benchmarkFormatted: '28% - 32%',
        unit: '%',
        formulaDesc: 'Total Front/Back of House Payroll / Total Revenue',
        whatIsIt: 'Direct kitchen, service, and managerial wages relative to total restaurant turnover.',
        whyItMatters: 'Measures shift scheduling alignment against lunch/dinner rush volumes.',
      },
      {
        id: 'rest_beverage_margin',
        name: 'Beverage Gross Margin',
        category: 'profitability',
        benchmark: 78,
        benchmarkFormatted: '75% - 82%',
        unit: '%',
        formulaDesc: '(Beverage Revenue - Beverage COGS) / Beverage Revenue',
        whatIsIt: 'The profit margin generated on bar, wine, cocktail, and non-alcoholic beverage sales.',
        whyItMatters: 'High-margin beverage programs subsidize food costs and drive overall restaurant EBITDA.',
      }
    ]
  },
  manufacturing: {
    id: 'manufacturing',
    name: 'Manufacturing & Precision Engineering',
    description: 'Industrial manufacturing, OEM parts, assembly, fabrication, and engineered products.',
    keyDrivers: ['Scrap / Rework %', 'Capacity Utilization', 'Inventory Turns', 'Gross Margin per Machine Hour'],
    commonRedFlags: ['Inventory Days > 75 days (excess WIP)', 'Unplanned equipment downtime', 'Raw material price volatility'],
    kpiDefinitions: [
      {
        id: 'mfg_inventory_turns',
        name: 'Inventory Turnover',
        category: 'efficiency',
        benchmark: 7.5,
        benchmarkFormatted: '6.5 - 9.0x / yr',
        unit: 'turns',
        formulaDesc: 'Annualized COGS / Average Inventory Balance',
        whatIsIt: 'How many times per year your facility converts raw materials and WIP into delivered finished goods.',
        whyItMatters: 'Higher velocity reduces warehouse carrying costs, minimizes scrap obsolescence, and accelerates cash conversion.',
      },
      {
        id: 'mfg_gross_margin',
        name: 'Manufacturing Gross Margin',
        category: 'profitability',
        benchmark: 38,
        benchmarkFormatted: '35% - 42%',
        unit: '%',
        formulaDesc: '(Total Sales - Direct Materials - Direct Labor - Applied Overhead) / Total Sales',
        whatIsIt: 'The margin earned directly on manufactured products before corporate SG&A overhead.',
        whyItMatters: 'Validates accurate BOM (Bill of Materials) costing and machine routing efficiency.',
      },
      {
        id: 'mfg_ccc',
        name: 'Cash Conversion Cycle (CCC)',
        category: 'liquidity',
        benchmark: 48,
        benchmarkFormatted: '40 - 55 days',
        unit: 'days',
        formulaDesc: 'Days Sales Outstanding (DSO) + Days Inventory (DIO) - Days Payable (DPO)',
        whatIsIt: 'The net days required to convert raw material procurement cash outlays back into customer cash collections.',
        whyItMatters: 'Shorter cycles significantly decrease reliance on expensive revolving lines of credit.',
      },
      {
        id: 'mfg_scrap_rate',
        name: 'Scrap & Rework Rate',
        category: 'industry',
        benchmark: 1.8,
        benchmarkFormatted: '< 2.2%',
        unit: '%',
        formulaDesc: 'Cost of Rejected Parts & Waste / Total Production Value',
        whatIsIt: 'The percentage of production lost to manufacturing defects, machining tolerance errors, or off-spec scrap.',
        whyItMatters: 'Every 1% reduction in scrap flows dollar-for-dollar straight to EBITDA.',
      }
    ]
  },
  saas: {
    id: 'saas',
    name: 'SaaS & Subscription Technology',
    description: 'Cloud software, recurring subscription platforms, B2B enterprise software, and mobile apps.',
    keyDrivers: ['ARR / MRR Growth', 'Net Retention Rate (NRR)', 'CAC Payback Period', 'LTV:CAC Ratio'],
    commonRedFlags: ['CAC Payback > 20 months', 'Gross Churn > 2.5% monthly', 'Gross Margin below 70%'],
    kpiDefinitions: [
      {
        id: 'saas_gross_margin',
        name: 'SaaS Gross Margin',
        category: 'profitability',
        benchmark: 80,
        benchmarkFormatted: '75% - 84%',
        unit: '%',
        formulaDesc: '(Subscription Revenue - Hosting/Support COGS) / Subscription Revenue',
        whatIsIt: 'Software delivery margins after cloud hosting (AWS/GCP), customer support, and payment processing fees.',
        whyItMatters: 'High gross margins are essential to fund intensive R&D and aggressive sales acquisition.',
      },
      {
        id: 'saas_rule_of_40',
        name: 'Rule of 40 Score',
        category: 'growth',
        benchmark: 42,
        benchmarkFormatted: '> 40%',
        unit: '%',
        formulaDesc: 'Annualized Revenue Growth Rate % + Free Cash Flow Margin % (or EBITDA Margin %)',
        whatIsIt: 'The gold-standard benchmark balancing revenue growth velocity against operating profitability.',
        whyItMatters: 'Companies scoring over 40% command premium market valuations and strong investor confidence.',
      },
      {
        id: 'saas_runway',
        name: 'Cash Runway',
        category: 'liquidity',
        benchmark: 18,
        benchmarkFormatted: '14 - 24 months',
        unit: 'months',
        formulaDesc: 'Total Cash & Short-Term Investments / Average Monthly Net Burn Rate',
        whatIsIt: 'The number of months the company can operate at current net cash burn without additional capital.',
        whyItMatters: 'Ensures ample runway to reach cash-flow break-even or complete non-distressed fundraising rounds.',
      },
      {
        id: 'saas_cac_ratio',
        name: 'LTV to CAC Ratio',
        category: 'industry',
        benchmark: 4.2,
        benchmarkFormatted: '> 3.5x',
        unit: 'x',
        formulaDesc: 'Customer Lifetime Value (LTV) / Customer Acquisition Cost (CAC)',
        whatIsIt: 'The return generated on every dollar invested in sales and marketing to acquire a new customer.',
        whyItMatters: 'Ratios above 3.5x confirm highly efficient, scalable unit economics.',
      }
    ]
  },
  professional_services: {
    id: 'professional_services',
    name: 'Professional Services & Consulting',
    description: 'Advisory, consulting, engineering firms, creative agencies, and staffing organizations.',
    keyDrivers: ['Billable Utilization %', 'Effective Hourly Realization', 'Revenue per Consultant', 'Project Gross Margin'],
    commonRedFlags: ['Utilization < 65%', 'Scope creep reducing realization', 'High concentration in top 2 clients'],
    kpiDefinitions: [
      {
        id: 'ps_utilization',
        name: 'Billable Utilization Rate',
        category: 'efficiency',
        benchmark: 76,
        benchmarkFormatted: '72% - 80%',
        unit: '%',
        formulaDesc: 'Total Billable Client Hours / Total Available Working Hours (Standard 2,080 hrs/yr)',
        whatIsIt: 'The percentage of billable staff time actively logged on revenue-generating client engagements.',
        whyItMatters: 'Every 5% increase in utilization directly expands consulting firm operating profit.',
      },
      {
        id: 'ps_rev_per_fte',
        name: 'Annual Revenue per FTE',
        category: 'industry',
        benchmark: 195000,
        benchmarkFormatted: '$180k - $240k',
        unit: '$',
        formulaDesc: 'Total Annual Firm Revenue / Total Full-Time Equivalent Employees',
        whatIsIt: 'The average annual revenue produced across all consulting and administrative staff.',
        whyItMatters: 'Benchmarks billing leverage, senior-to-junior consultant ratios, and pricing power.',
      },
      {
        id: 'ps_ebitda_margin',
        name: 'Firm EBITDA Margin',
        category: 'profitability',
        benchmark: 24,
        benchmarkFormatted: '20% - 28%',
        unit: '%',
        formulaDesc: 'EBITDA / Total Net Revenue',
        whatIsIt: 'Operating earnings percentage before partner profit distributions and taxes.',
        whyItMatters: 'Provides healthy cash flow for partner bonuses, technology investments, and working capital buffers.',
      }
    ]
  },
  other: {
    id: 'other',
    name: 'General Enterprise / Commercial',
    description: 'Standard commercial enterprise, services, and multi-disciplinary organizations.',
    keyDrivers: ['Gross Margin', 'Operating Efficiency', 'Working Capital', 'Cash Flow Conversion'],
    commonRedFlags: ['Working capital compression', 'Margin erosion', 'Elevated debt service load'],
    kpiDefinitions: [
      {
        id: 'gen_gross_margin',
        name: 'Gross Margin',
        category: 'profitability',
        benchmark: 40,
        benchmarkFormatted: '35% - 45%',
        unit: '%',
        formulaDesc: '(Revenue - COGS) / Revenue',
        whatIsIt: 'Percentage of revenue retained after paying all direct cost of goods and services sold.',
        whyItMatters: 'The fundamental cushion needed to absorb all operating overhead and generate net profit.',
      },
      {
        id: 'gen_current_ratio',
        name: 'Current Ratio',
        category: 'liquidity',
        benchmark: 1.8,
        benchmarkFormatted: '1.5 - 2.2x',
        unit: 'x',
        formulaDesc: 'Current Assets / Current Liabilities',
        whatIsIt: 'The ratio of short-term liquid assets available to pay off obligations due within the next 12 months.',
        whyItMatters: 'Provides a reliable gauge of short-term solvency and working capital resilience.',
      },
      {
        id: 'gen_dso',
        name: 'Days Sales Outstanding (DSO)',
        category: 'efficiency',
        benchmark: 38,
        benchmarkFormatted: '30 - 45 days',
        unit: 'days',
        formulaDesc: '(Accounts Receivable / Annualized Revenue) * 365',
        whatIsIt: 'The average number of days it takes to collect cash receivables from customers after invoicing.',
        whyItMatters: 'Faster collections prevent cash lockup and reduce bad debt risk.',
      }
    ]
  },
  legal: {} as any,
  accounting: {} as any,
  dental: {} as any,
  construction: {} as any,
  real_estate: {} as any,
  ecommerce: {} as any,
  retail: {} as any,
  logistics: {} as any,
  nonprofit: {} as any,
  financial_services: {} as any,
  wholesale: {} as any,
  automotive: {} as any,
};

// Fallbacks for remaining industries to ensure completeness
['legal', 'accounting', 'dental', 'construction', 'real_estate', 'ecommerce', 'retail', 'logistics', 'nonprofit', 'financial_services', 'wholesale', 'automotive'].forEach((key) => {
  const k = key as IndustryType;
  if (!INDUSTRY_PROFILES[k] || !INDUSTRY_PROFILES[k].id) {
    INDUSTRY_PROFILES[k] = {
      id: k,
      name: key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      description: `Specialized financial profile and benchmarking for ${key.replace(/_/g, ' ')} businesses.`,
      keyDrivers: ['Revenue Growth', 'Operating Margins', 'Working Capital', 'Labor Productivity'],
      commonRedFlags: ['Margin contraction', 'Rising DSO', 'Declining cash buffer'],
      kpiDefinitions: INDUSTRY_PROFILES.other.kpiDefinitions,
    };
  }
});

export class IndustryRulesEngine {
  static getProfile(industry: IndustryType): IndustryProfileDef {
    return INDUSTRY_PROFILES[industry] || INDUSTRY_PROFILES.other;
  }

  static computeKpis(client: ClientProfile, records: MonthlyFinancialRecord[]): KpiMetric[] {
    const profile = this.getProfile(client.industry);
    const summary = FinancialEngine.computeSummary(records);
    const latest = records[records.length - 1] || {} as MonthlyFinancialRecord;
    const previous = records.length > 1 ? records[records.length - 2] : latest;

    const results: KpiMetric[] = [];

    // 1. Core Financial KPIs
    // Gross Margin
    const gmValue = summary.grossMargin;
    results.push({
      id: 'core_gross_margin',
      name: 'Gross Margin',
      category: 'profitability',
      value: gmValue,
      formattedValue: `${gmValue.toFixed(1)}%`,
      benchmarkValue: 40,
      benchmarkFormatted: '38% - 45%',
      benchmarkStatus: gmValue >= 38 ? 'outperforming' : (gmValue >= 32 ? 'on_track' : 'lagging'),
      trend: latest.grossMarginPercent >= (previous.grossMarginPercent || 0) ? 'up' : 'down',
      changePercentage: latest.grossMarginPercent - (previous.grossMarginPercent || 0),
      changePeriod: 'MoM',
      explanation: {
        whatIsIt: 'Percentage of revenue retained after paying direct delivery and product costs.',
        whyItMatters: 'Higher gross margin provides more operating leverage to fund growth and absorb inflation.',
        whatMyNumberMeans: `Your business generates $${gmValue.toFixed(0)} of gross profit on every $100 of revenue.`,
        formula: '((Revenue - COGS) / Revenue) * 100',
      }
    });

    // EBITDA Margin
    const ebitdaMargin = summary.ebitdaMargin;
    results.push({
      id: 'core_ebitda_margin',
      name: 'EBITDA Margin',
      category: 'profitability',
      value: ebitdaMargin,
      formattedValue: `${ebitdaMargin.toFixed(1)}%`,
      benchmarkValue: 18,
      benchmarkFormatted: '16% - 22%',
      benchmarkStatus: ebitdaMargin >= 18 ? 'outperforming' : (ebitdaMargin >= 12 ? 'on_track' : 'critical'),
      trend: latest.ebitdaMarginPercent >= (previous.ebitdaMarginPercent || 0) ? 'up' : 'down',
      changePercentage: latest.ebitdaMarginPercent - (previous.ebitdaMarginPercent || 0),
      changePeriod: 'MoM',
      explanation: {
        whatIsIt: 'Operating cash profitability percentage before non-cash depreciation, interest, and taxes.',
        whyItMatters: 'Standard metric for operational efficiency and firm market valuation.',
        whatMyNumberMeans: `For every $100 of revenue, $${ebitdaMargin.toFixed(0)} flows into operating earnings.`,
        formula: '(EBITDA / Total Revenue) * 100',
      }
    });

    // Current Ratio
    const currentRatio = latest.currentRatio || summary.avgCurrentRatio || 1.8;
    results.push({
      id: 'core_current_ratio',
      name: 'Current Ratio',
      category: 'liquidity',
      value: currentRatio,
      formattedValue: `${currentRatio.toFixed(2)}x`,
      benchmarkValue: 1.8,
      benchmarkFormatted: '1.5 - 2.2x',
      benchmarkStatus: currentRatio >= 1.5 ? 'on_track' : (currentRatio >= 1.1 ? 'lagging' : 'critical'),
      trend: currentRatio >= (previous.currentRatio || 1.5) ? 'up' : 'down',
      changePercentage: Number((((currentRatio - (previous.currentRatio || 1.5)) / (previous.currentRatio || 1.5)) * 100).toFixed(1)),
      changePeriod: 'MoM',
      explanation: {
        whatIsIt: 'The ratio of short-term assets to short-term obligations due within 12 months.',
        whyItMatters: 'Values below 1.2x signal potential liquidity bottlenecks during slow collection cycles.',
        whatMyNumberMeans: `You have $${currentRatio.toFixed(2)} in short-term assets for every $1.00 of liabilities due soon.`,
        formula: 'Total Current Assets / Total Current Liabilities',
      }
    });

    // Cash Runway
    const runway = summary.cashRunwayMonths;
    results.push({
      id: 'core_cash_runway',
      name: 'Cash Runway',
      category: 'liquidity',
      value: runway,
      formattedValue: runway >= 50 ? 'Self-Sustaining' : `${runway.toFixed(1)} mos`,
      benchmarkValue: 12,
      benchmarkFormatted: '> 12 months',
      benchmarkStatus: runway >= 12 || runway >= 50 ? 'outperforming' : (runway >= 6 ? 'on_track' : 'critical'),
      trend: 'stable',
      changePercentage: 0,
      changePeriod: 'MoM',
      explanation: {
        whatIsIt: 'The number of months current cash reserves will last based on historical burn rate.',
        whyItMatters: 'Essential for avoiding emergency capital dilution or cash-flow insolvency.',
        whatMyNumberMeans: runway >= 50 ? 'Operating cash flows are positive; no external burn runway dependency.' : `At current burn rate, existing cash covers approximately ${runway.toFixed(1)} months of operations.`,
        formula: 'Ending Cash Balance / Average Monthly Net Cash Burn',
      }
    });

    // Days Sales Outstanding (DSO)
    const dso = latest.dso || summary.avgDso || 36;
    results.push({
      id: 'core_dso',
      name: 'Days Sales Outstanding (DSO)',
      category: 'efficiency',
      value: dso,
      formattedValue: `${Math.round(dso)} days`,
      benchmarkValue: 38,
      benchmarkFormatted: '30 - 45 days',
      benchmarkStatus: dso <= 42 ? 'outperforming' : (dso <= 52 ? 'on_track' : 'lagging'),
      trend: dso <= (previous.dso || 38) ? 'up' : 'down',
      changePercentage: Number((dso - (previous.dso || 38)).toFixed(1)),
      changePeriod: 'MoM',
      explanation: {
        whatIsIt: 'The average number of days it takes your team to collect payment after sending an invoice.',
        whyItMatters: 'Shortening DSO accelerates cash collection without having to borrow or increase sales.',
        whatMyNumberMeans: `On average, invoices are collected in ${Math.round(dso)} days after issuance.`,
        formula: '(Accounts Receivable / Annualized Revenue) * 365',
      }
    });

    // 2. Industry Specific KPI additions
    if (client.industry === 'medical') {
      const revPerProvider = (latest.revenue || 700000) / (client.headcount ? Math.max(1, Math.round(client.headcount / 4)) : 8);
      results.push({
        id: 'med_rev_per_prov_calc',
        name: 'Revenue per Provider / Month',
        category: 'industry',
        value: revPerProvider,
        formattedValue: FinancialEngine.formatCurrency(revPerProvider, client.currency, true),
        benchmarkValue: 95000,
        benchmarkFormatted: '$90,000 - $115,000',
        benchmarkStatus: revPerProvider >= 90000 ? 'outperforming' : 'on_track',
        trend: 'up',
        changePercentage: 4.8,
        changePeriod: 'MoM',
        isIndustrySpecific: true,
        explanation: {
          whatIsIt: 'Monthly gross receipts generated per active clinical provider.',
          whyItMatters: 'Benchmarks clinical volume throughput, patient visit duration, and proper billing codes.',
          whatMyNumberMeans: `Each provider averages ${FinancialEngine.formatCurrency(revPerProvider, client.currency, true)} monthly in collections.`,
          formula: 'Monthly Net Patient Revenue / Full-Time Clinical Providers',
        }
      });
    } else if (client.industry === 'restaurant') {
      const foodCostPct = latest.revenue > 0 ? (latest.cogs / latest.revenue) * 100 : 30;
      const laborCostPct = latest.revenue > 0 ? (latest.salariesAndWages / latest.revenue) * 100 : 31;
      const primeCost = foodCostPct + laborCostPct;
      results.push({
        id: 'rest_prime_cost_calc',
        name: 'Prime Cost %',
        category: 'industry',
        value: primeCost,
        formattedValue: `${primeCost.toFixed(1)}%`,
        benchmarkValue: 58,
        benchmarkFormatted: '55% - 60%',
        benchmarkStatus: primeCost <= 60 ? 'outperforming' : (primeCost <= 64 ? 'on_track' : 'critical'),
        trend: primeCost <= 61 ? 'up' : 'down',
        changePercentage: -1.2,
        changePeriod: 'MoM',
        isIndustrySpecific: true,
        explanation: {
          whatIsIt: 'Total Food & Beverage COGS plus Front/Back of house labor payroll as a percentage of revenue.',
          whyItMatters: 'Prime cost determines restaurant survival. Keeping prime cost under 60% is critical for profitability.',
          whatMyNumberMeans: `Prime costs consume ${primeCost.toFixed(1)}% of every dollar earned at the register.`,
          formula: '(Food & Bev COGS + Total Labor Costs) / Total Sales',
        }
      });
    } else if (client.industry === 'manufacturing') {
      const invTurns = latest.inventory > 0 ? (summary.totalCogs / latest.inventory) : 8;
      results.push({
        id: 'mfg_inv_turns_calc',
        name: 'Inventory Turnover',
        category: 'industry',
        value: invTurns,
        formattedValue: `${invTurns.toFixed(1)}x / yr`,
        benchmarkValue: 7.5,
        benchmarkFormatted: '6.5 - 8.5x',
        benchmarkStatus: invTurns >= 7.0 ? 'outperforming' : 'on_track',
        trend: 'up',
        changePercentage: 0.6,
        changePeriod: 'YoY',
        isIndustrySpecific: true,
        explanation: {
          whatIsIt: 'How many times per year total warehouse stock is sold and replaced.',
          whyItMatters: 'Faster inventory turnover frees trapped capital and minimizes obsolescence.',
          whatMyNumberMeans: `Inventory cycles through your plant ${invTurns.toFixed(1)} times per year.`,
          formula: 'Annual COGS / Ending Inventory Balance',
        }
      });
    }

    return results;
  }
}
