# Generated by Django 5.2.17 on 2026-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("navy", "Corporate Navy"),
                    ("midnight", "Midnight Dark"),
                    ("emerald", "Emerald"),
                    ("slate", "Slate Steel"),
                    ("indigo", "Royal Indigo"),
                    ("amber", "Amber Sunset"),
                ],
                default="navy",
                help_text="UI theme preference — persists across devices once signed in.",
                max_length=16,
            ),
        ),
    ]
