<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../tools/Practice.WorkbookProfiler/Practice.WorkbookProfiler.csproj" />
    <ProjectReference Include="../../tools/Practice.ClientImporter/Practice.ClientImporter.csproj" />
  </ItemGroup>
</Project>
